canada-ca/tracker

frontend/src/FloatingMenu.js

Icons don't convey enough meaning to users.
Users would have to guess till they end up on the page they want.

Replace floating menu icons with text

---

frontend/src/UserList.js
frontend/src/client.js

Allows a super admin to request an invite **only** at the super admin level (only for the super-admin org). Also only allows changing another user's role to SUPER_ADMIN if the change is for the super-admin org.
Closes #2393

Allow super admin to invite super admins

---

services/super-admin/package-lock.json
services/super-admin/package.json

Update super-admin service dependencies.

---

frontend/src/CreateOrganizationPage.js

Swap positions of buttons on CreateOrganizationPage.js

---

frontend/src/DmarcGuidancePage.js

Makes it so that the Web and Email guidance are the same width.

fixes #2399

---

services/super-admin/package-lock.json

Update Super Admin Dependencies

---

frontend/src/ScanCategoryDetails.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

added curves to SSL category on Web Scan card

FE add curves to guidance page

---

frontend/mocking/mocker.js
frontend/src/fixtures/orgUserListData.js

Fe fix userlist test

---

frontend/src/index.js

Fix user getting logged out when switching language

---

clients/python/Pipfile.lock

Bundling dependabot updates for the client.

Update client dependencies

---

platform/aks/kustomization.yaml
platform/staging/kustomization.yaml

This the config so that annotations are added and config is actually usable by
the operator afterwards.

Quote annotation values

---

api-js/src/email-scan/subscriptions/__tests__/dkim-scan-data.test.js
api-js/src/email-scan/subscriptions/__tests__/dmarc-scan-data.test.js
api-js/src/email-scan/subscriptions/__tests__/spf-scan-data.test.js
api-js/src/web-scan/subscriptions/__tests__/https-scan-data.test.js
api-js/src/web-scan/subscriptions/__tests__/ssl-scan-data.test.js

This is the first attempt at fixing up subscription tests, by shifting around how redis connections are handled in the tests, with moving them to setup, and tear down rather then in the test itself. Hopefully this will fix our issues.

Attempt to fix up Subscription Tests

---

frontend/src/App.js
frontend/src/LocaleSwitcher.js
frontend/src/TopBanner.js
frontend/src/TrackerButton.js
frontend/src/__tests__/TopBanner.test.js

add signin buttons to TopBanner

---

frontend/Dockerfile

Bump frontend base image to 16.3.0

---

frontend/src/AdminPage.js
frontend/src/OrganizationInformation.js

Fix admin panel org list not updating after org is created.
Closes #2448

Fix admin panel org list not updating

---

frontend/src/SignInPage.js

Create account button no longer needed on sign in page now that it is in the top bar.

remove create account button

---

frontend/src/client.js

Fe fix admin panel not showing all orgs

---

frontend/src/AdminDomains.js
frontend/src/UserList.js

Adds loading state to the "Add Domain" and "Invite User" buttons
Closes #2459

Fe add loading state to buttons

---

platform/base/istio-operator.yaml

This commmit ensures there are always two istiod instances running.

Set minReplicas to 2 for istiod

---

api-js/jest.config.js
api-js/src/user/mutations/__tests__/sign-in.test.js
api-js/src/user/mutations/sign-in.js
api-js/src/user/mutations/verify-account.js

Fixing up test coverage in the API to get coverage up on a few user related mutations.

API Fix Test Coverage

---

frontend/src/TrackerButton.js

Makes the buttons more prominent and more clearly buttons
New:
Old:

Made Tob Bar buttons more prominent

---

api-js/src/locale/en/messages.po
api-js/src/locale/fr/messages.po
api-js/src/user/mutations/__tests__/authenticate.test.js
api-js/src/user/mutations/__tests__/refresh-tokens.test.js
api-js/src/user/mutations/__tests__/reset-password.test.js
api-js/src/user/mutations/__tests__/set-phone-number.test.js
api-js/src/user/mutations/__tests__/sign-in.test.js
api-js/src/user/mutations/__tests__/update-user-password.test.js
api-js/src/user/mutations/__tests__/update-user-profile.test.js
api-js/src/user/mutations/__tests__/verify-account.test.js
api-js/src/user/mutations/__tests__/verify-phone-number.test.js
api-js/src/user/mutations/authenticate.js
api-js/src/user/mutations/refresh-tokens.js
api-js/src/user/mutations/reset-password.js
api-js/src/user/mutations/set-phone-number.js
api-js/src/user/mutations/sign-in.js
api-js/src/user/mutations/update-user-password.js
api-js/src/user/mutations/update-user-profile.js
api-js/src/user/mutations/verify-account.js
api-js/src/user/mutations/verify-phone-number.js

Updating various mutations to ensure that transactions are being used when inserting/updating/removing data from the db.

Update Mutations to Ensure Transactions Are Being Used

---

api-js/src/user/queries/__tests__/is-user-admin.test.js
api-js/src/user/queries/is-user-admin.js

This PR adds a new arg onto the `isUserAdmin` query to support checking if the user requesting user is an admin for a specific org.
```graphql
query {
isUserAdmin (orgId: "")
}
query {
isUserAdmin (orgId: "")
}
```

Update isUserAdmin to Support Individual Org Checks

---

services/dmarc-report/package-lock.json
services/dmarc-report/package.json

Update DMARC Report Service Dependencies

---

services/super-admin/package-lock.json
services/super-admin/package.json

Update Super Admin Service Dependencies

---

services/scanners/dns/dns_scanner.py
services/scanners/https/https_scanner.py
services/scanners/results/result_processor.py
services/scanners/ssl/ssl_scanner.py

These changes resolve the following two issues relating to domains that do not resolve:
https://github.com/canada-ca/tracker/issues/2414
https://github.com/canada-ca/tracker/issues/2413

Unreachable domain handling

---

platform/production/kustomization.yaml

Use the correct ip for prod.

---

frontend/src/graphql/mutations.js

Update tfa and validatition status when changing phone number

---

services/summaries/tests/test_summaries.py

Fixes test issue stemming from recent changes to collection creation logic

Create summary collections in test

---

api-js/src/organization/loaders/load-organization-connections-by-domain-id.js
api-js/src/organization/loaders/load-organization-connections-by-user-id.js
api-js/src/verified-organizations/loaders/load-verified-organization-connections-by-domain-id.js
api-js/src/verified-organizations/loaders/load-verified-organizations-connections.js

Some refactoring to get some more performance out of the queries.

Optimize Org Connection Loader Queries

---

api-js/src/email-scan/objects/__tests__/dkim-sub.test.js
api-js/src/email-scan/objects/__tests__/dmarc-sub.test.js
api-js/src/email-scan/objects/__tests__/spf-sub.test.js
api-js/src/email-scan/objects/dkim-sub.js
api-js/src/email-scan/objects/dmarc-sub.js
api-js/src/email-scan/objects/spf-sub.js
api-js/src/email-scan/subscriptions/__tests__/dkim-scan-data.test.js
api-js/src/email-scan/subscriptions/__tests__/dmarc-scan-data.test.js
api-js/src/email-scan/subscriptions/__tests__/spf-scan-data.test.js
api-js/src/email-scan/subscriptions/dkim-scan-data.js
api-js/src/email-scan/subscriptions/dmarc-scan-data.js
api-js/src/email-scan/subscriptions/spf-scan-data.js
api-js/src/web-scan/objects/__tests__/https-sub.test.js
api-js/src/web-scan/objects/__tests__/ssl-sub.test.js
api-js/src/web-scan/objects/https-sub.js
api-js/src/web-scan/objects/ssl-sub.js
api-js/src/web-scan/subscriptions/__tests__/https-scan-data.test.js
api-js/src/web-scan/subscriptions/__tests__/ssl-scan-data.test.js
api-js/src/web-scan/subscriptions/https-scan-data.js
api-js/src/web-scan/subscriptions/ssl-scan-data.js

Adding Domain Field to Subscription Types

---

api-js/src/domain/loaders/load-domain-connections-by-user-id.js
api-js/src/verified-domains/loaders/load-verified-domain-connections-by-organization-id.js
api-js/src/verified-domains/loaders/load-verified-domain-connections.js

This PR extends a refactor from the organization id domain connection loader to the other domain connection loaders.

Refactor queries in other domain loaders

---

frontend/src/graphql/queries.js

Request only the latest scan information for guidance

---

frontend/src/UserCard.js

fixes #2460
Stack doesn't support responsive styling for direction in 0.8
So There's some responsive display props.

Ux user card overflow rebase

---

services/scanners/dns/dns_scanner.py
services/scanners/https/https_scanner.py
services/scanners/ssl/ssl_scanner.py

Addresses error handling issues and minor fixes for edge cases after handling the entire domain set.

Scanner hotfix - Error handling improvements and bug fixes

---

services/scanners/dns/dns_scanner.py

Amend error logging to address potentially uninitialized variables and differentiate between exception sources.

Improve error logging

---

api-js/src/dmarc-summaries/loaders/load-dmarc-sum-connections-by-user-id.js

This PR refactors the DMARC summary connection loader similarly to #2551, resulting in better performance.

API DMARC summary connection loader query optimization

---

api-js/src/guidance-tag/loaders/load-aggregate-guidance-tags-connections.js
api-js/src/guidance-tag/loaders/load-dkim-guidance-tags-connections.js
api-js/src/guidance-tag/loaders/load-dmarc-guidance-tags-connections.js
api-js/src/guidance-tag/loaders/load-https-guidance-tags-connections.js
api-js/src/guidance-tag/loaders/load-spf-guidance-tags-connections.js
api-js/src/guidance-tag/loaders/load-ssl-guidance-tags-connections.js

This PR refactors the guidance tag connection loaders similarly to #2551, resulting in better performance.

Api optimize guidance tag queries

---

api-js/src/email-scan/loaders/load-dkim-connections-by-domain-id.js
api-js/src/email-scan/loaders/load-dkim-results-connections-by-dkim-id.js
api-js/src/email-scan/loaders/load-dmarc-connections-by-domain-id.js
api-js/src/email-scan/loaders/load-spf-connections-by-domain-id.js
api-js/src/web-scan/loaders/load-https-connections-by-domain-id.js
api-js/src/web-scan/loaders/load-ssl-connections-by-domain-id.js

This PR refactors the result (HTTPS, DMARC, etc.) connection loaders similarly to #2551, resulting in better performance.

Api optimize results queries

---

services/super-admin/src/database/create-super-admin-account.js

Send SA Username to Lower Case

---

api-js/src/domain/mutations/request-scan.js
api-js/src/email-scan/objects/__tests__/dkim-sub.test.js
api-js/src/email-scan/objects/__tests__/dmarc-sub.test.js
api-js/src/email-scan/objects/__tests__/spf-sub.test.js
api-js/src/email-scan/objects/dkim-sub.js
api-js/src/email-scan/objects/dmarc-sub.js
api-js/src/email-scan/objects/spf-sub.js
api-js/src/email-scan/subscriptions/__tests__/dkim-scan-data.test.js
api-js/src/email-scan/subscriptions/__tests__/dmarc-scan-data.test.js
api-js/src/email-scan/subscriptions/__tests__/spf-scan-data.test.js
api-js/src/email-scan/subscriptions/dkim-scan-data.js
api-js/src/email-scan/subscriptions/dmarc-scan-data.js
api-js/src/email-scan/subscriptions/spf-scan-data.js
api-js/src/web-scan/objects/__tests__/https-sub.test.js
api-js/src/web-scan/objects/__tests__/ssl-sub.test.js
api-js/src/web-scan/objects/https-sub.js
api-js/src/web-scan/objects/ssl-sub.js
api-js/src/web-scan/subscriptions/__tests__/https-scan-data.test.js
api-js/src/web-scan/subscriptions/__tests__/ssl-scan-data.test.js
api-js/src/web-scan/subscriptions/https-scan-data.js
api-js/src/web-scan/subscriptions/ssl-scan-data.js
services/auto-scan/autoscan.py
services/results/result_processor.py
services/results/tests/test_result_processor.py
services/scanners/dns/dns_scanner.py
services/scanners/dns/tests/test_dns_scanner.py
services/scanners/https/https_scanner.py
services/scanners/https/tests/test_https_scanner.py
services/scanners/ssl/ssl_scanner.py
services/scanners/ssl/tests/test_ssl_scanner.py

Add a shared id for matching one-time-scans together

---

frontend/src/CreateOrganizationPage.js
frontend/src/InfoPanel.js

add glossary to Create Organization Page

---

platform/base/istio-operator.yaml

Upgrade Istio control plane

---

api-js/package-lock.json
api-js/package.json

Update API Dependencies

---

api-js/src/email-scan/objects/__tests__/dkim-sub.test.js
api-js/src/email-scan/objects/__tests__/dmarc-sub.test.js
api-js/src/email-scan/objects/__tests__/spf-sub.test.js
api-js/src/email-scan/objects/dkim-sub.js
api-js/src/email-scan/objects/dmarc-sub.js
api-js/src/email-scan/objects/spf-sub.js
api-js/src/email-scan/subscriptions/__tests__/dkim-scan-data.test.js
api-js/src/email-scan/subscriptions/__tests__/dmarc-scan-data.test.js
api-js/src/email-scan/subscriptions/__tests__/spf-scan-data.test.js
api-js/src/email-scan/subscriptions/dkim-scan-data.js
api-js/src/email-scan/subscriptions/dmarc-scan-data.js
api-js/src/email-scan/subscriptions/spf-scan-data.js
api-js/src/web-scan/objects/__tests__/https-sub.test.js
api-js/src/web-scan/objects/__tests__/ssl-sub.test.js
api-js/src/web-scan/objects/https-sub.js
api-js/src/web-scan/objects/ssl-sub.js
api-js/src/web-scan/subscriptions/__tests__/https-scan-data.test.js
api-js/src/web-scan/subscriptions/__tests__/ssl-scan-data.test.js
api-js/src/web-scan/subscriptions/https-scan-data.js
api-js/src/web-scan/subscriptions/ssl-scan-data.js
services/results/result_processor.py

Add phase and status to dmarc scan subscription

---

api-js/src/domain/mutations/__tests__/remove-domain.test.js

This PR fixes some issues with tests with related to the `removeDomain` mutation.

Remove Domain Test Fixes

---

api-js/src/domain/mutations/__tests__/remove-domain.test.js
services/queues/ots-result/tests/test_result_queue.py
services/queues/ots-scan/tests/test_scan_queue.py
services/scanners/https/https_scanner.py

Amends OTS-related logic within https-scanner and OTS queues.

OTS backend implementation update and fix

---

api-js/src/affiliation/mutations/__tests__/leave-organization.test.js
api-js/src/affiliation/mutations/leave-organization.js

This PR adds some fixes to the `leaveOrganization` that could've caused issues in the future.

API Update Leave Organization Tests

---

api-js/src/domain/mutations/__tests__/remove-domain.test.js
api-js/src/domain/mutations/remove-domain.js

Slowly but surely getting rid of these test errors.

API Updates to Fix Remove Domain Tests

---

api-js/src/domain/mutations/__tests__/remove-domain.test.js

This PR creates individual dbs for each test inside the remove domain testing script.

Update Remove Domain Tests

---

api-js/src/affiliation/mutations/__tests__/leave-organization.test.js

This PR updates the leave organization mutation tests to create individual dbs for each test

Update Leave Organization Tests

---

services/super-admin/package-lock.json

Super Admin Dependency Update

---

frontend/src/AdminDomains.js
frontend/src/AdminPage.js
frontend/src/Domain.js
frontend/src/OrganizationInformation.js
frontend/src/UserList.js

adds gap between org select and create org on small screens
adds gap between buttons and UserCard on small screens
fixes spacing of delete/edit org on small screens
fixes size of verified check
better uses space on large screens by making Domain information one line

improve AdminPage formatting

---

frontend/src/AdminPage.js

create spacing between Dropdown and `Create Org` button

---

app/aks/kustomization.yaml
app/gke/kustomization.yaml
deploy/bases/queue-registries.yaml

This PR removes references to deleted queue overlays and fixes image paths for queues.

Fix flux for queues

---

frontend/src/OrganizationCard.js

Fix overcard overflow

---

frontend/src/RelayPaginationControls.js

Adds an outline and spacing to the pagination controls

Update pagination controls styling

---

frontend/src/TopBanner.js

Makes spacing on sign in buttons the same for each space.

Fix sign in buttons spacing

---

frontend/src/AdminPage.js

Align create org button

---

services/queues/ots-result/result_queue.py
services/queues/ots-scan/scan_queue.py

As described. Checkpoints currently not handled by the api.

Comment out scan and result queue checkpoints

---

frontend/src/AdminPanel.js

change tab variant on Admin Panel

---

frontend/src/UserCard.js

add coloured badges to UserCard

---

frontend/src/InfoPanel.js
frontend/src/OrganizationDomains.js

Add glossary to organizations/domain

---

frontend/package-lock.json
frontend/src/AdminDomainModal.js
frontend/src/AdminDomains.js
frontend/src/App.js
frontend/src/__tests__/AdminDomains.test.js
frontend/src/__tests__/App.test.js
frontend/src/__tests__/Dropdown.test.js
frontend/src/__tests__/EmailValidationPage.test.js
frontend/src/__tests__/UserCard.test.js

Removes errors from test output. These messages didn't cause any errors, but clogged up the test output.

Fe remove errors from tests

---

api-js/src/locale/en/messages.js
api-js/src/locale/en/messages.po
api-js/src/locale/fr/messages.js
api-js/src/locale/fr/messages.po
api-js/src/organization/mutations/__tests__/remove-organization.test.js
api-js/src/organization/mutations/remove-organization.js

This PR implements the new algorithm for removing organizations, and their related data.

More Updates to Remove Organization Mutation

---

frontend/src/OrganizationCard.js

an attempt to fix #2688
uses a boolean and conditionals in place of directly using the Chakra components
``` const hasButton = useBreakpointValue({ base: true, md: false }) ```

fix OrgCard button

---

api-js/src/domain/mutations/__tests__/remove-domain.test.js

This PR mocks all database interactions for the `removeDomain` mutation for the "failing" portion of the tests.

Mock DB in Remove Domain Failing Tests 

---

frontend/src/AdminDomainModal.js
frontend/src/AdminDomains.js
frontend/src/UserList.js
frontend/src/__tests__/UserList.test.js

All buttons that have no text now have a proper label
fixes  #2636
If you want all buttons, even with text, to have labels, I can add onto this pull request.

Add labels it IconButtons

---

frontend/src/App.js

define exact path for TOS page link

---

services/results/result_processor.py
services/results/utils.py
services/scanners/dns/dns_scanner.py
services/scanners/https/https_scanner.py
services/scanners/ssl/ssl_scanner.py

Ensure json dictionaries are formatted correctly and .loads/.dumps are used consistently. Ensure we are taking into account the format of incoming payloads

Json formatting consistency

---

frontend/package-lock.json
frontend/package.json

:tada: 
Goodbye `The width(500) and height(500) are both fixed numbers, maybe you don't need to use a ResponsiveContainer` you  won't be missed!

Remove unused recharts dependency

---

frontend/package-lock.json
frontend/package.json

Remove unused qrcode.react dependency

---

frontend/src/__tests__/useDocumentTitle.test.js

Add test for useDocumentTitle hook

---

frontend/src/OrganizationDetails.js

If the number of users is 0, user count is currently not shown. This PR fixes this case.

Fe fix org user count

---

frontend/src/OrganizationDetails.js
frontend/src/OrganizationSummary.js

Fix org user tab not rendering

---

frontend/src/App.js

Redirect users from sign-in page when already logged in

---

frontend/src/CreateOrganizationPage.js

Fix form not submitting, remove form requirements for "sector" and "zone" fields

Fix create organization page

---

frontend/src/AdminPage.js
frontend/src/OrganizationInformation.js

Admin page doesn't work when user only has admin privileges on one org. This PR will fix this issue. Also conditionally renders "zone" and "sector" in the information pane

Fix admin page when only one org

---

frontend/package.json
frontend/src/__tests__/AdminDomains.test.js
frontend/src/__tests__/OrganizationInformation.test.js

Globally increase jest test timeout

---

frontend/mocking/mocker.js

Fix findMe resolver mock

---

frontend/src/Dropdown.js

Switch Dropdown.js to ChakraUI

---

frontend/src/OrganizationDetails.js
frontend/src/OrganizationSummary.js
frontend/src/graphql/mutations.js

might move button to same line as org name, just worried about longer org names/smaller screens
Maybe move to bottom.
Having some issues with 'LeaveOrg' not being defined?

Leave Org Button

---

frontend/src/LandingPage.js
frontend/src/__tests__/App.test.js

New text written by Greggory, reviewed by Sheldon.

Change landing page text

---

frontend/src/FloatingMenu.js

Fix mobile sign out

---

services/queues/ots-result/tests/test_result_queue.py
services/queues/ots-scan/tests/test_scan_queue.py
services/scanners/dns/server.py
services/scanners/https/server.py
services/scanners/ssl/server.py

Remove manual json encoding for posts

---

frontend/src/LandingPage.js
frontend/src/__tests__/App.test.js

This reverts commit b672ccadedcf8bd695764dc5d2ad3fe380fa79a0.

Revert "Change landing page text (#2772)"

---

services/super-admin/package-lock.json
services/super-admin/package.json

Super Admin Service Dependencies Update

---

services/dmarc-report/package-lock.json
services/dmarc-report/package.json

DMARC Report Service Dependency Updates

---

app/bases/tracker-frontend-deployment.yaml
frontend/src/AdminDomainModal.js
frontend/src/DmarcGuidancePage.js
frontend/src/DmarcReportPage.js
frontend/src/GuidanceTagDetails.js
frontend/src/__tests__/AdminDomains.test.js
frontend/src/theme/canada.js

addresses some of  #2698
Here are some colours that fix some of the contrast issues.
Info: 1476d8
red.500 (error): e50003
Teal-500 (link): 007984
Teal-600 (link): 007072

update colours for contrast fixes

---

api-js/src/affiliation/mutations/invite-user-to-org.js

Invite Links Expire After 24 Hrs

---

frontend/src/UserList.js
frontend/src/UserListModal.js
frontend/src/__tests__/UserList.test.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

Refactor `Userlist.js` so that inviting and editing users are all in a new modal component

Fe move user invite to modal

---

api-js/src/user/mutations/__tests__/close-account.test.js
api-js/src/user/mutations/close-account.js

So turns out I really messed up the first implementation of this one by not actually removing the users account ... this PR however fixes that mistake :tada:

Fix Up Closing Account Issues

---

api-js/src/locale/en/messages.js
api-js/src/locale/en/messages.po
api-js/src/locale/fr/messages.js
api-js/src/locale/fr/messages.po
api-js/src/summaries/queries/mail-summary.js
api-js/src/summaries/queries/web-summary.js

Remove translations for summary names

---

frontend/mocking/mocker.js
frontend/src/DmarcReportPage.js

Add whitespace to dmarc report tables

---

frontend/mocking/faked_schema.js
frontend/src/UserPage.js

closing your account still leaves you 'signed in',

Sign out on close account

---

frontend/src/client.js

Change "Accept-Language" connection param to "AcceptLanguage"

Change accept-language socket connection param name

---

frontend/src/html.js

make favicon pull from root directory

---

services/scanners/dns/server.py
services/scanners/https/server.py
services/scanners/ssl/server.py

Add extra logging

---

frontend/src/locales/en.po
frontend/src/locales/fr.po

Update frontend translations

---

frontend/src/admin/AdminPage.js
frontend/src/admin/__tests__/AdminPage.test.js
frontend/src/components/Dropdown.js
frontend/src/components/__tests__/Dropdown.test.js
frontend/src/graphql/queries.js

admin org search/select box now calls query while searching

Dynamically search admin org affiliations

---

api-js/src/affiliation/mutations/__tests__/update-user-role.test.js
api-js/src/affiliation/mutations/update-user-role.js
api-js/src/affiliation/objects/__tests__/update-user-role-result.test.js
api-js/src/affiliation/objects/update-user-role-result.js

Return User in updateUserRole

---

frontend/src/app/App.js

Redirect non-users from UserPage to Sign in

---

frontend/src/auth/CreateUserPage.js
frontend/src/auth/ResetPasswordPage.js
frontend/src/auth/SignInPage.js
frontend/src/auth/TwoFactorAuthenticatePage.js
frontend/src/components/AuthenticateField.js
frontend/src/components/DisplayNameField.js
frontend/src/components/EmailField.js
frontend/src/components/FormField.js
frontend/src/components/PasswordConfirmation.js
frontend/src/components/PasswordField.js
frontend/src/components/__tests__/AuthenticateField.test.js
frontend/src/components/__tests__/EmailField.test.js
frontend/src/user/EditableUserPhoneNumber.js
frontend/src/user/PhoneNumberField.js

Fields all used the basic layout,
so now they build off of FieldForm's template

Combine fields

---

services/super-admin/package-lock.json
services/super-admin/package.json

Super Admin Service Dependency Update - August 20, 2021

---

api-js/package-lock.json
api-js/package.json

API Dependency Update - August 20, 2021

---

scripts/insert-json/package-lock.json
scripts/insert-json/package.json

Insert JSON Script Dependency Update - August 20, 2021

---

frontend/src/user/PhoneNumberField.js

Fix padding property

---

frontend/src/admin/AdminDomianCard.js
frontend/src/app/App.js
frontend/src/app/FloatingMenu.js
frontend/src/app/TopBanner.js

combines checks using the ternary operator.

combine checks

---

guidance/chartSummaryCriteria.json

Update Mail Doughnut Requirements

---

ci/Dockerfile

This commit bumps the version of Ubuntu so that we have the latest python,
removes postgres stuff, and adds the latest pipenv.

Update ci image Dockerfile

---

frontend/src/admin/AdminDomainCard.js
frontend/src/admin/AdminDomains.js
frontend/src/admin/__tests__/AdminDomainCard.test.js
frontend/src/dmarc/__tests__/DmarcReportPage.test.js

Changes AdminDomianCard to AdminDomainCard

Fix AdminDomainCard name (typo)

---

scanners/domain-dispatcher/index.js
scanners/domain-dispatcher/src/__tests__/dispatch.test.js
scanners/domain-dispatcher/src/dispatch.js

This commit gets the domain dispatcher to await the publishing of the message
to nats.

Await nats publish

---

frontend/src/app/App.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

Changes message in "Pre-Alpha" banner:
EN:
FR:

Change "Pre-Alpha" to "BETA"

---

frontend/src/app/PhaseBanner.js

Change "BETA" tag appearance

---

scanners/tls-processor/poetry.lock
scanners/tls-processor/pyproject.toml
scanners/tls-processor/requirements.txt

This sheds some dependencies from service.

Clean up tls-processor dependencies

---

frontend/src/admin/OrganizationInformation.js
frontend/src/auth/SignInPage.js
frontend/src/createOrganization/CreateOrganizationPage.js
frontend/src/user/UserPage.js
frontend/src/utilities/fieldRequirements.js

Fix match email validation (for closing account)

---

scripts/insert-json/package-lock.json
scripts/insert-json/package.json

Insert JSON Script Deps Update

---

api-js/package-lock.json
api-js/package.json
api-js/src/server.js
app/bases/tracker-api-virtual-service.yaml

This PR adds in GraphQL Voyager as an express middleware providing a greater insight to the API's schema.

API add GraphQL-Voyager Middleware

---

scanners/tls-scanner/service.py

This commit simplifies the connection setup, and passes a correctly formed
argument to the "servers" option.

Fix nats connection setup for tls-scanner

---

scanners/tls-processor/.dockerignore
scanners/tls-processor/kustomization.yaml
scanners/tls-processor/tls-processor-deployment.yaml
scanners/tls-processor/tls_processor/__init__.py

This commit adds kubernetes config and cleans up the args to nats so the
service starts.

Make tls-processor deployable

---

scanners/nats/kustomization.yaml
scanners/nats/nats-deployment.yaml
scanners/nats/nats-service.yaml
scanners/nats/pubsub-namespace.yaml

Basic config to get the data flowing.

Add nats to scanners@next

---

scanners/counter/counter-deployment.yaml
scanners/counter/index.js

This commit corrects the initial connection to nats and gets the service
properly listening on domains.>

Fix counter service nats connection

---

frontend/src/app/App.js
frontend/src/domains/DomainsPage.js

Remove one time scans area

---

scanners/https-processor/https-processor-deployment.yaml
scanners/https-processor/https_processor.py

Adding a proper name and some other logging to help debugging.

Add nats name to https-proccessor

---

scanners/https-scanner/https-scanner-deployment.yaml
scanners/kustomization.yaml
scanners/tls-scanner/tls-scanner-deployment.yaml

This centralizes the replica handling into a single place and lets kustomize
handle it.

Move replica handling to kustomization

---

Makefile
app/jobs/guidance-job.yaml

This command runs the guidance job, which populates the *GuidanceTags
collections.

Add `make guidance` command

---

frontend/src/components/TrackerTable.js
frontend/src/dmarc/DmarcByDomainPage.js
frontend/src/dmarc/__tests__/DmarcByDomainPage.test.js

Add server side pagination back to dmarc summary page

---

Makefile

Fixing up superadmin credentials and removing unused guidance creds.

Clean up test creds in makefile

---

services/summaries/summaries-job.yaml

add namespace tag to summaries job

Run Summary Job in Proper Namespace

---

scanners/docker-compose.yaml

These changes are aimed at making testing a little easier.

Add counter to docker-compose and set replicas=1

---

frontend/mocking/faked_schema.js
frontend/mocking/mocker.js
frontend/src/graphql/queries.js
frontend/src/landing/LandingPageSummaries.js
frontend/src/summaries/Doughnut.js
frontend/src/summaries/SummaryCard.js
frontend/src/summaries/SummaryGroup.js
frontend/src/summaries/__tests__/SummaryGroup.test.js
frontend/src/summaries/patterns.js

Replaces the email card with a DMARC phase  card:

Fe add phase donut

---

app/aks/backup-cronjob.yaml
app/aks/kustomization.yaml
app/bases/backup-service-account.yaml
app/bases/kustomization.yaml
app/gke/backup-cronjob.yaml
app/gke/backup-service-account.yaml
app/gke/kustomization.yaml
app/production/backup-cronjob.yaml
app/production/kustomization.yaml
app/staging/backup-cronjob.yaml
app/staging/kustomization.yaml
app/test/backup-cronjob.yaml
app/test/kustomization.yaml

This backup runs every day at 4 AM. This commit closes #2538 and #2756.

Add backup cronjob

---

scripts/domain-loader/README.md

Remove json formatting from example that is not json

Remove json formatting from example

---

api/src/scalars/__tests__/scalar-organization-acronym.test.js
api/src/scalars/organization-acronym.js

Api allow lowercase acronyms

---

services/summaries/summaries.py

Fix keyError when trying to access 'phase' on domain when it does not exist

---

services/summaries/summaries.py

Fix dict property syntax

---

app/jobs/backup/aks/backup-job.yaml
app/jobs/backup/base/backup-job.yaml
app/jobs/backup/gke/backup-job.yaml
app/jobs/backup/staging/backup-job.yaml
app/jobs/backup/test/backup-job.yaml
app/jobs/scan-job.yaml
app/jobs/super-admin.yaml
scanners/domain-dispatcher/domain-dispatcher-job.yaml
services/guidance/guidance-job.yaml
services/summaries/summaries-job.yaml

Replace batch/v1beta1 with batch/v1 for kind: Job

Use batch/v1 for Kind: Job

---

scripts/domain-loader/src/add-organizations-domains.js
scripts/domain-loader/src/helpers/__tests__/check-claim.test.js
scripts/domain-loader/src/helpers/check-claim.js

Switch to .next() from .all()

---

scanners/tls-processor/tls_processor/__init__.py

This commit ensures that domains marked as unreachable receive are marked as
"info".

Fix tls handling of unreachable domains

---

scanners/kustomization.yaml

As described, upping tls scanners, but reducing https.

Add more tls scanners

---

api/src/domain/objects/__tests__/domain-status.test.js
api/src/domain/objects/domain-status.js

This commit modifies the apis policy resolver to handle unreachable domains,
which result in "info".

Update api policy resolver to handle info

---

api/src/summaries/queries/https-summary.js
services/summaries/summaries.py
services/summaries/tests/test_summaries.py

Add https summaries

---

frontend/mocking/faked_schema.js
frontend/mocking/mocker.js
frontend/src/graphql/queries.js
frontend/src/landing/LandingPageSummaries.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/organizationDetails/OrganizationSummary.js
frontend/src/organizationDetails/__tests__/OrganizationDetails.test.js
frontend/src/summaries/SummaryGroup.js
frontend/src/summaries/__tests__/SummaryGroup.test.js

Fe add https donut

---

api/src/organization/objects/__tests__/organization-summary.test.js
api/src/organization/objects/organization-summary.js
services/summaries/summaries.py
services/summaries/tests/test_summaries.py

Add dmarc summary to summary service and api

---

frontend/mocking/faked_schema.js
frontend/src/components/fields/AuthenticateField.js
frontend/src/graphql/queries.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/organizations/OrganizationCard.js
frontend/src/organizations/Organizations.js
frontend/src/organizations/__tests__/Organizations.test.js

Aligns organization summary bars with summaries on home page:

Change organization summary bars to "HTTPS" and "DMARC"

---

scripts/db/README.md
scripts/db/add-timestamps.js
scripts/db/remove-orphans.js

This commit adds some scripts for data munging.

Add db scripts

---

frontend/src/dmarc/DmarcByDomainPage.js

Fix "items per page" button

---

frontend/src/graphql/queries.js

This query was never imported anywhere so killing it with 🔥

Remove unused graphql query

---

frontend/src/admin/AdminPage.js
frontend/src/admin/__tests__/AdminPage.test.js
frontend/src/graphql/queries.js

This commit combines the  isUserSuperAdmin query with the findMyDomains query
to eliminate some of the network traffic.

 Merge queries on AdminPage

---

frontend/src/admin/__tests__/UserListModal.test.js

Fix flakey UserListModal test

---

frontend/src/locales/en.po
frontend/src/locales/fr.po

This commit is the result of running
```
[mike@ouroboros frontend]$ npm run extract -- --clean
> tracker-frontend@0.1.0 extract
> lingui extract "--clean"
Catalog statistics for src/locales/{locale}:
┌─────────────┬─────────────┬─────────┐
│ Language    │ Total count │ Missing │
├─────────────┼─────────────┼─────────┤
│ en (source) │     547     │    -    │
│ fr          │     547     │    0    │
└─────────────┴─────────────┴─────────┘
```

Clean out translation files

---

frontend/mocking/mocker.js

Fix mocked connections for organization domains and affiliations

---

scanners/log4shell-processor/index.js
scanners/log4shell-processor/log4shell-processor-deployment.yaml

Single stringified line instead of multiline strings.

Make logging more gcp friendly

---

scanners/kustomization.yaml
scanners/log4shell-scanner/log4shell-scanner-deployment.yaml
scanners/log4shell-scanner/service.py

More get request

---

deploy/bases/kustomization.yaml
deploy/bases/log4shell-processor-registry.yaml
deploy/bases/log4shell-scanner-registry.yaml
deploy/gke/kustomization.yaml
deploy/gke/log4shell-processor-image-policy.yaml
deploy/gke/log4shell-scanner-image-policy.yaml
deploy/log4shell-scanner-image-policy.yaml
scanners/log4shell-processor/cloudbuild.yaml
scanners/log4shell-processor/log4shell-processor-deployment.yaml
scanners/log4shell-scanner/log4shell-scanner-deployment.yaml

After all what are we... barbarians?

Automate log4shell related things

---

scanners/log4shell-processor/Dockerfile
scanners/log4shell-processor/index.js

fix: port for DNS server

---

scanners/log4shell-processor/index.js

Adds a small error handler to return empty questions

fix: DNS error handling

---

scripts/hash-domains/.env.example
scripts/hash-domains/.eslintignore
scripts/hash-domains/.eslintrc
scripts/hash-domains/.prettierrc
scripts/hash-domains/database-options.js
scripts/hash-domains/index.js
scripts/hash-domains/package-lock.json
scripts/hash-domains/package.json

This is just a simple hashing script that will go through the db and add hashes to domain entries.

Introduce Hashing Script

---

scanners/log4shell-scanner/service.py

This commit cleans up logging, prints useful status information and improves
the payload handling.

Clean up log4shell-scanner

---

app/gke/log4shell-scanner-deployment.yaml
scanners/log4shell-scanner/service.py

This commit makes an attempt at waf evasion and records response codes.

Update log4shell scanner

---

scanners/log4shell-scanner/service.py

This commit removes indent=2 so that logs aren't all multiline crazyiness.

Log on one line

---

frontend/package.json
frontend/src/app/App.js
frontend/src/app/FloatingMenu.js

Add "contact" mail link to footer

---

scanners/domain-dispatcher/src/__tests__/dispatchDomains.test.js
scanners/domain-dispatcher/src/__tests__/getCursor.test.js

The tests were using the wrong env var.

Get tests using DB_PASS instead of DB_PASSWORD

---

services/summaries/summaries.py

Use `.domain.get("status", {}).get(scan_type)` instead of `domain["status"][scan_type]` to avoid `TypeError: 'NoneType' object is not subscriptable`. 
Closes #3351.

Fix "NoneType is not subscriptable" error when domain not yet scanned

---

frontend/src/app/App.js
frontend/src/app/FloatingMenu.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

Removes contact email address from "Contact" links.

Update "Contact" link text

---

scanners/domain-dispatcher/src/__tests__/dispatch.test.js

This commit cleans up some leftovers in the test data for the dispatch test.
These artifacts were leftovers from early iterations.

Fix domain-dispatch test data

---

frontend/src/dmarc/__tests__/DmarcByDomainPage.test.js
frontend/src/domains/__tests__/DomainsPage.test.js

Fix tests relying on current year

---

frontend/src/app/App.js
frontend/src/app/ContactUsPage.js
frontend/src/app/__tests__/ContactUsPage.test.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

Link in footer takes user to Contact Us page with similar format to HTTPSEverywhere.
Button is link to email.
closes #3346

Contact Us Page

---

api/src/organization/loaders/__tests__/load-organization-connections-by-user-id.test.js

Fix 'loginRequiredBool' import

---

api/src/affiliation/mutations/__tests__/remove-user-from-org.test.js
api/src/domain/mutations/__tests__/remove-domain.test.js

Skip flaky test

---

frontend/src/admin/__tests__/UserListModal.test.js

Increase waitFor timeout

---

frontend/src/user/EditableUserTFAMethod.js

Updates the tfaSendMethod of the currentUser stored in the reactiveVar after successful mutation

Update tfa method on update

---

scanners/tls-processor/tls_processor/__init__.py

Fail protocol status if cipher fails

---

scanners/tls-processor/Dockerfile

This commit adds a workaround for an issue with pip.

Fix require-hashes CI/CD failure

---

scanners/dns-processor/poetry.lock
scanners/dns-processor/requirements.txt
scanners/tls-processor/poetry.lock
scanners/tls-processor/pyproject.toml
scanners/tls-processor/requirements.txt

Update scanner requirements (Fix require-hashes CI/CD failure)

---

scanners/docker-compose.yaml
scanners/https-scanner/https-scanner-deployment.yaml
scanners/https-scanner/scan/https.py

Increase https scan timeout

---

api/src/create-context.js

Add tfaRequired to context

---

api/src/domain/mutations/__tests__/remove-domain.test.js

Skip flaky tests

---

frontend/src/graphql/queries.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/organizationDetails/OrganizationDomains.js
frontend/src/organizationDetails/__tests__/OrganizationDomains.test.js

Org domains search

---

frontend/src/domains/DomainCard.js
frontend/src/domains/DomainsPage.js
frontend/src/graphql/queries.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/organizationDetails/OrganizationDomains.js

Update text on domain cards (and in glossaries) to be more clear on what status is measuring

Update domain status text

---

api/index.js
api/package-lock.json
api/package.json
api/src/auth/check-domain-permission.js
api/src/create-context.js
api/src/domain/mutations/request-scan.js
frontend/src/domains/DomainCard.js
frontend/src/domains/ScanDomainButton.js
frontend/src/guidance/DmarcGuidancePage.js

Add scan request function to api and UI

---

services/dmarc-report/src/dmarc-report.js
services/summaries/summaries.py

Fixes dmarc report service. The dmarc domain list was updated to use the format <ORG_ENG_ACR>-<ORG_FR_ACR>. This PR updates to use this format. Also removes extra "$" symbol in logging.

Fix dmarc summaries

---

api/package-lock.json
api/package.json

Remove nodemon

---

api/index.js
api/package-lock.json
api/package.json
api/src/server.js

This function wasn't being used, and there are better ways to achieve this.

Remove arango-express

---

api/package-lock.json
api/package.json
api/src/__tests__/create-context.test.js
api/src/create-i18n.js

This commit fixes the i18n pluralization warnings unmasked by removing the
mocking of console.log.

Fix api plural warnings

---

scanners/dns-scanner/service.py

Run DKIM scan in main thread instead of in a ThreadPoolExecutor

Run DKIM scanner in main thread

---

api/index.js
api/src/create-context.js

This commit is the first step in imposing the "functional core/imperative shell" pattern.
https://www.destroyallsoftware.com/screencasts/catalog/functional-core-imperative-shell

Move env access out of createContext

---

frontend/src/app/TopBanner.js
frontend/src/components/RelayPaginationControls.js
frontend/src/components/SearchBox.js
frontend/src/domains/DomainsPage.js
frontend/src/domains/__tests__/DomainsPage.test.js
frontend/src/organizationDetails/OrganizationDetails.js
frontend/src/organizationDetails/OrganizationDomains.js
frontend/src/organizationDetails/OrganizationSummary.js
frontend/src/organizations/Organizations.js
frontend/src/organizations/__tests__/Organizations.test.js

redesign filter/pagination

---

platform/components/namespaces/istio-operator-namespace.yaml
platform/components/namespaces/kustomization.yaml

This should have been there but wasn't.

Add missing istio-operator namespace

---

scanners/dns-scanner/dns_scanner/dns_scanner.py

check_dmarc does not always return an array for rua.values and ruf.values, handle this case.

Handle case where rua.value and ruf.value are strings

---

scanners/dns-scanner/dns_scanner/dns_scanner.py
scanners/docker-compose.yaml

We receive a NoAnswer exception on prod instead of NXDOMAIN, this PR handles this.

Add noanswer exception

---

app/bases/issuers.yaml
app/gke/certificate.yaml

This commit switches the issuers to dns01, and starts gke with a staging cert.

Switch issuers to dns01

---

platform/components/istio/istio.yaml

Update istio operator to 1.13.2

---

frontend/src/landing/LandingPage.js

Using a regex to catch both domains: French and English.

Fix donut display regex.

---

app/bases/database-configmap.yaml
app/bases/kustomization.yaml
app/bases/tracker-api-deployment.yaml
database-migration/.dockerignore
database-migration/Dockerfile
database-migration/index.js
database-migration/package-lock.json
database-migration/package.json

As the name suggests this commit adds an initContainer to the tracker-api pod.
It ensures that the database is in the right state and then exits, and then the
api is started.

Add db-migration initContainer to api

---

frontend/src/admin/OrganizationInformation.js
frontend/src/app/App.js
frontend/src/app/ReadGuidancePage.js
frontend/src/app/__tests__/ReadGuidancePage.test.js
frontend/src/components/LoadingMessage.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/organizationDetails/OrganizationDetails.js
frontend/src/theme/canada.js
frontend/src/theme/components/Button.js

- New footer link taken from HTTPSEverywhere /guidance page and "Trackerized"
- updated button colour states
- updated loading message colour

Read Guidance Page

---

Makefile

This adds a command to run the dmarc-report service.

Add reports command to Makefile

---

Makefile

As advertised: This was useful when exploring/configuring the istio operator.

Add print-istio-operator cmd to makefile

---

frontend/src/admin/__tests__/UserListModal.test.js
frontend/src/app/App.js
frontend/src/components/RelayPaginationControls.js
frontend/src/domains/DomainCard.js
frontend/src/domains/DomainsPage.js
frontend/src/graphql/queries.js
frontend/src/guidance/DmarcGuidancePage.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/organizationDetails/OrganizationDetails.js
frontend/src/organizationDetails/OrganizationDomains.js
frontend/src/organizationDetails/__tests__/OrganizationDetails.test.js
frontend/src/organizations/OrganizationCard.js
frontend/src/organizations/Organizations.js
frontend/src/summaries/Doughnut.js
frontend/src/summaries/RadialBarChart.js
frontend/src/user/EditableUserDisplayName.js
frontend/src/user/EditableUserEmail.js
frontend/src/user/EditableUserLanguage.js
frontend/src/user/EditableUserPassword.js
frontend/src/user/EditableUserPhoneNumber.js
frontend/src/user/EditableUserTFAMethod.js
frontend/src/user/UserPage.js
frontend/src/user/__tests__/UserPage.test.js

- add tab names to routing on some pages to persist in history traversal
- update UserPage tests
- Clean up domain/org cards
- display error when navigating to org that doesn't exist (closes #3283)
- adds domain total and text to Summary Donuts (closes #3468)

Add Tabs to Routing

---

platform/aks/kustomization.yaml
platform/gke/kustomization.yaml
platform/minikube/kustomization.yaml
platform/production/kustomization.yaml
platform/staging/kustomization.yaml

Update istio operator namespace

---

platform/base/istio-operator.yaml

Increase maxreplicas for istiod and ingress

---

Makefile
k8s/apps/bases/api/creds/kustomization.yaml
k8s/apps/bases/api/kustomization.yaml
k8s/apps/bases/scanners/dmarc-report-cronjob/creds/kustomization.yaml
k8s/apps/bases/scanners/scanner-platform/creds/kustomization.yaml
k8s/apps/bases/scanners/scanner-platform/kustomization.yaml
k8s/infrastructure/bases/arangodb/creds/kustomization.yaml
k8s/infrastructure/bases/arangodb/kustomization.yaml
k8s/jobs/super-admin/creds/kustomization.yaml
k8s/jobs/super-admin/kustomization.yaml

Move secrets to own folder so they are not applied by default.

Move secret generator to own folder

---

k8s/infrastructure/overlays/staging/kustomization.yaml

Add arango patch in staging

---

k8s/infrastructure/overlays/gke/kustomization.yaml
k8s/infrastructure/overlays/production/kustomization.yaml
k8s/infrastructure/overlays/staging/kustomization.yaml

Update namespace to istio-system

Fix istio patch namespace

---

k8s/infrastructure/overlays/production/kustomization.yaml
k8s/infrastructure/overlays/staging/kustomization.yaml

Add gateway patch

---

k8s/infrastructure/overlays/gke/kustomization.yaml

Add kiali, jaeger, grafana, prometheus to gke deployment

Add kiali to gke

---

k8s/infrastructure/bases/arangodb/arangodb-deployment.yaml

Upgrade arangodb

---

k8s/clusters/auto-image-update/bases/kustomization.yaml

Fix git repo patch

---

services/dmarc-report/package-lock.json
services/dmarc-report/package.json

as described, in services/dmarc-report

remove unused arangojs dep

---

k8s/jobs/restore-backup/bases/kustomization.yaml
k8s/jobs/restore-backup/bases/restore-backup-job.yaml
k8s/jobs/restore-backup/overlays/gke/kustomization.yaml
k8s/jobs/restore-backup/overlays/gke/patch-restore-backup-download.yaml
k8s/jobs/restore-backup/overlays/minikube/kustomization.yaml
k8s/jobs/restore-backup/overlays/minikube/patch-restore-backup-download.yaml
k8s/jobs/restore-backup/overlays/production/kustomization.yaml
k8s/jobs/restore-backup/overlays/production/patch-restore-backup-download.yaml
k8s/jobs/restore-backup/overlays/staging/kustomization.yaml
k8s/jobs/restore-backup/overlays/staging/patch-restore-backup-download.yaml
k8s/jobs/restore-backup/overlays/test/kustomization.yaml
k8s/jobs/restore-backup/overlays/test/patch-restore-backup-download.yaml

Istio sidecar injection disabled as job pods were unable to connect to database.
Closes #3711

Add backup restore job

---

api/src/domain/mutations/__tests__/remove-domain.test.js
api/src/domain/mutations/remove-domain.js

Fix domain removal

---

frontend/src/landing/LandingPage.js

Update EN and FR links to email and web policy on landing page

Update Policy Links

---

k8s/infrastructure/overlays/test/kustomization.yaml
skaffold.yaml

Add istio tracing to test cluster

---

scanners/dns-processor/dns_processor/__init__.py

Remove required positive dkim tags for passing status

---

frontend/package-lock.json

removes need for "got" dependency bump

update nodemon to 2.0.19

---

frontend/src/utilities/fieldRequirements.js

Allow acronym with lowercase letters

---

frontend/src/admin/SuperAdminUserList.js
frontend/src/admin/UserListModal.js
frontend/src/app/ABTestVariant.js
frontend/src/app/ABTestWrapper.js
frontend/src/app/App.js
frontend/src/app/TopBanner.js
frontend/src/landing/LandingPage.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/organizationDetails/OrganizationSummary.js
frontend/src/summaries/Doughnut.js

Client side method for delivering new features to insider users based on logged in user information.
Non-logged in user view:
Logged in user, not insider:
Logged in insider:
Provide fixes for the following frontend bugs:
- fix bug with summary card percentages when numbers end in 0.5
- change DMARC card text to be more accurate
- fix bug on SA user list where the wrong info is displayed in the modal
- remove the location from the org summary (unneeded)
- add link to canada.ca in GC header image

AB Testing in Frontend

---

frontend/src/guidance/DmarcGuidancePage.js

Fix scan button on guidance page

---

frontend/src/app/ReadGuidancePage.js
frontend/src/domains/DomainCard.js
frontend/src/domains/DomainsPage.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

updates Read Guidance page to new guidance and FAQ.
Begin removing references to ITPIN
closes #4004 
closes #4021

Tracker 2.1 Guidance

---

frontend/src/admin/__tests__/UserListModal.test.js
frontend/src/app/App.js
frontend/src/app/__tests__/FloatingMenu.test.js

Fix email verify page

---

frontend/src/admin/__tests__/AdminDomains.test.js
frontend/src/app/App.js

Fix AB Wrapper on navbar

---

frontend/src/guidance/EmailGuidance.js

Fix email guidance page when dkim results did not exist

Fix email guidance page

---

frontend/src/organizationDetails/OrganizationDomains.js

Add subdomain warning to organization domains page

---

api/src/domain/mutations/create-domain.js

add updatedProperties to logActivity input

---

k8s/apps/bases/scanners/https-scanner/deployment.yaml
k8s/apps/bases/scanners/tls-scanner/deployment.yaml

Add 192.168.0.0/16 to proxy range (required for aks)

---

k8s/infrastructure/bases/istio/ecdh-curves-patch.yaml
k8s/infrastructure/bases/istio/kustomization.yaml

Add ecdh curve patch to only include p-256

---

frontend/src/domains/DomainCard.js

move org-level domain tags position on domain cards

---

scanners/dns-processor/dns_processor/__init__.py

Change DKIM tag strengths to be less strict

---

scanners/dns-processor/dns_processor/__init__.py

Change tags which fail dkim status

---

api/index.js
api/src/affiliation/mutations/invite-user-to-org.js
api/src/audit-logs/objects/target-resource.js
api/src/create-context.js
api/src/organization/mutations/create-organization.js
api/src/organization/mutations/remove-organization.js
api/src/organization/mutations/update-organization.js
api/src/user/mutations/close-account.js
frontend/src/admin/AuditLogTable.js
frontend/src/admin/__tests__/AuditLogTable.test.js

provides various small fixes to the activity logging:
- smaller timestamp format
- uses username in place of id when logging close-account mutation
- logs translated org names for create,update,remove org mutations
- adds userRole to logs when adding user to org
- translates tags in domain logs

Update activity logging

---

frontend/src/fixtures/dmarcGuidancePageData.js
frontend/src/graphql/queries.js
frontend/src/guidance/GuidancePage.js

as described, org names link to org details page
closes #4003

add organizations to domain guidance page

---

api/package-lock.json
api/package.json

as described, mitigates CVE-2022-23529

bump notifications-node-client to 6.0.0

---

k8s/apps/overlays/gke/domain-dispatcher-suspend-patch.yaml
k8s/apps/overlays/gke/kustomization.yaml
k8s/apps/overlays/staging/domain-dispatcher-suspend-patch.yaml
k8s/apps/overlays/staging/kustomization.yaml

Suspend daily scans on gke and staging

---

scanners/https-scanner/scan/https.py

Google repo changed from master to main, reflect in link

Update preload url

---

scanners/https-scanner/Dockerfile
scanners/https-scanner/scan/query_crlite.py

Move from old moz-crlite-query to rust-query-crlite

Use rust-query-crlite

---

frontend/src/components/TrackerTable.js
frontend/src/dmarc/DmarcReportPage.js

DMARC report export feature is currently broken. Only exports 1 row and includes extra data (__typename for example). This PR fixes this issue.

Fix dmarc csv export feature

---

frontend/src/app/App.js

Remember navigation state of private pages between refreshes

---

frontend/src/auth/CreateUserPage.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/termsConditions/TermsConditionsPage.js

Add link to terms agreement when creating account
closes #4188

Fix register terms and conditions

---

Makefile
k8s/infrastructure/bases/istio/istio-operator-deployment.yaml
k8s/infrastructure/bases/istio/istio-operator.yaml
k8s/infrastructure/bases/istio/kustomization.yaml
k8s/infrastructure/bases/istio/platform/crds.yaml
k8s/infrastructure/bases/istio/platform/kustomization.yaml
skaffold.yaml

Update istio and istio operator to 1.16.2

Upgrade istio to 1.16.2

---

k8s/infrastructure/bases/arangodb/platform/kustomization.yaml

Update kube arangodb to 1.2.24 (latest)

---

services/summaries/summaries.py

fix every archived ocnditional in summaries job

---

services/summaries/summaries.py

as described, will be reverted once all new domains are in prod.

temporarily exclude hidden domains from landing page summaries

---

api/src/domain/loaders/load-domain-connections-by-organizations-id.js

as described, to be reverted after all new domains are added

temporarily hide hidden domains from admins

---

services/summaries/summaries.py

as described, to revert after domains are in

hide hidden domains from dmarc phase summary

---

scanners/web-scanner/requirements.txt

as described, required for latest sslyze

bump nassl to 5.0.1

---

k8s/infrastructure/overlays/gke/kustomization.yaml
k8s/infrastructure/overlays/test/kustomization.yaml

Remove unused jaeger and kiali k8s resources

---

scanners/dns-processor/dns_processor/dns_processor.py

add additional default value for dkim_tags that was causing errors when dkim results are None

fix processing of null dkim results

---

api/src/domain/loaders/load-domain-connections-by-organizations-id.js
api/src/domain/loaders/load-domain-connections-by-user-id.js
api/src/enums/domain-order-field.js
frontend/src/domains/DomainsPage.js
frontend/src/graphql/fragments.js
frontend/src/graphql/queries.js
frontend/src/organizationDetails/OrganizationDomains.js

add certificates value as an order by and filtering option

Add certificates to filters

---

api/src/affiliation/mutations/__tests__/invite-user-to-org.test.js
api/src/affiliation/mutations/invite-user-to-org.js
api/src/notify/__tests__/notify-send-org-invite-create-account.test.js
api/src/notify/notify-send-org-invite-create-account.js

Send bilingual org invite/create account email

---

frontend/src/app/TopBanner.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

change wording from INSIDER to PREVIEW

change feature preview banner wording

---

frontend/src/summaries/Doughnut.js

Ensure all email and web charts have the appropriate domain text

Fix tiered summary chart text

---

services/summaries/summaries.py

Exclude domains that return blocked or NXDOMAIN status for summaries
closes #4407

use ignore_domain func to exclude domains from summaries

---

app/aks/backup-cronjob.yaml
app/bases/dmarc-report-cronjob.yaml
app/bases/guidance-cronjob.yaml
app/bases/scan-dispatcher-cronjob.yaml
app/bases/summaries-cronjob.yaml
app/gke/backup-cronjob.yaml
app/production/backup-cronjob.yaml
app/staging/backup-cronjob.yaml
app/test/backup-cronjob.yaml
k8s/apps/bases/api/org-footprint-cronjob.yaml
k8s/apps/bases/scanners/dmarc-report-cronjob/cronjob.yaml
k8s/apps/bases/scanners/domain-dispatcher-cronjob/cronjob.yaml
k8s/apps/bases/scanners/summaries-cronjob/cronjob.yaml
k8s/apps/overlays/gke/domain-dispatcher-suspend-patch.yaml
k8s/apps/overlays/staging/domain-dispatcher-suspend-patch.yaml
k8s/infrastructure/overlays/gke/backup-cronjob.yaml
k8s/infrastructure/overlays/production/backup-cronjob.yaml
k8s/infrastructure/overlays/staging/backup-cronjob.yaml
k8s/infrastructure/overlays/test/backup-cronjob.yaml

`batch/v1beta1` is no longer supported, change api version to `batch/v1`.

Update k8s cronjob versions

---

k8s/clusters/auto-image-update/bases/image-repo-policies/org-footprint-image-repo-policy.yaml
services/org-footprint/cloudbuild.yaml

add services dir to image path in org-footprint cloudbuild

---

frontend/src/graphql/mutations.js

fixes error when inviting user through admin page

change RoleEnum to InvitationRoleEnums in InviteUserToOrg mutation

---

frontend/src/admin/AdminDomainModal.js

change addable tags to buttons in AdminDomainModal

---

api/src/organization/mutations/__tests__/remove-organization.test.js
api/src/organization/mutations/remove-organization.js

Allow owners to remove unverified organizations

---

frontend/src/admin/OrganizationInformation.js
frontend/src/admin/__tests__/OrganizationInformation.test.js

remove zone and sector values from OrganizationInformation component
closes #4601

Remove unneeded org info from admin page

---

k8s/apps/bases/api/domain-cleanup-cronjob.yaml
services/org-footprint/src/__tests__/notify-send-org-footprint-email.test.js
services/org-footprint/src/notify/notify-send-org-footprint-email.js

Add scans to org footprint emails

---

api/src/domain/loaders/load-domain-connections-by-user-id.js
api/src/domain/mutations/__tests__/remove-domain.test.js
api/src/domain/mutations/remove-domain.js
api/src/user/loaders/load-my-tracker-by-user-id.js
services/domain-cleanup/database-options.js
services/domain-cleanup/src/__tests__/domain-cleanup-service.test.js
services/domain-cleanup/src/remove-nxdomain-service.js

- Fix removal of favourites edges on domain removal
- ~~Filter out dead edges on myTracker page~~
closes #4612

Fix my tracker domains

---

frontend/src/guidance/EmailGuidance.js
frontend/src/guidance/GuidancePage.js
frontend/src/guidance/WebGuidance.js

add timestamps to scan results
closes #3170

add timestamp to scan results

---

frontend/src/app/App.js
frontend/src/auth/CreateUserPage.js
frontend/src/auth/SignInPage.js
frontend/src/auth/TwoFactorAuthenticatePage.js
frontend/src/graphql/fragments.js
frontend/src/index.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/utilities/userState.js

Provide a banner for unaffiliated users stating they will unlock features upon affiliation
closes #4610

Warn user they are not affiliated

---

clients/python/Pipfile
clients/python/Pipfile.lock
clients/python/tests/test_client.py
clients/python/tracker_client/client.py
clients/python/tracker_client/domain.py
clients/python/tracker_client/organization.py

Major updates including updates for `cryptography` and `black`.

Update python client

---

api/src/affiliation/mutations/request-org-affiliation.js

add service account email to list of aff request notifications

---

k8s/apps/overlays/gke/kustomization.yaml
k8s/apps/overlays/production/kustomization.yaml
k8s/apps/overlays/staging/kustomization.yaml

Scale dns-scanner count from 3 to 6

---

api/src/user/mutations/__tests__/authenticate.test.js
api/src/user/mutations/__tests__/refresh-tokens.test.js
api/src/user/mutations/__tests__/sign-in.test.js
api/src/user/mutations/__tests__/sign-up.test.js
api/src/user/mutations/authenticate.js
api/src/user/mutations/refresh-tokens.js
api/src/user/mutations/sign-in.js
api/src/user/mutations/sign-up.js
frontend/mocking/faked_schema.js
frontend/src/graphql/mutations.js
frontend/src/index.js

replace setTimeout with setInterval for continuous session handling
closes #4173

Bugfix handle session timeout

---

api/src/user/mutations/__tests__/close-account.test.js
api/src/user/mutations/close-account.js
frontend/src/admin/SuperAdminUserList.js
frontend/src/graphql/mutations.js
frontend/src/user/UserPage.js

Separate closeAccount mut into closeAccountSelf and closeAccountOther to prevent input contamination
closes #3801

Bugfix separate close account functions

---

k8s/apps/bases/scanners/domain-discovery/deployment.yaml
scanners/domain-discovery/Dockerfile
scanners/domain-discovery/domain_discovery.py

Fix issues with current Docker build of domain-discovery

Bugfix domain discovery permissions

---

k8s/clusters/auto-image-update/bases/image-repo-policies/kustomization.yaml

Remove unused image policy

---

services/org-footprint/src/database/get-new-audit-logs.js

Do not send emails if only logs are scans and exports
closes #4472

Only send footprint changes

---

api/src/server.js

allows us to use GraphQL Studio

use default non-prod landing page for graphql endpoint

---

scripts/mass-invite-users/massInviteUsers.js

Script now checks for any missing information and checks current affiliation status for each requested invite, updating roles instead if affiliation already exists.

Upgrade mass invite script

---

scanners/dns-processor/service.py

Fix dns processor slowness

---

services/org-footprint/src/org-footprint-service.js

use env var to include service account in footprint updates

---

frontend/src/admin/AdminPage.js
frontend/src/components/Dropdown.js

select admin org for user if only part of 1 org

---

scanners/dns-scanner/dns_scanner/email_scanners.py

Cache tld extract

---

frontend/src/organizationDetails/OrganizationDomains.js
frontend/src/organizationDetails/__tests__/OrganizationDomains.test.js

filter org domains to only show web domains by default

---

frontend/src/admin/AdminDomainModal.js

use trim() method when submitting domain for adding or updating

---

scanners/spring4shell/Dockerfile

bump base image in spring4shell/Dockerfile

---

frontend/src/admin/AdminPanel.js
frontend/src/admin/UserList.js
frontend/src/admin/__tests__/AdminPage.test.js
frontend/src/admin/__tests__/UserList.test.js

match search component on admin userlist to admin domain list
adds ability to change items per page

Feature add search box to admin org users

---

api/src/organization/mutations/__tests__/verify-organization.test.js
api/src/organization/mutations/verify-organization.js

unarchive org domains when verifying

---

scanners/dns-scanner/dns_scanner/email_scanners.py

Set default value for DKIM key type

---

frontend/src/graphql/queries.js
frontend/src/guidance/EmailGuidance.js

Fix order of MX record diffs on guidance

---

scanners/dns-processor/notify/send_mx_diff_email_alerts.py

get rid of db query to find mx stakeholders

---

k8s/apps/bases/api/progress-report-cronjob/cronjob.yaml
services/progress-report/src/progress-report-service.js

redirect progress report emails to service account

---

api/src/domain/mutations/create-domain.js
api/src/domain/mutations/update-domain.js
api/src/scalars/__tests__/scalar-selector.test.js
api/src/scalars/selector.js

Remove selector regex validation for selectors already in system

---

frontend/src/admin/AdminPage.js
frontend/src/admin/OrganizationInformation.js
frontend/src/admin/__tests__/OrganizationInformation.test.js

only allow super admins to edit org acronyms

Hide acronym edit field from users

---

frontend/src/dmarc/DmarcReportPage.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

In response to the removal of duplicate data across the tables.
Closes #4943

Create notification banner for new DMARC data changes

---

k8s/apps/bases/api/progress-report-cronjob/cronjob.yaml
services/progress-report/cloudbuild.yaml
services/progress-report/src/database/find-verified-org-summaries.js

exclude unclaimed org from verified orgs in progress report

---

frontend/src/components/fields/PhoneNumberField.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/user/EditableUserPhoneNumber.js

User phone number managed device reminder

---

k8s/apps/bases/scanners/domain-dispatcher-cronjob/cronjob.yaml
k8s/infrastructure/overlays/gke/backup-cronjob.yaml
k8s/infrastructure/overlays/production/backup-cronjob.yaml
k8s/infrastructure/overlays/staging/backup-cronjob.yaml
k8s/infrastructure/overlays/test/backup-cronjob.yaml

Backup db before starting new scans

---

frontend/src/graphql/queries.js
frontend/src/organizationDetails/OrganizationDetails.js
frontend/src/organizationDetails/__tests__/OrganizationDetails.test.js
frontend/src/organizations/Organizations.js
frontend/src/organizations/__tests__/Organizations.test.js

SImple check for userHasPermission when rendering request invite button
closes #5034

Hide invite request button when affiliated

---

api/src/organization/objects/organization.js
frontend/src/organizationDetails/OrganizationAffiliations.js
frontend/src/organizationDetails/OrganizationDetails.js
frontend/src/organizationDetails/__tests__/OrganizationDetails.test.js

Let affiliated users see user list

---

api/package-lock.json
api/package.json

fixes 3 security issues (snyk)

bump notifications-node-client to 8.0.0 in api/package.json

---

frontend/src/landing/LandingPage.js

make landing page links more obvious

add external link icons to landing page links

---

services/summaries/summaries.py

Stop counting email info statuses as fail for summaries

only include pass/fail statuses for summaries

---

api/docker-compose.yaml

NATS and ArangoDB compose file for development. Make sure to add path to ArangoDB backup directory:
```export TRACKER_BACKUP_DIR=<BACKUP DIRECTORY FOR ARANGODB>```

Add db and nats compose file

---

scanners/web-scanner/requirements.txt
scanners/web-scanner/scan/endpoint_chain_scanner/endpoint_chain_scanner.py
scanners/web-scanner/scan/tls_scanner/tls_scanner.py

sslyze: 5.2.0 => 6.0.0
cryptography: 41.0.7 => 42.0.5
pyOpenSSL: 23.2.0 => 24.1.0

bump sslyze to 6.0.0

---

frontend/src/app/ABTestWrapper.js

allows super admins to view changes between what is in preview and prod on frontend

remove super admins from always being on preview stream

---

scanners/web-scanner/requirements.txt

pydantic: 2.3.0 --> 2.4.0
pydantic_core: 2.6.3 --> 2.10.0

upgrade pydantic libraries in web-scanner

---

scanners/web-processor/web_processor/web_processor.py

- gives feedback to users on missing certificate
- evens out summary totals
closes #5283

set TLS statuses to fail when endpoint is present and certificate is missing

---

frontend/src/app/App.js
frontend/src/app/ContactUsPage.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

- remove "Report an Issue" link in footer
- Add GIthub link to "Contact Us" page
- Give guidance on where to contact us, including looking at the "Getting Started/FAQ" page first

Expand contact us page

---

azure-defender-easm/add-domain-to-easm/clients/kusto_client.py
azure-defender-easm/add-domain-to-easm/requirements.txt
azure-defender-easm/add-domain-to-easm/service.py
azure-defender-easm/add-easm-assets-to-tracker/requirements.txt
azure-defender-easm/import-easm-additional-findings/requirements.txt
azure-defender-easm/label-known-easm-assets/requirements.txt

required for kusto data helper

bugfix: add missing requirements to /azure-defender-easm services

---

azure-defender-easm/add-easm-assets-to-tracker/service.py
azure-defender-easm/import-easm-additional-findings/service.py
azure-defender-easm/label-known-easm-assets/clients/kusto_client.py
azure-defender-easm/label-known-easm-assets/service.py

modify queries to remove syntax and semantic errors in kusto queries when fetching unlabelled assets

Bugfix: fix KQL issues in EASM label service

---

frontend/src/app/App.js
frontend/src/app/NotificationBanner.js
frontend/src/dmarc/DmarcReportPage.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/user/UserPage.js

Make NotificationBanners hideable and change to using Alert component

---

api/src/user/mutations/__tests__/sign-in.test.js
api/src/user/mutations/authenticate.js
api/src/user/mutations/sign-in.js

- add `lastLogin` value to user doc upon successful login
- force email MFA if: 1. MFA is enabled; 2. `lastLogin` is >= 30 days ago
closes #5399

Feature: Force email MFA after 30 days

---

api/src/organization/objects/organization-summary.js

Refactored the code in organization-summary.js to include reusable components and cut down the length of the code

Refactored code in organization-summary to have reusable components

---

api/index.js
api/package-lock.json
api/package.json
api/src/server.js
frontend/package-lock.json
frontend/package.json
frontend/src/app/App.js
frontend/src/client.js

remove unused dependency and web socket subscription servers

Security: remove ws subscription dependencies

---

k8s/apps/bases/api/kustomization.yaml
k8s/apps/bases/api/network-policy.yaml
k8s/apps/bases/frontend/kustomization.yaml
k8s/apps/bases/frontend/network-policy.yaml

allow egress traffic from frontend pods to istiod and dns queries

Bugfix: fix frontend netpol egress

---

services/summaries/summaries.py

Will only use non-info DKIM statuses when calculating mail summaries

Bugfix: Conditionally use DKIM status for calculating mail summary

---

api/src/organization/loaders/load-all-organization-domain-statuses.js
api/src/organization/loaders/load-organization-domain-statuses.js
api/src/organization/objects/organization.js
api/src/organization/queries/__tests__/get-all-organization-domain-statuses.test.js
api/src/organization/queries/get-all-organization-domain-statuses.js

grabs domain IP addresses from webScans if available and adds them as semicolon-separated list
closes #5424

Feature: Add IPs to domains export CSV

---

frontend/src/components/MonthSelect.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/summaries/HistoricalSummariesGraph.js

Closes [#5481](https://github.com/canada-ca/tracker/issues/5481).

Clarify last thirty days _of data_

---

api/src/additional-findings/loaders/load-additional-findings-by-domain-id.js

Add limit to additional findings loader to improve performance

add 'LIMIT 1' to additionalFindings loader

---

frontend/src/graphql/queries.js
frontend/src/guidance/GuidancePage.js

Feature: Add favouriteDomain button to results page

---

api/Dockerfile
frontend/Dockerfile

Frontend: `scratch-node` isn't maintained anymore, switching to distroless
API: Specify node and alpine versions

Update api frontend images

---

api/src/domain/inputs/domain-filter.js
api/src/domain/loaders/load-domain-connections-by-organizations-id.js
api/src/enums/domain-order-field.js
api/src/organization/loaders/load-organization-domain-statuses.js
api/src/organization/objects/organization.js
frontend/src/admin/AdminDomains.js
frontend/src/domains/DomainListFilters.js
frontend/src/domains/DomainsPage.js
frontend/src/domains/FilterList.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/organizationDetails/OrganizationDomains.js

- Adds option to filter org domain connections by asset state value
- Adds asset state value to exported org domains CSV

Feature: Add asset state to domain filters/export

---

frontend/src/graphql/queries.js
frontend/src/guidance/AdditionalFindings.js
frontend/src/guidance/GuidancePage.js
frontend/src/guidance/__tests__/AdditionalFindings.test.js

Improve performance for loading guidance page since Additional findings are in B stream

Lazy load additional findings

---

api/src/enums/asset-state.js
frontend/src/admin/AdminDomainCard.js
frontend/src/admin/AdminDomains.js
frontend/src/components/InfoPanel.js
frontend/src/domains/DomainCard.js
frontend/src/domains/FilterList.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/organizationDetails/OrganizationDomains.js

- adds asset states to glossary on admin page and org page
- translate asset state filter tags

Feature: Add asset state definitions to org domain lists

---

api/src/domain/loaders/__tests__/load-domain-conn-org-id.test.js
api/src/domain/loaders/load-domain-connections-by-organizations-id.js
api/src/domain/mutations/__tests__/add-organizations-domains.test.js
api/src/domain/mutations/add-organizations-domains.js
api/src/domain/mutations/create-domain.js
api/src/domain/mutations/update-domain.js
api/src/domain/objects/domain.js
api/src/enums/domain-tag-label.js
api/src/organization/loaders/load-organization-domain-statuses.js
api/src/organization/objects/organization.js
azure-defender-easm/add-easm-assets-to-tracker/service.py
azure-defender-easm/label-known-easm-assets/service.py
frontend/src/admin/AdminDomainCard.js
frontend/src/admin/AdminDomainModal.js
frontend/src/admin/AdminDomains.js
frontend/src/admin/__tests__/AdminDomains.test.js
frontend/src/domains/DomainCard.js
frontend/src/fixtures/orgDomainListData.js
frontend/src/graphql/mutations.js
frontend/src/graphql/queries.js
frontend/src/organizationDetails/OrganizationDomains.js
frontend/src/summaries/__tests__/TieredSummaries.test.js
frontend/src/utilities/fieldRequirements.js
scanners/domain-discovery/domain_discovery.py
services/summaries/summaries.py
services/summaries/tests/test_summaries.py

- remove references to 'hidden' value in frontend and api
- remove function to ignore hidden domains in org summaries

Deprecate hidden domains

---

frontend/src/app/App.js
frontend/src/app/TopBanner.js
frontend/src/components/LoadingMessage.js
frontend/src/index.js

Issue due to race condition with refreshTokens.
This PR will delay loading the rest of the application until refreshTokens (and loginRequired) returns a result.
Fixes #5563
Loading state:

Fix occasional login state mismatch (sometimes showing org affiliation etc)

---

README.md

fix 404 link in README.md

---

api/src/additional-findings/loaders/index.js
api/src/additional-findings/loaders/load-top-25-reports.js
api/src/additional-findings/queries/__tests__/get-top-25-reports.test.js
api/src/additional-findings/queries/get-top-25-report.js
api/src/additional-findings/queries/index.js
api/src/initialize-loaders.js
api/src/query.js

add api query to fetch top 25 CSV report for verified orgs

Feature: Top 25 report

---

api/src/organization/loaders/load-all-organization-domain-statuses.js
api/src/organization/queries/__tests__/get-all-organization-domain-statuses.test.js
api/src/organization/queries/get-all-organization-domain-statuses.js

only adding org info if part of verified org

Add verified org to all domains export

---

frontend/src/admin/AdminDomains.js

add search tip to admin domains

---

api/src/domain/mutations/__tests__/update-domain.test.js
api/src/domain/mutations/create-domain.js
api/src/domain/mutations/update-domain.js
azure-defender-easm/add-domain-to-easm/clients/easm_client.py
azure-defender-easm/add-domain-to-easm/service.py

- call 'add-domain-to-easm' service when creating or updating domain and asset state changes
- if asset found in easm, update asset state to match tracker's

Feature: Update easm asset state

---

frontend/src/app/LocaleSwitcher.js
frontend/src/app/TopBanner.js
frontend/src/app/__tests__/App.test.js
frontend/src/landing/LandingPage.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/userOnboarding/__tests__/TourButton.test.js
frontend/src/userOnboarding/components/TourButton.js
frontend/src/userOnboarding/components/TourComponent.js

expose tour component on landing page

Display landing page tour

---

scanners/web-scanner/scan/endpoint_chain_scanner/endpoint_chain_scanner.py

Set user agent for web scanner

---

frontend/src/guidance/GuidancePage.js

Fix GuidancePage breaking on language switch

---

api/src/organization/objects/organization.js
frontend/src/admin/AdminPage.js
frontend/src/admin/OrganizationInformation.js
frontend/src/app/App.js
frontend/src/organizationDetails/OrganizationDetails.js

allows onboarding users to view potential point of contacts to become affiliated
closes #5372

Feature: Expose org affiliations when login not required

---

frontend/src/admin/AdminDomains.js
frontend/src/admin/AuditLogTable.js
frontend/src/admin/SuperAdminUserList.js
frontend/src/admin/UserList.js
frontend/src/admin/__tests__/AdminDomains.test.js
frontend/src/admin/__tests__/AdminPage.test.js
frontend/src/admin/__tests__/AuditLogTable.test.js
frontend/src/admin/__tests__/SuperAdminUserList.test.js
frontend/src/admin/__tests__/UserList.test.js
frontend/src/dmarc/DmarcByDomainPage.js
frontend/src/dmarc/__tests__/DmarcByDomainPage.test.js
frontend/src/domains/DomainsPage.js
frontend/src/domains/__tests__/DomainsPage.test.js
frontend/src/organizationDetails/OrganizationAffiliations.js
frontend/src/organizationDetails/OrganizationDomains.js
frontend/src/organizationDetails/__tests__/OrganizationAffiliations.test.js
frontend/src/organizationDetails/__tests__/OrganizationDomains.test.js
frontend/src/organizations/Organizations.js
frontend/src/organizations/__tests__/Organizations.test.js

Change default pagination counts to 50

---

frontend/src/guidance/EmailGuidance.js
frontend/src/guidance/WebGuidance.js

Add timezone to displayed "Last Scanned"

---

scanners/web-processor/web_processor/web_processor.py

…and ssl_status should pass
closes #5859

Bugfix: handle case in web_processor where curves are unused

---

frontend/src/landing/LandingPageSummaries.js
frontend/src/organizationDetails/OrganizationDetails.js
frontend/src/summaries/HistoricalSummariesGraph.js

- summary progress graphs
- aggregated negative findings
- landing page and org details page

Move new summary views to a stream

---

frontend/src/guidance/WebConnectionResults.js
frontend/src/guidance/WebGuidance.js
frontend/src/guidance/WebTLSResults.js

...to blue info status
closes #5868

Bugfix: Change red web status on non web domain guidance

---

frontend/src/theme/components/Button.js
frontend/src/userOnboarding/components/TourButton.js

Utilising our Tracker logo colours to make it *pop*

Make tour button stand out

---

services/update-selectors/main.py
services/update-selectors/tests/test_update_selectors.py
services/update-selectors/update_selectors.py

Only adds selectors seen within the last year.
Also removes current selectors which are missing either lastSeen or firstSeen

Only add newish selectors

---

scanners/dns-scanner/dns_scanner/dns_scanner.py

Bugfix: wildcard sibling logic to only return true if records match

---

api/src/user/mutations/close-account.js
api/src/user/objects/close-account-result.js
frontend/src/admin/SuperAdminUserList.js
frontend/src/graphql/mutations.js

- fixed incorrect destructured var name
- replaced awaiting query refetch with cache update
- fixed more then one modal being rendered

Bugfix: Successful error when closing other user accounts

---

frontend/src/domains/DomainListFilters.js
frontend/src/domains/DomainsPage.js
frontend/src/organizationDetails/OrganizationDomains.js

Bugfix: Domain filter form reset

---

frontend/src/admin/AdminDomains.js
frontend/src/admin/AuditLogTable.js
frontend/src/components/AffiliationFilterSwitch.js
frontend/src/dmarc/DmarcByDomainPage.js
frontend/src/domains/DomainListFilters.js
frontend/src/domains/DomainsPage.js
frontend/src/domains/FilterList.js
frontend/src/domains/__tests__/FilterList.test.js
frontend/src/organizationDetails/OrganizationDomains.js
frontend/src/organizations/Organizations.js

Make filters reset to first page

---

frontend/src/admin/AdminDomains.js
frontend/src/domains/DomainsPage.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/organizationDetails/OrganizationDomains.js

Expand wildcard glossary entries

---

frontend/src/admin/AdminDomains.js
frontend/src/admin/AdminPage.js
frontend/src/admin/AdminPanel.js
frontend/src/graphql/queries.js

Hide remove domain button on verified orgs for non-super-admins (unless NXDOMAIN)

---

scanners/web-scanner/requirements.txt

Update sslyze to 6.1.0 and cryptography to 44.0.0

---

scanners/dns-scanner/dns_scanner/email_scanners.py

Closes [#5902](https://github.com/canada-ca/tracker/issues/5902)

Fix handling of null MX records

---

scanners/web-processor/web_processor/web_processor.py
scanners/web-scanner/Dockerfile
scanners/web-scanner/scan/tls_scanner/tls_scanner.py

Effort for better blocking detection.

Check if scanner can connect to server after other scans completed

---

scanners/web-scanner/scan/endpoint_chain_scanner/endpoint_chain_scanner.py

Web scanner fix relative redirect

---

k8s/apps/bases/azure-defender-easm/label-known-easm-assets-cronjob/cronjob.yaml

increase frequency from every friday to every day to remove window that assets can be discovered and not labelled

run easm label job daily

---

scanners/dns-processor/dns_processor/dns_processor.py
scanners/dns-scanner/dns_scanner/email_scanners.py

Handle spf all mechanism for redirect. Store all spf data

---

scanners/dns-processor/service.py
scanners/web-processor/service.py

adds sets of negative web and email findings to domain docs in db. This will allow performative loading of domain connections to guidance tags

Feature: Add negative findings to domain docs

---

api/src/organization/objects/organization-summary.js

Only required login for loginRequired environments

Allow logged-out users to see negative findings

---

api/src/domain/mutations/add-organizations-domains.js
azure-defender-easm/add-easm-assets-to-tracker/service.py
scanners/domain-discovery/domain_discovery.py

bugfix: add assetState field for bulk domain adds
