web/Pipfile
web/Pipfile.lock

This commit gets us using pipenv for dependency management.
With this the application can now be tested with
```sh
pipenv install -d
pipenv run test
```
To run the application:
```sh
pipenv install
pipenv run start
```

Use pipenv

---

web/track/config.py

I felt a great disturbance in the Force. As if millions of "UserWarning:
Flask-Cache: CACHE_TYPE is set to null, caching is effectively
disabled." cried out in terror, and were suddenly silenced.

Silence cache warnings in tests

---

ci/Dockerfile
ci/README.md
web/cloudbuild.yaml

This commit adds a folder with build image used in the CI process, and
references it at its new home on gcr.io.

Use proper ci image

---

web/track/email_templates.py
web/track/views.py

Implemented Nick's function for sending password reset emails to the section of code that handles a 'too many failed attempts' error.
Added email_templates.py to store the hardcoded values for each notification template to clean code in views.py
Removed redundant variable assignment and called functions directly to generate template id
Performing a password reset also resets failed login attempts to 0
Added new template for this email in the notification template manager.

Email is now sent to reset password when account has been locked

---

web/tests/conftest.py

This function wasn't being called anywhere, and it's checking of the
vendor specific "CIRCLECI" environmental variable represents knowledge
of the deployment environment leaking into the app that is good to get
rid of.

Remove unused local_mongo_is_running function

---

api/app.py
api/models.py
api/queries.py
api/schemas/auth_token.py
api/schemas/user.py

Allows for new users to be created and stored in postgres via the graphql api.
Adds a mutation for generating an JWT Auth token.
TODO:  Move he Bcrypt instance into a global scope.

GraphQL create new users through mutation

---

.gitignore
api/Pipfile
api/schema_export.py

This script introspects on the GraphQL schema and writes the results
into schema.json. This description can later be used as the basis for
comparing schemas between frontend and api service to ensure that they
stay in sync.
When Graphql core 3 is more widely supported this script can be [made much cooler](https://graphql-core-next.readthedocs.io/en/latest/usage/introspection.html).

Add graphql schema export script

---

api/functions/error_messages.py
api/functions/update_user_password.py
api/queries.py
api/schemas/user.py
api/tests/test_user_schema.py

The Mutation requires:
- User's email
- New Password
- New Password (Confirmed)
This PR also adds tests for error checking. There are also tests for non existing users, but they are commented out for now until a DB mock is setup.
Thanks!

Add a GraphQL endpoint for updating user's password

---

frontend/webpack.config.js

It turns out that it's hard to debug stuff you can't connect to!
Listening on all ports enables connecting from mobile devices so you can
use the Chrome dev tools.

Get webpack dev server to listen on 0.0.0.0

---

api/Pipfile.lock
api/cloudbuild.yaml
web/cloudbuild.yaml

Using sync to install packages exactly as specified in Pipfile.lock.

Use pipenv sync to only install from lock

---

web/Dockerfile

Between pipenv's spinner and output buffering stdout is hard with
python.

Fix Python stdout

---

api/cloudbuild.yaml

The postgres alpine image is 154MB while the standard image is 394MB. 😳

Use postgres:alpine in CI

---

api/Pipfile
api/Pipfile.lock
api/functions/error_messages.py
api/functions/validate_two_factor.py
api/models.py
api/queries.py
api/schemas/user.py
api/tests/test_user_schema.py

This PR adds two endpoints to the API.
1.  **generate_otp_url** which generates a URL to be parsed into a QR Code
2. **authenticate_two_factor** which allows a user's 2FA status to be updated if a valid OTP is presented along with their email address.
Note: This PR will require that everyone have a new environment variable called:
**BASE32_SECRET** which must be a 16 character base32 secret key in accordance to the pyotp documentation.

Implement 2FA-Validation with pyotp

---

api/cloudbuild.yaml

No longer using the cloud instance DB, so removed references in the cloud build template

Removed Azure from API cloud build template

---

platform/bases/tracker-api-deployment.yaml

Run `pipenv run db-seed` after schema creation succeeds.

Add initContainer to run db-seed

---

frontend/.eslintrc
frontend/index.js
frontend/package-lock.json
frontend/package.json
frontend/src/Server.js
frontend/src/__tests__/Server.test.js

To allow for deep linking and k8s liveness/readiness checks and stuff it's time
to move from the very simple `serve` library to something more flexible.

Replace serve with express

---

platform/bases/tracker-api-deployment.yaml

It turns out this was a bad idea since (obviously) this is not an idempotent
operation.

Remove db-seed initcontainer

---

api/app.py
api/cloudbuild.yaml
api/functions/db_seeding/admin_affiliations.py
api/functions/db_seeding/admins.py
api/functions/db_seeding/ciphers.py
api/functions/db_seeding/classification.py
api/functions/db_seeding/dkim_scans.py
api/functions/db_seeding/dmarc_scans.py
api/functions/db_seeding/domains.py
api/functions/db_seeding/groups.py
api/functions/db_seeding/guidance.py
api/functions/db_seeding/http_scans.py
api/functions/db_seeding/organizations.py
api/functions/db_seeding/scans.py
api/functions/db_seeding/sectors.py
api/functions/db_seeding/spf_scans.py
api/functions/db_seeding/ssl_scans.py
api/functions/db_seeding/user_affiliations.py
api/functions/db_seeding/users.py
api/manage.py
api/tests/test_domains_resolver.py
api/tests/test_email_address_scalar.py
api/tests/test_groups_resolver.py
api/tests/test_organizations_resolver.py
api/tests/test_sector_resolver.py
api/tests/test_url_scalar.py
api/tests/test_user_roles.py
api/tests/test_user_schema.py
api/tests/test_validators.py

- Reformatted test, and db_seeding files to conform with new editor config
- Created new system for enum generation without interference with testing
- Brought back the pytest fixtures (I know you missed them) for all tests to insert data, and remove it after the test is done
- Cleaned up enum seeding information to only contain information for the creation of enums
- Removed seed step for the cloudbuild

Fixing All The Tests

---

platform/bases/tracker-api-deployment.yaml
platform/bases/tracker-frontend-deployment.yaml

These resource requests help the kubernetes scheduler make decisions about what
to run when resources are tight/changing.

Add resource requests to deployments

---

platform/overlays/flux/README.md

The deployment instructions here were missing the fact that the gpg key needed
to be in the same namespace as flux and as a result the deployment would fail
because the secret couldn't be mounted.
It's fixed now!

Update deployment instructions in the flux readme

---

platform/overlays/flux/kustomization.yaml
platform/overlays/flux/memcached-dep.yaml
platform/overlays/flux/patch.yaml

Seeing slow deploys and kubelet killing the flux and memcached pods. This
commit bumps the memory and cpu allocated for flux (which does the deployments)
and memcached (where flux keeps it's state) in hopes we will see less of this
sort of thing.

Bumping resource requests/limits for flux

---

frontend/README.md
frontend/docker-compose.yaml
frontend/envoy-dev.yaml
frontend/schema.faker.graphql
frontend/src/DomainsPage.js
frontend/src/__tests__/App.test.js
frontend/src/index.js
frontend/webpack.config.js

This commit add docker-compose to create a nice frontend dev workflow.
Docker compose starts the frontend service with a bind-mount for the current
directory along with a mocked graphql api.
To knit those together Envoy is used as a lightweight proxy allowing the two
services to appear as the same domain.
Envoy was chosen here because it's lightweight and fast and also because it's
already included in the project by virtue of being used by Istio.

Add docker-compose based frontend dev workflow

---

platform/overlays/flux/api-namespace.yaml
platform/overlays/flux/frontend-namespace.yaml
platform/overlays/flux/kustomization.yaml
platform/overlays/flux/patch.yaml
platform/overlays/gke/.flux.yaml
platform/overlays/gke/kustomization.yaml

This commit removes the secret handling from the flux setup.
Since the sops binary is now baked into the flux image, originally I was thinking it would be good to check in secrets and then let flux handle the decrytion with a generator in the .flux.yaml command. Unfortunately this wasn't a well documented part of flux and never really worked properly. There were lots of messages like this in the logs:
```sh
Error: verifying changes: failed to verify changes: the image for container "api" in resource "api:deployment/tracker-api" should be "gcr.io/track-compliance/api:master-48db84c", but is "gcr.io/track-compliance/api:update-frontend-deps-862b39e"
```
This sort of thing was mysterious and blocked deployments from happening, making our continuous deployment not very continuous.
What's …

Don't use sops

---

api/docker-compose.yaml

This commit adds a docker-compose file to help make a nice dev workflow.
In the api folder, you can now run the command `docker-compose up` and have the
api and database started and listening on port 5000.
The file is also set up so that it runs the migrations before starting the api.
If you want to run everything in the background, you can "detach" like this:
```sh
docker-compose up -d
```
Stopping everything is basically what you might expect:
```sh
docker-compose down
```

Add docker-compose for api development

---

api/tests/test_user_sign_in.py

Add unit tests for user sign in

---

api/app.py
api/backend/__init__.py
api/backend/cost_check.py
api/backend/cost_map.py
api/backend/depth_check.py
api/backend/security_check.py
api/resolvers/sectors.py
api/tests/test_auth_wrapper.py
api/tests/test_cost_check.py
api/tests/test_depth_check.py
api/tests/test_domains_resolver.py
api/tests/test_groups_resolver.py
api/tests/test_notification_emails.py
api/tests/test_organizations_resolver.py
api/tests/test_scans_resolver.py
api/tests/test_sector_resolver.py
api/tests/test_user_roles.py
api/tests/test_user_schema.py
api/tests/test_user_sign_in.py

This PR will bring in a new security check that will not all users to submit a query of depth 10 or greater. The depth can be changed at any time inside the `api/backend/depth_check.py` file.
- Added backend directory to contain any backends we may choose to implement
- Added depth check backend to help mitigate cycle attacks
- Tests created to test depth check functionality

Initial depth check setup, testing has also been completed

---

platform/bases/envoy-filter.yaml

This commit adds to the Envoy filters to ensure that the x-frame-options header
is added to all responses leaving the ingress gateway.
```sh
$ curl -I http://192.168.39.242:32566/
HTTP/1.1 200 OK
x-powered-by: Express
accept-ranges: bytes
cache-control: public, max-age=0
last-modified: Wed, 19 Feb 2020 21:58:59 GMT
etag: W/"14c-1705f7614b8"
content-type: text/html; charset=UTF-8
content-length: 332
date: Fri, 13 Mar 2020 16:59:51 GMT
x-envoy-upstream-service-time: 2
server: istio-envoy
x-frame-options: deny
```

Add x-frame-options header to responses

---

platform/bases/envoy-filter.yaml
platform/overlays/gke/envoy-filter.yaml
platform/overlays/gke/kustomization.yaml

This commit moves the security related headers to the production config, and adds the header needed to support HSTS.

Set frame options & HSTS headers in production

---

platform/overlays/gke/certificate.yaml

This commit switches the certificate to use RSA 4096 instead of ecdsa because
it turn out that Letsencrypt won't issue certs of that kind, saying "ECDSA
curve P-521 not allowed".
😒

Use RSA 4096

---

frontend/schema.faker.graphql
frontend/src/App.js
frontend/src/SignInPage.js
frontend/src/__tests__/SignInPage.test.js
frontend/src/index.js

* Successful sign in redirects to `/`
* `/` path always refresh component
* ~~`localStorage()`~~ Apollo Client: `client.writeData()` used to hold jwt token
* tests added for these features.

Sign in component redirects after success

---

frontend/src/TwoFactorPage.js

This commit adds an initial value for the otpCode which resolves the dreaded "A
component is changing an uncontrolled input of type undefined to be controlled"
warning.

Supply initial value for otpCode

---

api/cloudbuild.yaml
frontend/cloudbuild.yaml

This reverts commit a97f5162ed625c842adb37b4557d0553581b8037.
The problem with the previous commit was that in replacing the `:` with a slash changed the meaning from "create an image called `gcr.io/$PROJECT_ID/frontend` tagged with `$BRANCH_NAME-$SHORT_SHA`" to "create an image called `gcr.io/$PROJECT_ID/frontend/$BRANCH_NAME-$SHORT_SHA`".
Flux relies on tags to do deployments so this commit switches things back.

Revert "Update cloudbuild.yaml (#213)"

---

frontend/Dockerfile
frontend/index.js

Prompted by constant "gyp ERR! find Python" errors cluttering the stdout of our
builds, this commit reworks our production image build.
First, we've moved to use a [multi-stage
build](https://www.ardanlabs.com/blog/2020/02/docker-images-part1-reducing-image-size.html).
This allows us to install the python that node-gyp is whining about without
unneeded software ending up in our production images.
Second, the image is now
["Distroless"](https://www.youtube.com/watch?v=lviLZFciDv4). The idea here is
to significantly reduce the attack surface by removing everything from the
image except for the runtime and the code. No shell, no nothing.
One of the side effects of this move is that there is no longer a way for us to
exec into our images. For debugging containers we will need to use …

Use distroless for production image

---

frontend/Dockerfile

This commit ends our short lived experiment with Distroless images.
Based on an ancient version of Debian (of all things), the most current node
image has 28 vulns going back over 4 years mostly centering on glibc and
openssl.
Noping right out of there.

💀 distroless

---

api/Dockerfile
ci/Dockerfile

That's right folks we're going to Ubuntu 20.04, yes it is still in development but with an expected release this April 2020 we should be on track to be able to use the release version when we move into production.
- Moved API docker image over to Ubuntu 20.04
- Moved CI docker image back to Alpine

Moving On Up To Ubuntu 20.04

---

frontend/src/App.js
frontend/src/QRcodePage.js
frontend/src/SignInPage.js
frontend/src/UserPage.js
frontend/src/UserState.js
frontend/src/__tests__/App.test.js
frontend/src/__tests__/DmarcReportPage.test.js
frontend/src/__tests__/QRcodePage.test.js
frontend/src/__tests__/SignInPage.test.js
frontend/src/__tests__/TwoFactorNotificationBar.test.js
frontend/src/__tests__/TwoFactorPage.test.js
frontend/src/__tests__/UserState.test.js
frontend/src/client.js
frontend/src/graphql/queries.js
frontend/src/index.js

This commit adds a UserStateProvider function which makes available a
currentUser object and some helper functions to mutate that state.
The provider is passed an initial state object with the appropriate default
values for the currentUser object:
```javascript
<UserStateProvider initialState={{ userName: null, jwt: null, tfa: null }}>
<App/>
</UserStateProvider>
```
That inital state is retrieved via the `useUserState()` hook along with helper
functions to operate on that state.
```javascript
const { currentUser, isLoggedIn, login, logout } = useUserState()
```
The `isLoggedIn` function will return true if there are truthy values in the
state (ie, we have non-null values for userName, jwt or tfa).
The `login` function expects the details for a user to be passed in, and will
set the …

Manage user state with custom context and hook

---

frontend/schema.faker.graphql
frontend/src/UserCard.js
frontend/src/UserList.js
frontend/src/UserPage.js
frontend/src/__tests__/UserCard.test.js
frontend/src/__tests__/UserList.test.js
frontend/src/__tests__/UserPage.test.js
frontend/src/graphql/mutations.js
frontend/src/graphql/queries.js
platform/overlays/gke/kustomization.yaml

* adds custom gql type for userPage
* adds custom gql type (and dependents) for userList
* Updates files and tests to use these new types.

Create custom GraphQL types for UserPage and UserList

---

platform/overlays/flux/patch.yaml

This commit removes the registry-include-image option from flux because it
doesn't recognize tags, only image names which doesn't solve the problem of
keeping flux away from our feature branch images.

Remove registry-include/exclude options

---

frontend/package.json
frontend/src/UserState.js
frontend/src/__tests__/UserState.test.js

The UserState component ended up knowing to much about what constituted "logged
in" and "logged out" states (truthy and false values in the currentUser
object). This commit removes this implicit knowledge by using fast-deep-equal
to determine if the current state differs from the initial state.
This simpler approach will be far more robust and generic.

Make UserState dumber

---

platform/bases/envoy-filter.yaml
platform/bases/kustomization.yaml
platform/bases/publicgateway.yaml
platform/bases/tracker-api-virtual-service.yaml
platform/bases/tracker-frontend-virtual-service.yaml
platform/overlays/gke/kustomization.yaml
platform/overlays/gke/publicgateway.yaml
platform/overlays/gke/tracker-api-virtual-service.yaml
platform/overlays/gke/tracker-frontend-virtual-service.yaml
platform/overlays/minikube/kustomization.yaml

This commit fixes gzip compression settings, which were not being applied in
prod. This updates the envoyfilter config and moves publicgateway up into the
base folder to ensure that gzip is consistently applied regardless of the
overlay being used. The gke overlay now just patches publicgateway rather than
trying to add it ensuring better consistency between environments.

Fix gzip compression

---

platform/overlays/gke/tracker-api-deployment.yaml
platform/overlays/gke/tracker-frontend-deployment.yaml

For a long time now flux has been confused by the existence of images for our
feature branches. This shouldn't be the case since the only tags it should
consider start with 'master'. This commit switches from the existing glob based
matching to regex in hopes that flux will be better behaved.

Switch from glob to regex for flux image matching

---

platform/overlays/flux/patch.yaml

Flux polls for new copies of all the images in the cluster. This commit adds an
option to narrow its focus.

Get flux to ignore more images

---

frontend/src/DmarcReportPage.js
frontend/src/DomainsPage.js

Authorization: Bearer <token> turns out to be an Oauth2 thing which we are not
currently using.

Remove "Bearer" from Authorization header

---

platform/overlays/gke/kustomization.yaml

This commit removes a reference to a deleted file that is tripping up kustomize
and blocking manifest generation.

Remove reference to deleted file

---

api/Pipfile
api/tests/test_auth_functions.py
api/tests/test_auth_wrapper.py
api/tests/test_cost_check.py
api/tests/test_db_migrate.py
api/tests/test_depth_check.py
api/tests/test_domains_mutations.py
api/tests/test_domains_resolver_access_control.py
api/tests/test_domains_resolver_values.py
api/tests/test_email_address_scalar.py
api/tests/test_notification_emails.py
api/tests/test_organization_acronym_scalar.py
api/tests/test_organization_mutations.py
api/tests/test_organization_resolver_access_control.py
api/tests/test_organization_resolver_values.py
api/tests/test_that_migrations_have_a_single_revision_head.py
api/tests/test_url_scalar.py
api/tests/test_user_access_control.py
api/tests/test_user_mutations.py
api/tests/test_user_roles.py
api/tests/test_user_sign_in.py
api/tests/test_user_values.py
api/tests/test_users.py
api/tests/test_users_access_control.py
api/tests/test_users_values.py

This commit modifies the "test" script to run pytest as a module which adds the
current directory to the module search path. This allows the removal of a bunch
of path munging code sprinkled throughout the tests.

Run pytest as a module

---

frontend/package.json

Since the tests are written such that the test output is essentially
documentation, it's useful to print this out.

Set Jest test output to verbose

---

api/migrations/env.py

Commit 5c2775df935de changed our models so the inherit the declarative base
class instead of flask-sqlalchemy's db.Model. Unfortunately this breaks
migrations because they are no longer able to introspect on the models
properly.
Alembic assumes it should delete tables for models it can no longer
see, so running `pipenv run db-migrate` resulted in lots of stuff like
`Detected removed table 'dkim_scans'` and a generated migration that drops the
apparently orphaned tables.
This commit gives alembic a proper metadata object so it can see our models again.

Fix model introspection to get migrations working

---

api/db.py

This function is aimed at making testing nicer. The idea is that Sqlalchemy's
scoped_session function [returns a Session factory](https://stackoverflow.com/q/39750373)
with which we are minting a new session for each of our tests.
This function is then used in the tests like so:
```python
from db import DB
save, cleanup, session = DB()
```
The idea here getting better isolation between our tests via separate sessions,
but it also provides some abstraction between us and the db object. Mostly
tests will just need `save(thing)` and `cleanup()` but the `session` object is
there as an escape hatch when those aren't sufficient.
Adding abstraction means we can make changes behind the scenes to change those
objects are instantiated and configured (beginning transactions and stuff like
that) …

Export DB() factory function from db.py

---

api/models/Users.py
api/tests/test_users.py

This change adds a roles method to the users model. The idea here to give a
single authoritative definition for the notion of a "role", and a way to access
those given a user object.

Add roles method to users model

---

api/tests/test_auth_wrapper.py

This commit reworks the auth wrapper tests with an eye making them fail with
more helpful errors and be more understandable when read.
To improve the understandability, the specific preconditions needed for a given
test (what users and whatnot need to exist for this test to pass) have been
moved inside each test rather than having them created in a single global setup
function.
The acquisition of a token and the creation of an auth header has been folded into
functions to make it clearer what the object under test actually is.
Lastly, Users and other models no longer use specific ids, removing the
possibility of violating uniqueness constraints when tests are run.

Refactor auth wrapper tests

---

platform/bases/tracker-api-deployment.yaml
platform/bases/tracker-frontend-deployment.yaml

These values were weirdly low which explains why the performance of these
services was super slow even though the cluster had plenty of juice.

Increase cpu resource requests

---

api/cloudbuild.yaml
frontend/cloudbuild.yaml

This commit changes our cloudbuild scripts to only build docker images on the
master branch. Skipping builds should speed up our PRs a bit, this should also
save us space in our registry.
Also it turns out that Flux only truly understands semver tagged images and
falls back to sorting by time for everything else. This means our branch+SHA
based tagging scheme confuses it (by creating images for feature branches than
are newer than the image for master which it's told is the only one it should
deploy).
Flux's `--registry-include-image` limits scanning of images by name and not by
tag, so the choices seem to narrow down to either special image names for
master images or not building images for feature branches... so here we are.

Only build images on master

---

platform/overlays/seed/kustomization.yaml
platform/overlays/seed/tracker-namespace.yaml

This commit adds the tracker namespace that was referenced by one of the
secrets but wasn't actually included in our seed config.

Add missing tracker namespace to seed config

---

api/cloudbuild.yaml

This commit fixes the cloudbuild file so that it builds in the proper
directory, which has the rather desirable side effect of producing a working
image.

Fix cloudbuild for the api

---

platform/overlays/gke/README.md

This commit adds details to the gke readme covering how we are currently
creating our clusters. With this addition, in theory this repo now contains all
the docs needed to create a working deployment from scratch.

Update gke overlay with cluster creation info

---

platform/bases/tracker-api-deployment.yaml

This commit adds the env vars to the api deployment needed for it to work.
These were added previously but only for the initContainer and not the api
itself.

Add missing SA_* env vars to tracker-api

---

api/functions/sign_in_user.py
api/functions/validate_two_factor.py
api/tests/test_cost_check.py
api/tests/test_domains_mutations.py
api/tests/test_domains_resolver_access_control.py
api/tests/test_organization_resolver_values.py
api/tests/test_user_access_control.py
api/tests/test_user_mutations.py
api/tests/test_user_roles.py
api/tests/test_user_sign_in.py
api/tests/test_user_values.py
api/tests/test_users_access_control.py
api/tests/test_users_values.py

This commit continues the work of refactoring the API tests. The goal is to
keep increasing the isolation of our tests, simplifying them and getting them
all written in the same pytest style.

Refactor API tests

---

frontend/src/DomainsPage.js
frontend/src/__tests__/DomainsPage.test.js

This commit adds some error handling for case where domains query succeeds but
doesn't return any domains.

Gracefully handle the "no domains" case

---

platform/overlays/flux/patch.yaml

This commit adds our scanner images to flux's exclude list to prevent it from
scanning them for updates. Once we automate their build process we can loop
back and adjust this.

Exclude scanner images... for now.

---

platform/overlays/flux/patch.yaml

This commit bumps the CPU resource back to where it was before after realising
that 200 millicores wasn't enough for it to clone the repo and sync stuff.
This change also adds kiali and cert-manager to the list of images that it
should not bother polling for changes.

Update flux settings: more cpu, more excludes

---

frontend/src/App.js
frontend/src/RouteIf.js
frontend/src/__tests__/RouteIf.test.js
frontend/src/__tests__/SignInPage.test.js

This commit adds a RouteIf component, and makes use of it to provide
"protected" routes on the frontend.
Given that it's the routing equivalent of an if statement the component adopts
some of that terminology:
```javascript
<RouteIf condition={true}
consequent="/path-if-true"
alternate="/path-if-false">
<p>child rendered if condition is true</p>
</RouteIf>
```
With that component in place, it's then put to use in the App component.
This modification revealed that the App component was making an unwanted
appearance in the SignInPage tests, so that is removed here too.

Require an authenticated user for certain routes

---

api/json_web_token.py

TIL: Python only evaluates default arguments once when the function is being
defined, not once per invocation.
Because of the way this function was written, the jwt "issued at" and expiry
times were being calculated once when the server started.  With token
expiration set for 1 hour, this means we had a 1 hour window before all tokens
would be expired by default.
🤦

Fix timestamp generation

---

platform/overlays/gke/certificate.yaml

This commit switches our cert to pulse.alpha.canada.ca

Update certificate to use the new dns name

---

api/enums/languages.py
api/schemas/sign_up/create_user.py
api/schemas/sign_up/sign_up.py
api/tests/test_language_enums.py
api/tests/test_sign_up.py

Quick little PR that includes a required field on the `signUp` mutations that uses a new language enum.
- `preferred_lang` field added to `signUp` mutation
- New `LanguageEnums` has been introduced
- Tests for all changes, and implementations have been included

API signUp mutation modified with the users preferred language

---

platform/bases/README.md
platform/bases/istio.yaml
platform/overlays/gke/README.md
platform/overlays/gke/istio.yaml
platform/overlays/seed/kustomization.yaml

This commit does what it says on the tin, and moves us to Istio 1.6.  As part
of this commit, I've also edited the istio config to remove some extra ports
that istio was listening on. The documentation has been updated to reflect the
extra bit of tomfoolery which we can look to automate or eliminate shortly.

Update to Istio 1.6

---

api/Pipfile
api/Pipfile.lock
api/functions/external_graphql_api_request.py
api/queries.py
api/schemas/yearly_dmarc_report_summary/__init__.py
api/schemas/yearly_dmarc_report_summary/category_totals.py
api/schemas/yearly_dmarc_report_summary/resolver.py
api/schemas/yearly_dmarc_report_summary/send_request.py
api/schemas/yearly_dmarc_report_summary/yearly_dmarc_report_summary.py
api/tests/test_get_yearly_dmarc_report_summaries.py
api/tests/testdata/get_yearly_dmarc_report_summaries/__init__.py
api/tests/testdata/get_yearly_dmarc_report_summaries/get_yearly_dmarc_report_summaries_data.py
api/tests/testdata/get_yearly_dmarc_report_summaries/get_yearly_dmarc_report_summaries_expected_data.py

Initial implementation of bringing in the `dmarc-report-api`
- Ability to query `dmarc-report-api`
- `getYearlyDmarcReportSummaries` query has been implemented
- All tests for relevant implementations included
- Black ran on all modified files

Integrating the dmarc-report-api

---

platform/overlays/gke/letsencrypt-issuer.yaml
platform/overlays/seed/README.md
platform/overlays/seed/kustomization.yaml

After some deliberation over the security implications of the dns-01 challenge
vs the http-01 challenge this commit switches us over to the http-01.
The thinking here is that both challenges happen over an unencrypted channel,
and both challenges mitigate MITM attacks by looking at the requester from
multiple network vantage points (http://tiny.cc/vqlypz).
The big tradeoff here is that wildcard certs are only possible via dns-01, at
the cost of a little extra setup... the managing of a DNS hosted zone and a
service account with which to manipulate those settings to complete the
challenge. We weren't/aren't using wildcard certs, and are happy to accept an
operational simplification anywhere that doesn't impact our security posture.
Please see the IETF docs for further discussion of the …

Get certs via http-01 challenge

---

platform/overlays/gke/http-01-challenge-destination-rule.yaml
platform/overlays/gke/kustomization.yaml

This commit adds a destination rule disabling mTLS between cert-manager and
envoy for the purposes of dealing with an http-01 challenge.
Without this the envoy logs were filling up with
```
error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
```

Add destination rule for HTTP-01 challenge

---

frontend/src/PasswordConfirmation.js
frontend/src/TwoFactorPage.js

This commit removes some calls to setTimeout that were generating the warning:
```
Warning: Can't perform a React state update on an unmounted component. This is
a no-op, but it indicates a memory leak in your application. To fix, cancel all
subscriptions and asynchronous tasks in a useEffect cleanup function.
```

Remove setTimeout calls

---

platform/overlays/gke/flux-patch.yaml

This commit fixes the ordering of the patch directives and adds the current tag
to the frontend container.

Clean up flux-patch

---

platform/overlays/gke/flux-patch.yaml

This commit adds the flux deployment automation annotations to the patch.

Ensure patches retain automation annotations

---

api/schemas/authenticate/authenticate.py

This commit changes username back to EmailAddress type from string to align it
with the other instances of username in the api and the existing expectations
of the frontend queries.

Use EmailAddress type for authenticate mutation

---

api/models/Users.py
api/tests/test_user_page_query.py

This commit puts organization creation back in the User model init to ensure
that users will be able to have a usable account after signup.

Create a default user during user creation

---

frontend/cloudbuild.yaml
frontend/package-lock.json
frontend/package.json

This commit drops the use of the CI image for the frontend. Basically that
image was needed because webpack-dev-server uses chokidar 2, which uses an old
version of fsevents which tries to compile a fs watcher for OSX even on Linux
using python 2 which isn't included in node:alpine.
This commit forces the use of modern version of chokidar and drops the image
entirely.

Don't use ci image for frontend builds

---

platform/overlays/flux/patch.yaml

This commit adds to the exclude list for flux, further narrowing it's view and
cleaning up a bunch of noise from the logs.

Exclude more images from flux

---

frontend/package-lock.json
frontend/package.json
frontend/schema.faker.graphql
frontend/src/LandingPage.js
frontend/src/Navigation.js
frontend/src/SummaryCard.js
frontend/src/SummaryGroup.js
frontend/src/SummaryTable.js
frontend/src/__tests__/DomainsPage.test.js
frontend/src/__tests__/SummaryCard.test.js
frontend/src/__tests__/SummaryGroup.test.js
frontend/src/__tests__/SummaryTable.test.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/makeSummaryTableData.js
frontend/src/theme/canada.js

- Add summary donuts to landing page and fill them with mocked data
- Create domain summary table component

Add Summary Charts to Landing Page

---

frontend/src/SummaryGroup.js

This commit removes the translation of data before it's passed into the
SummaryCard component. This fixes the issue where these translated values where
used as keys to access colors in our theme, which had no equivalent when
switched to French.

Don't translate data

---

api/queries.py
api/schemas/is_user_admin/__init__.py
api/schemas/is_user_admin/is_user_admin.py
api/schemas/is_user_admin/resolver.py
api/tests/test_is_admin_query.py

Quick little query to test that a user has a role of `admin` or higher. This is sort of broken at the moment because any new user gets a sandbox org, but it will be useful in the future where the user will not have that sandbox org until they verify their account.

Is the User an Admin

---

api/queries.py
api/resolvers/organizations.py
api/schemas/organizations.py
api/tests/test_organization_resolver_access_control.py
api/tests/test_organization_resolver_values.py

This is a breaking change to the API, since it drops Query.organization and
replaces it with Query.findOrganizationDetailBySlug which returns an
OrganizationDetail type.
The thinking here is to return a specific type that is appropriate for the
public API, meaning that it doesn't expose details that depend on a logged in
user like the base Organization type does. It's also a step away from the very
broad generic names we were using in the early days to narrow specific ones
that take up less "naming real estate" leaving us more room to evolve our API
additively.

Add Query.findOrganizationDetailBySlug to API

---

platform/overlays/gke/tracker-frontend-deployment.yaml

This commit bumps the replica count and sets the rolling update parameters to
enable a zero downtime deployment for the frontend. This leverages the already
implemented liveness/readiness checks allowing kubernetes to spin up new
containers and seamlessly redirect traffic to the new containers only when they
are ready to handle it.
This is a key capability allows for constant updates without the risk of
services disruption/downtime for users.

Enable zero downtime deploys for the frontend

---

platform/overlays/gke/knative/config/config.yaml

This updates the scanner config.yaml to use DB_HOST for result processing

Utilize DB_HOST key from scanners secret

---

api/queries.py
api/schemas/request_scan/__init__.py
api/schemas/request_scan/fire_scan.py
api/schemas/request_scan/request_scan.py
api/tests/test_request_scan.py
frontend/schema.faker.graphql

This PR is a short one, moving the `requestScan` into its own directory, and moving the directly related functionality out of the functions directory and into `schemas/request_scan`, and finalizing the functionality of mutation. As well tests have been finally written testing the mutations functionality.

Refactoring requestScan mutation

---

frontend/schema.faker.graphql
frontend/src/Organization.js
frontend/src/Organizations.js
frontend/src/__tests__/Organizations.test.js
frontend/src/graphql/queries.js

This commit makes use of the new domainCount field that is now available to
display the number of domains associated with an organization.

Add domainCount to orgs page

---

api/schemas/authenticate/authenticate.py
api/tests/test_authenticate.py
api/tests/test_user_update_password.py
frontend/schema.faker.graphql
frontend/src/graphql/mutations.js

This converts the standard arguments over to an input object for the Authenticate mutation, faker, and frontend stuff should also be correct as tests are still passing.

Use Input Object for Authenticate

---

api/schemas/dmarc_report_detail_tables/__init__.py
api/schemas/dmarc_report_detail_tables/resolver.py
api/tests/testdata/dmarc_report_detail_table/dmarc_report_table_query.py
frontend/schema.faker.graphql
frontend/src/graphql/queries.js

This PR updates the demo, and regular dmarcReportDetailsTable query to use an Input Object.

Use Input Object for Dmarc Report Detail Tables

---

services/scanners/dns/dns_scanner.py

Erroneous dkim selector scans should be {"missing": True}

DKIM selector scan error handling

---

frontend/src/Server.js

This commit adds a configuration option to have express properly pay attention
to the x-forwarded-for header that is needed to deal with IPs correctly behind
proxies like Envoy.

Set Express to trust the x-forwarded-for header

---

api/schemas/remove_domain/remove_domain.py
api/schemas/remove_organization/remove_organization.py
api/tests/test_removeDomain_mutation.py
api/tests/test_removeOrganization_mutation.py
frontend/schema.faker.graphql

Quick PR with the goal of switching `removeDomain` and `removeOrganization` mutations to use an input object rather than base arugments.

Converting Remove Mutations to use Input Objects

---

platform/overlays/gke/knative/config/autoscan.yaml

This change relocates the 'autoscan' kubernetes cron job from the barren wasteland of the default namespace.

Addition of namespace specifier within autoscan.yaml

---

platform/overlays/gke/pgo/api-service.yaml

This reverts commit 464ae83c67a5c7b57a5e040d16ef2a28e22d1c23.

Revert "Rename pgo service port to be Istio friendly (#659)"

---

frontend/schema.faker.graphql
frontend/src/App.js
frontend/src/LandingPage.js
frontend/src/Organization.js
frontend/src/OrganizationDetails.js
frontend/src/Organizations.js
frontend/src/SummaryTable.js
frontend/src/__tests__/OrganizationDetails.test.js
frontend/src/__tests__/SummaryTable.test.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/makeSummaryTableData.js

Add summary tables with mocked data to organisation details pages

Add Summary Tables to Organisation Details

---

platform/overlays/gke/tracker-api-deployment.yaml
platform/overlays/gke/tracker-frontend-deployment.yaml

This commit removes the annotations from the api/frontend deployments which
leaves flux to just deploy whatever is the latest image based on the
timestamps. This wasn't done previously because we were building images for
feature branches as well as the master branch which forced us to be specific.
Since we've stopped building feature branch images we can drop these
annotations.

Let flux deploy based on timestamps

---

frontend/envoy-dev.yaml

This commit updates the envoy config we're using in our frontend dev setup to
silence a warning that was showing up in the output of docker compose.

Update envoy dev config

---

frontend/src/SummaryCard.js

This commit reworks the SummaryCard component to use react-minimal-pie-chart.
This library is significantly smaller than recharts, and also is much more
amenable to testing... the switch eliminated dozens of "The width(0) and
height(0) of chart should be greater than 0" warnings that have been cluttering
our test output.

Simplify SummaryCard

---

api/queries.py
api/schemas/invite_user_to_org/__init__.py
api/schemas/invite_user_to_org/invite_user_to_org.py
api/schemas/invite_user_to_org/send_added_to_org_email.py
api/schemas/invite_user_to_org/send_invite_to_service_email.py
api/schemas/sign_up/create_user.py
api/schemas/sign_up/sign_up.py
api/tests/test_invite_user_to_org.py
api/tests/test_send_invite_to_org_notification_email.py
api/tests/test_send_invite_to_service_email.py
api/tests/test_sign_up.py
frontend/schema.faker.graphql
frontend/src/graphql/mutations.js

A new query that allows admins of organizations to invite users to the organization. If the user the admin wants to invite does not have an account however, they will receive an email containing a link to create an account with a token in the url, that upon user creation will automatically assign that new user account to that organization.

People can finally be added to organizations

---

api/schemas/request_scan/request_scan.py
api/schemas/shared_structures/domain/__init__.py
api/tests/test_request_scan.py

Quick fix was causing error log and incorrect return to user to occur, also a possible fix for multiple domains being returned.

Fix request scan return check

---

api/schemas/user_list/user_list_item.py
api/tests/test_user_list_query.py
frontend/schema.faker.graphql
frontend/src/graphql/queries.js

Switched userList query field admin to role, and instead of returning a boolean value it now returns a RoleEnums value depending on the given users role in that organization.

More details in the UserList

---

frontend/src/AdminDomains.js
frontend/src/AdminPanel.js
frontend/src/UserList.js
frontend/src/__tests__/AdminDomains.test.js
frontend/src/__tests__/AdminPanel.test.js
frontend/src/__tests__/UserList.test.js
frontend/src/graphql/queries.js

As promised, this commit combines the two queries in the AdminPanel component
into a single query. There are also minor modifications to the UserList and
AdminDomains components since they are now passed a specific slice of a larger
object rather than an entire graphql response.

Combine AdminPanel queries

---

api/schemas/update_user_profile/update_user_profile.py
api/tests/test_update_user_profile_mutation.py
frontend/schema.faker.graphql

Add a `currentPassword` input field to the `updateUserProfile` mutation, to add another level of checks when the user updates their password.

Checking the user is who they say they are

---

frontend/package-lock.json
frontend/package.json
frontend/src/Organizations.js
frontend/src/SummaryGroup.js
frontend/src/__tests__/Organizations.pagination.next.test.js
frontend/src/__tests__/Organizations.pagination.previous.test.js
frontend/src/__tests__/Organizations.test.js
frontend/src/client.js
frontend/src/graphql/queries.js
frontend/src/index.js

This commit uses the new relay pagination helper to add next/previous buttons
to the organizations list.

Add pagination with Apollo

---

frontend/src/SignInPage.js

This commit simply adds some padding to the SignInPage so that the imputs
aren't slammed up against the sides of the screen on mobile devices.

Add padding to SignInPage

---

frontend/src/UserList.js

This commit adds keys to the Box components being mapped over in the UserList.
This fixes the `Each child in a list should have a unique "key" prop.` warning
that was showing up in the tests.  Also removed a console.log statement which
was also showing up in the test output.

Fix key warning in UserList

---

frontend/src/Organizations.js
frontend/src/__tests__/Organizations.test.js

Since the order of arguments matters, this commit switches all the
Organizations test data to use the order that reads well: first/after
last/before.

Make test data more consistent

---

platform/overlays/gke/knative/config/autoscan.yaml
services/auto-scan/Dockerfile
services/auto-scan/autoscan.py
services/auto-scan/docker-entrypoint.sh
services/auto-scan/requirements.txt
services/auto-scan/tests/test_autoscan.py

These changes provide the ability to "schedule" scans to be performed on the database's entire collection of domains. This can be performed daily, weekly, or however the corresponding CronJob manifest is configured (default value is specified to be once every 8 hours, to support development efforts through frequent scanning)

Amendments to auto-scan service and CronJob manifest

---

frontend/src/__tests__/indexes.test.js
frontend/src/__tests__/usePaginatedCollection.test.js
frontend/src/indexes.js
frontend/src/usePaginatedCollection.js

This commit spins the logic for calculating pagination indexes into it's own
tested function, adds a test reproducing what we are seeing in prod and
changing usePaginatedCollection to use the indexes function to get the test
passing. After all that... it should work this time™.

Properly calculate indexes for pagination

---

frontend/src/AdminDomains.js
frontend/src/CreateUserPage.js
frontend/src/DmarcReportTable.js
frontend/src/EditableUserDisplayName.js
frontend/src/EditableUserEmail.js
frontend/src/EditableUserPassword.js
frontend/src/theme/canada.js

This commit swaps out blue.900 that is used throughout the app for the name
"primary", and adds a definition for that in the theme.
The same treatment was given to yellow.250 which is now called accent.

Switch to named colors throughout the application

---

api/functions/external_graphql_api_request.py
api/schemas/dmarc_report_summary_table/__init__.py
api/schemas/dmarc_report_summary_table/resolver.py
api/tests/test_dmarc_report_summary_table.py

Hopefully this will fix the api issues, if not however we should be getting much better insight into what is going wrong.

Please fix the dmarc-report-api issues

---

api/schemas/dmarc_report_summary_table/resolver.py

Just a work around until the re-writes come along and make everything shiny.

Fix last 30 days issue

---

api/schemas/dmarc_report_summary_table/resolver.py
api/schemas/sign_up/sign_up.py
api/tests/test_sign_up.py

This change to the sign-up mutation will only allow users to sign up if they were sent an invite email. We will use the initial SA account to send out the initial invites and go from there.

Make sign up invite only

---

platform/overlays/gke/knative/config/autoscan.yaml

As it turns out, `concurrencyPolicy: Forbid` logically conflicts with the default successful job history limit of 3.
Forbidding concurrent jobs while previously successful 'autoscan' pods are kept around due to default settings prevents the scheduling of consecutive jobs.
These changes override the default behaviour and result in the forced deletion of pods after scheduled scans have been completed.
More info:
https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#jobs-history-limits

Autoscan Scheduling Fix

---

services/scanners/dns/dns_scanner.py
services/scanners/dns/tests/test_dns_scanner.py

For the sake of eliminating redundancy when inserting selector values, all selectors will have '._domainkey' appended to them within the scanning process itself.

No longer require '._domainkey' for domains.selectors

---

api-js/src/__tests__/check-domain-permission.test.js
api-js/src/__tests__/find-domain-by-slug.test.js
api-js/src/auth/check-domain-permission.js
api-js/src/auth/index.js
api-js/src/queries/domains/find-domain-by-slug.js

These changes introduce the findDomainBySlug query, as well as the checkDomainPermission auth function to ensure that users belong to an org that has a claim for the specified domain.
Tests have been introduced for the query and auth function, with coverage at 100%.

Addition of findDomainBySlug query

---

api-js/src/queries/domains/find-domain-by-slug.js

As the title suggests, these changes specify the field used for 'userKey' within the find-domain-by-slug query.

Specification of 'userID' field

---

services/scanners/dns/dns_scanner.py
services/scanners/dns/requirements.txt

These changes introduce a follow-up check to ensure that external DMARC report recipients found within the record's 'RUA' tag are indeed configured to receive/accept reports. Such configuration is a strong indicator of an authorized external reporting arrangement between the original organizational domain and the recipient.
More info can be found [here](https://tools.ietf.org/html/rfc7489#section-7.1)

External Reporting Check

---

platform/overlays/gke/knative/config/autoscan.yaml

Contrary to prior understanding, a pod concurrency policy of "Forbid" results in blocking behaviour. Even after a scheduled scan has been performed, it will be unable to switch status to "Completed" to avoid the generation of concurrent 'autoscan' pods. 
This has been updated to reflect a policy of 'Replace', which enables the desired behaviour.

Forbid -> Replace

---

platform/overlays/gke/knative/config/queues.yaml

These changes set the minimum and maximum number of queue replicas to 4. This disables scaling to zero, which results in loss of enqueued domains. A static number of replicas addresses this issue, and also ensures constant availability.

Disable scale-to-zero for scan and result queues

---

scripts/insert_csv.py
services/auto-scan/autoscan.py
services/db-migration/migrations/versions/dc6adc4d8944_update_guidance_table.py
services/db-migration/models/__init__.py
services/scanners/results/result_processor.py

These changes update the `guidance` table to reflect the `tag_id` column referenced within the wiki, as well as updating the `ref_links` column to support an array of external reference links.
Miscellaneous model updates have been implemented across several scripts to ensure the use of a consistent SQLA model.

Guidance table update

---

api/enums/period.py
api/tests/test_period_enums.py

Quick fix to abbreviation that was causing an issue to be thrown

Issue with sept not being an abbreavation

---

api-js/package.json
api-js/src/scalars/domain.js

Quick refactor to domain scalar to use a domain parser rather than regex, allowing in the future to limit based on various aspects of their domains.

Refactoring domain scalar

---

frontend/src/DmarcByDomainPage.js
frontend/src/DmarcReportSummaryGraph.js
frontend/src/DmarcReportTable.js

Small PR to format the following things:
- DMARC by domain table data is right-aligned
- DMARC by domain table Total Messages data is formatted with commas for english, spaces for french
- DMARC by domain table Percentage data is formatted with "%" appended
- Removed unusable options from "Show n" results for DMARC by domain table
- Bar graph tool-tip data is formatted with commas for english, spaces for french
- Go To Page selection for tables located with Page display

Added formatting for tables and bar chart

---

platform/overlays/gke/knative/config/autoscan.yaml

Changes effectively pause automated scanning until December.

Pause scanning

---

api-js/jest.config.js

Slight change to the jest config in the JS API increasing the timeout time to deal with the db not responding quickly enough and occasionally timing out.

Jest config changes in JS API

---

frontend/package-lock.json
frontend/package.json
frontend/webpack.config.js

This commit finally bumps html-webpack-plugin. We've tried to upgrade this
before but is mysteriously stopped working... it turns out that it was our
public path setting that was the problem, so it's been removed.

Update to html-webpack-plugin 4.5.0

---

platform/overlays/gke/certificate.yaml

This commit switches the certificate over to use the new tracker.alpha.canada.ca. It's also setting the Issue to be LE staging.

Update certificate to use the new tracker url

---

frontend/schema.faker.graphql
frontend/src/App.js
frontend/src/DomainCard.js
frontend/src/DomainsPage.js
frontend/src/Doughnut.js
frontend/src/OrganizationCard.js
frontend/src/OrganizationDetails.js
frontend/src/Organizations.js
frontend/src/SummaryCard.js
frontend/src/SummaryGroup.js
frontend/src/WelcomeMessage.js
frontend/src/__tests__/DomainsPage.test.js
frontend/src/__tests__/OrganizationDetails.test.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/theme/canada.js

Bringing back the domains page with:
- universal search tab
- one-off scan tab
- Both these features are yet to be fully implemented, and will be with the introduction of the JS API
UI tweaks:
- Summary cards are now the same length
- domains and organization names now truncate if they are too long, tooltips allow the whole name to be seen
- Theme colours updated to match the official tracker colour scheme

New Domains Page

---

frontend/src/DmarcReportPage.js
frontend/src/DmarcReportTable.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

This PR allows all other tables on the DMARC report page to be displayed when other tables are empty. A message is displayed when no data is available for a given table.

Fe handle empty tables

---

api-js/package.json
api-js/src/__tests__/find-my-domains.test.js
api-js/src/__tests__/load-domain-conn-org-id.test.js
api-js/src/__tests__/load-domain-connections-by-user-id.test.js
api-js/src/loaders/domains/load-domain-connections-by-organizations-id.js
api-js/src/loaders/domains/load-domain-connections-by-user-id.js
api-js/src/locale/en/messages.js
api-js/src/locale/en/messages.po
api-js/src/locale/fr/messages.js
api-js/src/locale/fr/messages.po

This introduces a new way to write the connection loaders in a way that the pageInfo fields are properly handled, querying the db only once, and setting up new rules for the pagination limit args

Fixing domain connection loaders

---

platform/bases/knative/config/config.yaml
platform/overlays/seed/kustomization.yaml
platform/overlays/seed/scanners-namespace.yaml
platform/overlays/seed/tracker-namespace.yaml

Moving scanners namespace creation into the seed overlay so that the scanners secret can be created there.

Move scanners namespace creation to seed overlay

---

platform/overlays/flux/patch.yaml

This commit silences a super noisy message in the flux logs:
ts=2020-10-27T17:45:49.04520074Z caller=repocachemanager.go:223 component=warmer canonical_name=index.docker.io/grafana/promtail auth={map[]} warn="manifest for tag master-fc6c5c0 missing in repository grafana/promtail" impact="flux will fail to auto-release workloads with matching images, ask the repository administrator to fix the inconsistency"

Tell flux to ignore grafana images

---

platform/.flux.yaml
platform/bases/kustomization.yaml
platform/overlays/gke/.flux.yaml
platform/overlays/gke/kustomization.yaml
platform/overlays/minikube/kustomization.yaml

This commit moved kustomize's image tagging up into bases so that it flows down
to all the overlays. This change also requires a change to the flux config to
tell it where and how to update the tags.

Centralize tags in bases.

---

platform/overlays/flux/patch.yaml

This commit changes flux's git path to match the new location of the .flux.yaml
file. This gets it properly generating manifests again.

Change flux git path to the platform folder

---

frontend/LICENCE
frontend/package.json

This commit adds repository and license fields to the package.json file in
order to resolve warnings that those fields were missing.
This commit also updates the license referred to by the license field, to
properly attribute the copyright to the GoC.

Add repo/license to silence warnings

---

frontend/src/DomainsPage.js
frontend/src/ScanDomain.js
frontend/src/__tests__/ScanDomain.test.js

This commit extracts the ScanDomain component from the DomainsPage. The
extraction allowed for improving the test, eliminating an "act" warning and
simplifying the DomainsPage. Functionally the same.

Pull Domain scan tab into it's own component

---

services/domain-ownership/cloudbuild.yaml

This directory attribute was missing from the image building tasks meaning that it would fail to build images on master...

Add missing directory to DO service cloudbuild

---

api-js/src/types/base/index.js

This commit fixes two unused args that were making the linter angry.

Fix jsapi linting

---

api-js/src/__tests__/load-organization-by-key.test.js
api-js/src/__tests__/load-organization-by-slug.test.js
api-js/src/__tests__/load-organization-connections-by-domain-id.test.js
api-js/src/__tests__/load-organization-connections-by-user-id.test.js
api-js/src/__tests__/load-verified-org-conn-by-domain-id.test.js
api-js/src/__tests__/load-verified-org-conn.test.js
api-js/src/__tests__/load-verified-organization-by-key.test.js
api-js/src/__tests__/load-verified-organization-by-slug.test.js
api-js/src/loaders/organizations/load-organization-by-key.js
api-js/src/loaders/organizations/load-organization-by-slug.js
api-js/src/loaders/organizations/load-organization-connections-by-domain-id.js
api-js/src/loaders/organizations/load-organization-connections-by-user-id.js
api-js/src/loaders/verified-organizations/load-verified-organization-by-key.js
api-js/src/loaders/verified-organizations/load-verified-organization-by-slug.js
api-js/src/loaders/verified-organizations/load-verified-organization-connections-by-domain-id.js
api-js/src/loaders/verified-organizations/load-verified-organizations-connections.js
api-js/src/locale/en/messages.po
api-js/src/locale/fr/messages.po
api-js/src/types/base/index.js
api-js/src/types/base/organization-summary.js
api-js/src/types/base/verified-objects.js

Added in new summaries fields to `Organizations` and `VerifiedOrganizations`, the structure follows that of the web and mail summaries
```graphql
query {
findVerifiedOrganizations (first: 5) {
edges {
node {
id
summaries {
web {
total
categories {
name
count
percentage
}
}
mail {
total
categories {
name
count
percentage
}
}
}
}
}
}
}
```

Organization Summary Fields!

---

api-js/src/auth/__tests__/check-user-is-admin-for-user.test.js
api-js/src/auth/check-user-is-admin-for-user.js
api-js/src/auth/index.js
api-js/src/locale/en/messages.js
api-js/src/locale/en/messages.po
api-js/src/locale/fr/messages.js
api-js/src/locale/fr/messages.po
api-js/src/queries/user/__tests__/find-user-by-username.test.js
api-js/src/queries/user/find-user-by-username.js
api-js/src/server.js

Slight issue found in the `findUserByUserName` Query
- any admin could query any user -> admins can only query users if they share an organization

Find User By UserName Query Refactor

---

app/generate-secrets/README.md
app/generate-secrets/kustomization.yaml

This overlay generates secrets from `.env` files. It's useful for seeding a new
cluster.

Add generate-secrets overlay

---

api-js/src/types/base/__tests__/domain.test.js
api-js/src/types/base/dmarc-report/__tests__/period.test.js
api-js/src/types/base/dmarc-report/period.js
api-js/src/types/base/index.js

Update to `periodType` to have a domain field added to it.

Domain Scalar added to Period Type

---

api-js/src/server.js

Simple PR forcing introspection and the graphql playground to be enabled for the api.

Bringing Introspection and Playground back to the API

---

api-js/src/loaders/dmarc-report/__tests__/generate-gql-query.test.js
api-js/src/loaders/dmarc-report/generate-gql-query.js
api-js/src/types/base/__tests__/dkim.test.js
api-js/src/types/base/__tests__/dmarc.test.js
api-js/src/types/base/__tests__/domain.test.js
api-js/src/types/base/__tests__/https.test.js
api-js/src/types/base/__tests__/spf.test.js
api-js/src/types/base/__tests__/ssl.test.js
api-js/src/types/base/index.js

Quick fix to the generate gql query function to always add in the category totals fields if either category totals or category percentage is called

Fixes to GQL Query Generation

---

app/bases/scanners-namespace.yaml

Disable istio injection within scanner namespace to avoid conflict with knative's `queue-proxy` sidecar.

Disable istio injection in scanner namespace

---

app/bases/tracker-api-deployment.yaml

Add CIPHER_KEY to Tracker API deployment

---

services/scanners/dns/requirements.txt
services/scanners/https/requirements.txt
services/scanners/results/requirements.txt
services/scanners/ssl/requirements.txt

Uvicorn seems to complain about the lack of `uvloop` within the newly updated scanners, giving the following previously unseen error:
[2020-12-03 00:19:11 +0000] [7] [ERROR] Exception in worker process
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
worker.init_process()
File "/usr/local/lib/python3.8/dist-packages/uvicorn/workers.py", line 61, in init_process
self.config.setup_event_loop()
File "/usr/local/lib/python3.8/dist-packages/uvicorn/config.py", line 339, in setup_event_loop
loop_setup = import_from_string(LOOP_SETUPS[self.loop])
File "/usr/local/lib/python3.8/dist-packages/uvicorn/importer.py", line 23, in import_from_string
raise exc from None
File …

Addition of uvloop requirement

---

api-js/src/loaders/dmarc-report/__tests__/generate-detail-table-fields.test.js
api-js/src/loaders/dmarc-report/__tests__/generate-gql-query.test.js
api-js/src/loaders/dmarc-report/generate-detail-table-fields.js
api-js/src/loaders/dmarc-report/generate-gql-query.js

Quick fix for the generation of gql queries for the dmarc report api, to supports variables.

Support GQL Vars for dynamic dmarc report api queries

---

api-js/src/loaders/domains/__tests__/load-domain-conn-org-id.test.js
api-js/src/loaders/domains/__tests__/load-domain-connections-by-user-id.test.js
api-js/src/loaders/domains/load-domain-connections-by-organizations-id.js
api-js/src/loaders/domains/load-domain-connections-by-user-id.js
api-js/src/queries/domains/find-my-domains.js
api-js/src/types/base.js

This is a quick band aid solution that adds a ownership arg to the `findMyDomains` query, and the `domains` field for the organization type.

Ownership Band aid

---

services/scanners/dns/dns_scanner.py
services/scanners/https/https_scanner.py
services/scanners/ssl/ssl_scanner.py

No longer sending results on scan timeout. If scan error occurs, send domain_key within payload.

Don't send results on timeout. On exception, send domain_key

---

api-js/src/__tests__/server.test.js
api-js/src/auth/__tests__/check-domain-permission.test.js
api-js/src/create-context.js
api-js/src/loaders/dmarc-report/__tests__/generate-detail-table-fields.test.js
api-js/src/loaders/dmarc-report/generate-gql-query.js
api-js/src/loaders/domains/__tests__/load-domain-conn-org-id.test.js
api-js/src/loaders/email-scan/__tests__/load-dkim-connections-by-domain-id.test.js
api-js/src/loaders/email-scan/__tests__/load-dmarc-connections-by-domain-id.test.js
api-js/src/loaders/organizations/__tests__/load-organization-connections-by-domain-id.test.js
api-js/src/loaders/verified-domains/__tests__/load-verified-domain-connections.test.js
api-js/src/loaders/web-scan/__tests__/load-https-connections-by-domain-id.test.js
api-js/src/mutations/user-affiliations/__tests__/remove-user-from-org.test.js
api-js/src/mutations/user-affiliations/remove-user-from-org.js
api-js/src/mutations/user/send-phone-code.js
api-js/src/mutations/user/update-user-profile.js
api-js/src/queries/domains/find-my-domains.js
api-js/src/types/__tests__/dkim-connection.test.js
api-js/src/types/__tests__/dkim-results-connection.test.js
api-js/src/types/__tests__/dkim-results.test.js
api-js/src/types/__tests__/dkim.test.js
api-js/src/types/__tests__/domain.test.js
api-js/src/types/__tests__/user-shared.test.js
api-js/src/types/__tests__/verified-domain-connection.test.js
api-js/src/types/__tests__/verified-organization-connection.test.js
api-js/src/types/base.js
api-js/src/types/dmarc-report/detail-tables/__tests__/dkim-failure-table.test.js

- Fix up naming convention of dkim results
- Run prettier on code base

Cleaning Up Dkim Results and Code Base

---

api-js/src/types/__tests__/domain.test.js
api-js/src/types/base.js
api-js/src/types/dmarc-report/__tests__/period.test.js
api-js/src/types/dmarc-report/period.js

This PR switches up how the month field in the period type works to support the return to the user of the `LAST30DAYS` enum.

Refactor Month Field

---

frontend/src/UserPage.js

This commit adds a key to an error boundary in the UserPage component to stop a
warning in the tests.

Add key to error boundary

---

frontend/src/AdminDomains.js
frontend/src/__tests__/AdminDomains.test.js

This commit fixes some minor issues with required props being null in
AdminDomains tests and resolves a warning that was showing up when the tests
ran.

Fix missing attributes warnings for AdminDomains

---

frontend/envoy-dev.yaml

This commit updates the Envoy config used for local development of the frontend
to use the v3.HttpConnectionManager API.
This resolves the error we were seeing with Docker Compose:
```
error initializing configuration '/etc/envoy-dev.yaml': The v2 xDS major
version is deprecated and disabled by default.
```

Update envoy dev config to v3

---

frontend/src/ScanDomain.js
frontend/src/__tests__/ScanDomain.test.js

As advertised. Width isn't valid but was being passed anyway and dropped.

Fix invalid prop warning in ScanDomain

---

frontend/src/DomainsPage.js
frontend/src/OrganizationDetails.js
frontend/src/Organizations.js

Test output included many key warnings:
```
Warning: Each child in a list should have a unique "key" prop
```
This commit resolves these warnings by adding the missing key prop to the
effected components.

Fix key warnings

---

api-js/src/queries/domains/__tests__/find-my-domains.test.js
api-js/src/queries/domains/find-my-domains.js
api-js/src/queries/organizations/__tests__/find-my-organizations.test.js
api-js/src/queries/organizations/find-my-organizations.js

This PR introduces a proper auth check for `findMyDomains` and `findMyOrganizations` queries.

Adding Proper Auth Checks to 'My' Queries

---

api-js/src/locale/en/messages.js
api-js/src/locale/en/messages.po
api-js/src/locale/fr/messages.js
api-js/src/locale/fr/messages.po
api-js/src/mutations/user/__tests__/authenticate.test.js
api-js/src/mutations/user/__tests__/reset-password.test.js
api-js/src/mutations/user/__tests__/sign-in.test.js
api-js/src/mutations/user/__tests__/sign-up.test.js
api-js/src/mutations/user/__tests__/update-user-password.test.js
api-js/src/mutations/user/sign-in.js
api-js/src/mutations/user/sign-up.js
api-js/src/types/__tests__/user-personal.test.js
api-js/src/types/base.js
api-js/src/types/index.js
api-js/src/types/sign-in.js

- Remove `tfaValidated` field from the personal user type and replace with `phoneValidated` and `emailValidated`
- Created Union for Sign In Mutation
- Automatically determines wither or not to use TFA method or provide single log in method
- All related tests updated with 100 coverage

Clarifying TFA in Auth Flow

---

frontend/src/App.js
frontend/src/DmarcByDomainPage.js
frontend/src/OrganizationCard.js
frontend/src/UserCard.js
frontend/src/UserPage.js
frontend/src/__tests__/DmarcByDomainPage.test.js
frontend/src/__tests__/UserCard.test.js
frontend/src/__tests__/UserList.test.js
frontend/src/__tests__/UserPage.test.js
frontend/src/fixtures/dmarcReportSummaryTable.js
frontend/src/graphql/queries.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

Removed organisations from UserPage and added in badges that show validations

FE User Page Fix

---

api-js/src/enums/index.js
api-js/src/enums/tfa-send-method.js
api-js/src/locale/en/messages.js
api-js/src/locale/en/messages.po
api-js/src/locale/fr/messages.js
api-js/src/locale/fr/messages.po
api-js/src/mutations/user/__tests__/sign-in.test.js
api-js/src/mutations/user/__tests__/sign-up.test.js
api-js/src/mutations/user/__tests__/update-user-password.test.js
api-js/src/mutations/user/__tests__/update-user-profile.test.js
api-js/src/mutations/user/__tests__/verify-account.test.js
api-js/src/mutations/user/__tests__/verify-phone-number.test.js
api-js/src/mutations/user/sign-in.js
api-js/src/mutations/user/sign-up.js
api-js/src/mutations/user/update-user-profile.js
api-js/src/mutations/user/verify-account.js
api-js/src/mutations/user/verify-phone-number.js
api-js/src/types/base.js
frontend/schema.faker.graphql

This PR introduces a new field in the users collection `tfaSendMethod` that allows the user to define how their TFA messages are sent during sign in.
- `updateUserProfile` updated to cover new `tfaSendMethod` field
- All related tests updated to cover new functionality
- `signIn` uses the `tfaSendMethod` field to determine how message is sent
- Tests updated to reflect changes
- New `TFASendMethodEnum` enum
- Values determine the current options for sending tfa messages
- Newly updated faker

Specifying how TFA Messages are Sent

---

frontend/src/DmarcReportPage.js
frontend/src/DmarcReportTable.js

- Decreases table font size
- Disables horizontal scrolling for report tables
- Disables line wrapping on categories Header From, Envelope From, Source IP Address

Add word breaking to dmarc report tables to avoid scrolling

---

frontend/src/CustomTooltipContent.js
frontend/src/DmarcReportSummaryGraph.js

Changes the values in the DMARC report graph tool tip to be right aligned. Introduces CustomTooltipContent.js for any further changes to the tool tip. 
Also adds percentages to tooltip.

Fe dmarc graph tooltip changes

---

frontend/src/DmarcReportPage.js

Re-arranges Total Messages, and Guidance columns in the DMARC report tables.
Right-aligns Total Messages and includes comma separation.

Fe dmarc report table changes

---

app/bases/knative/config/autoscan.yaml
app/bases/knative/config/config.yaml
app/bases/knative/config/queues.yaml
services/scanners/ssl/ssl_scanner.py

Default to string values for URLs. Fixed SSL edge case (whoops)

TIL Kubernetes secrets do not use URL-safe b64 encoding

---

api-js/index.js
api-js/src/server.js

This commit pulls startup messages out of the server constructor. This change
allows us to start removing some of the mocking of stdout that is going on in
the tests.
This change leaves behind an unused PORT variable (now called _PORT) , which is
retained because it's removal would change the signature of the Server function
causing widespread breakage.
Followup refactorings will be aimed at getting Server to accept an object (to
stop callers from coupling to argument order), and removing stdout mocking
where possible.

Move startup messages out of server.js

---

clients/python/tracker_client.py

Added ability to get monthly and yearly DMARC summaries for a specified domain. Also made output from main more informative.
Pardon the messy commit history - still getting used to VSCode git integration and fumbled the rebase onto master

Client get dmarc summary for domain

---

services/core/core.py
services/scanners/dns/dns_scanner.py
services/scanners/https/https_scanner.py
services/scanners/results/requirements.txt
services/scanners/results/result_processor.py
services/scanners/results/tests/test_data.py
services/scanners/results/tests/test_result_processor.py
services/scanners/results/utils.py
services/scanners/ssl/ssl_scanner.py

- Miscellaneous service updates to ensure reliable scanning and processing functionality
- Minor tag generation logic updates
- Addition of context-dependant tags and dmarc implementation phase determination

Service Update

---

api-js/cloudbuild.yaml

Jest runs test suites in paralell but the default build machine has only a
single CPU. This commit bumps us to a 8 CPU machine.

Bump up the power of the build machine

---

services/dmarc-report/index.js
services/dmarc-report/src/__tests__/calculate-percentages.test.js
services/dmarc-report/src/calculate-percentages.js
services/dmarc-report/src/database/__tests__/initialize-summaries.test.js
services/dmarc-report/src/database/__tests__/update-month-summary.test.js
services/dmarc-report/src/database/__tests__/update-thirty-days.test.js
services/dmarc-report/src/database/initialize-summaries.js
services/dmarc-report/src/database/update-month-summary.js
services/dmarc-report/src/database/update-thirty-days.js
services/dmarc-report/src/index.js

Introduce new function that will take in the `categoryTotals` of a given summary and calculate the respective percentages, and add them to the summary object for DB insertion.
- new `calculatePercentages` function
- 100% test coverage
- Update `initializeSummaries`, `updateMonthSummary`, and `updateThirtyDays` functions to use new `calculatePercentages` function
- 100% test coverage on updates

Pre-Calculate Category Percentages

---

services/dmarc-report/src/__tests__/calculate-percentages.test.js
services/dmarc-report/src/calculate-percentages.js
services/dmarc-report/src/database/__tests__/initialize-summaries.test.js
services/dmarc-report/src/database/__tests__/update-month-summary.test.js
services/dmarc-report/src/database/__tests__/update-thirty-days.test.js
services/dmarc-report/src/database/initialize-summaries.js
services/dmarc-report/src/database/update-month-summary.js
services/dmarc-report/src/database/update-thirty-days.js

Since we are already calculating the total for the percentages, we might as well store it as well, so we can order on it properly.

Calculate Total Messages

---

api-js/src/domain/inputs/__tests__/domain-order.test.js
api-js/src/domain/inputs/domain-order.js
api-js/src/domain/inputs/index.js
api-js/src/domain/loaders/__tests__/load-domain-conn-org-id.test.js
api-js/src/domain/loaders/__tests__/load-domain-connections-by-user-id.test.js
api-js/src/domain/loaders/load-domain-connections-by-organizations-id.js
api-js/src/domain/loaders/load-domain-connections-by-user-id.js
api-js/src/domain/queries/find-my-domains.js
api-js/src/enums/domain-order-field.js
api-js/src/enums/index.js
api-js/src/organization/objects/organization.js

Implements the ordering algorithm to the two domain connection loaders. The `orderBy` argument has been added to the `findMyDomains` query, and `domains` field arguments in the `organizations` object.

Ordering Domain Connections

---

frontend/schema.faker.graphql

Add ordering enums, and inputs for domain and org connections.
Also included a fix for the switch from `UserAffiliation` to `Affiliation`

Add Ordering to Domain and Org Connections

---

api-js/src/enums/https-order-field.js
api-js/src/enums/index.js
api-js/src/web-scan/inputs/__tests__/https-order.test.js
api-js/src/web-scan/inputs/https-order.js
api-js/src/web-scan/inputs/index.js
api-js/src/web-scan/loaders/__tests__/load-https-connections-by-domain-id.test.js
api-js/src/web-scan/loaders/load-https-connections-by-domain-id.js
api-js/src/web-scan/objects/__tests__/https.test.js
api-js/src/web-scan/objects/https.js
api-js/src/web-scan/objects/web-scan.js

Introduce ordering fields for HTTPS connections, as well as fixes for the `startDate` and `endDate` arguments.

Ordering HTTPS Connections

---

api-js/src/email-scan/inputs/__tests__/dkim-order.test.js
api-js/src/email-scan/inputs/__tests__/dkim-result-order.test.js
api-js/src/email-scan/inputs/dkim-order.js
api-js/src/email-scan/inputs/dkim-result-order.js
api-js/src/email-scan/inputs/index.js
api-js/src/email-scan/loaders/__tests__/load-dkim-connections-by-domain-id.test.js
api-js/src/email-scan/loaders/__tests__/load-dkim-results-connections-by-dkim-id.test.js
api-js/src/email-scan/loaders/load-dkim-connections-by-domain-id.js
api-js/src/email-scan/loaders/load-dkim-results-connections-by-dkim-id.js
api-js/src/email-scan/objects/__tests__/dkim.test.js
api-js/src/email-scan/objects/dkim.js
api-js/src/email-scan/objects/email-scan.js
api-js/src/enums/dkim-order-field.js
api-js/src/enums/dkim-result-order-field.js
api-js/src/enums/index.js

Ordering fields for `DKIM`:
- `TIMESTAMP`
---
Ordering fields for `DkimResults`:
- `SELECTOR`
- `RECORD`
- `KEY_LENGTH`

Ordering Dkim and Dkim Result Connections

---

api-js/src/web-scan/objects/__tests__/ssl.test.js
api-js/src/web-scan/objects/ssl.js

Introducing new fields on the ssl gql object:
- `acceptableCiphers`
- `acceptableCurves`
- `ccsInjectionVulnerable`
- `heartbleedVulnerable`
- `strongCiphers`
- `strongCurves`
- `supportsEcdhKeyExchange`
- `weakCiphers`
- `weakCurves`

New Fields on the SSL Object

---

platform/base/kustomization.yaml
platform/components/cert-manager/cert-manager.yaml
platform/components/cert-manager/kustomization.yaml

This commit bumps cert-manager from 1.0 to 1.2. In keeping with semver there
aren't any breaking changes and the recommended upgrade method is just kubectl
apply.
As a bonus this commit also moved cert manager into a kustomize component of
it's own.

Update to cert-manager 1.2

---

clients/python/README.md
clients/python/tests/test_formatting.py
clients/python/tests/test_get_dmarc.py
clients/python/tests/test_get_domains.py
clients/python/tests/test_get_results.py
clients/python/tests/test_get_summaries.py
clients/python/tests/test_gql.py
clients/python/tracker_client/client.py
clients/python/tracker_client/formatting.py
clients/python/tracker_client/queries.py

This PR includes:
- expanded and improved README
- conversion of existing docstrings to rst convention
- improvement of the contents of existing docstrings
- addition of new docstrings where they were missing
- extensive comments in queries.py
- addition of many examples in docstrings
- refactoring of client.py to split formatting into a different module (to make space for examples)

Client improve docs

---

api-js/src/auth/__tests__/check-super-admin.test.js
api-js/src/auth/check-super-admin.js
api-js/src/auth/index.js
api-js/src/create-context.js
api-js/src/dmarc-summaries/loaders/__tests__/load-dmarc-sum-connections-by-user-id.test.js
api-js/src/dmarc-summaries/loaders/load-dmarc-sum-connections-by-user-id.js
api-js/src/dmarc-summaries/queries/__tests__/find-my-dmarc-summaries.test.js
api-js/src/dmarc-summaries/queries/find-my-dmarc-summaries.js
api-js/src/domain/loaders/__tests__/load-domain-connections-by-user-id.test.js
api-js/src/domain/loaders/load-domain-connections-by-user-id.js
api-js/src/domain/queries/__tests__/find-my-domains.test.js
api-js/src/domain/queries/find-my-domains.js
api-js/src/organization/loaders/__tests__/load-organization-connections-by-user-id.test.js
api-js/src/organization/loaders/load-organization-connections-by-user-id.js
api-js/src/organization/queries/__tests__/find-my-organizations.test.js
api-js/src/organization/queries/find-my-organizations.js

- New `checkSuperAdmin` function
- Returns `true || false` depending if a user is a super admin or not
- 100% Test Coverage
- Queries now returning full data to super admins
- `findMyDmarcSummaries`
- `findMyDomains`
- `findMyOrganizations`
- Applied new function to the following loaders
- `orgLoaderConnectionsByUserId`
- `domainLoaderConnectionsByUserId`
- `dmarcSumLoaderConnectionsByUserId`

Fixing Super Admin Related Issues

---

api-js/src/auth/__tests__/check-domain-ownership.test.js
api-js/src/auth/check-domain-ownership.js
api-js/src/locale/en/messages.js
api-js/src/locale/en/messages.po
api-js/src/locale/fr/messages.js
api-js/src/locale/fr/messages.po

Add a super admin check to the `checkDomainOwnership` function to allow super admins to view any dmarc report summary data.

Allow Super Admins Domain Ownership

---

clients/python/tests/conftest.py
clients/python/tests/test_formatting.py
clients/python/tests/test_get_results.py
clients/python/tracker_client/client.py
clients/python/tracker_client/formatting.py
clients/python/tracker_client/queries.py

This PR:
- fixes indentation in several queries
- renames DOMAIN_RESULTS to ALL_RESULTS
- renames get_domain_results to get_all_results
- adds get_web_results and get_email_results + associated queries
- adds new tests and fixtures to match new functions

Client add separate web and email results functions

---

api-js/src/domain/objects/__tests__/domain.test.js
api-js/src/domain/objects/domain.js

Small change to convert the field type of `dmarcPhase` inside the `Domain` object to be a `string` instead of an `int`

dmarcPhase is now a String

---

services/scanners/results/result_processor.py

Various improvements to error handling.
- Check if domain "status" exists
- Check for "null" spf record
- Amend ssl5 tag check

Error handling improvements

---

api-js/src/email-scan/objects/__tests__/dkim-results.test.js
api-js/src/email-scan/objects/__tests__/dmarc.test.js
api-js/src/email-scan/objects/__tests__/spf.test.js
api-js/src/email-scan/objects/dkim-result.js
api-js/src/email-scan/objects/dmarc.js
api-js/src/email-scan/objects/spf.js
api-js/src/web-scan/objects/__tests__/https.test.js
api-js/src/web-scan/objects/__tests__/ssl.test.js
api-js/src/web-scan/objects/https.js
api-js/src/web-scan/objects/ssl.js

- Deprecating `guidanceTags` field on `DKIMResult`, `DMARC`, `SPF`, `HTTPS`, `SSL`
- Added `negativeGuidanceTags`, `neturalGuidanceTags`, and `positiveGuidanceTags` fields on:
- `DKIMResult`
- `DMARC`
- `SPF`
- `HTTPS`
- `SSL`

Negative, Neutral, Positive Guidance Tags

---

api-js/src/domain/mutations/__tests__/create-domain.test.js
api-js/src/domain/mutations/create-domain.js

Set the default values to `null`, example status in db
```json
{
"status": {
"dkim": null,
"dmarc": null,
"https": null,
"spf": null,
"ssl": null
}
}
```

Default Status Values on Domain Creation

---

api-js/src/user/mutations/__tests__/reset-password.test.js
api-js/src/user/mutations/reset-password.js

This makes a slight change to the `resetPassword` mutation that resets the failed login attempt counter.

Reset Failed Login Attempts when Password is Reset

---

api-js/src/user/mutations/update-user-profile.js

Quick fix to the `updateUserProfile` mutation where it would reset the users `tfaSendMethod` to `none` when the user attempted to update their profile.

Fix updateUserProfile

---

clients/python/setup.py
clients/python/tests/test_client.py
clients/python/tracker_client/client.py
clients/python/tracker_client/organization.py
clients/python/tracker_client/queries.py

This PR:
- tweaks query error handling to pass along as many query errors as occur rather than just the first
- adds path where error occurred to query error messages
- adds handling for query validation failure (`GraphQLError`)
- adds test for the above, updates query error test
- fixes some indentation issues in a query string

Client improve query error handling

---

api-js/src/user/mutations/__tests__/reset-password.test.js
api-js/src/user/mutations/reset-password.js
api-js/src/user/objects/__tests__/reset-password-error.test.js
api-js/src/user/objects/__tests__/reset-password-result.test.js
api-js/src/user/objects/index.js
api-js/src/user/objects/reset-password-error.js
api-js/src/user/objects/reset-password-result.js
api-js/src/user/unions/__tests__/reset-password-union.test.js
api-js/src/user/unions/index.js
api-js/src/user/unions/reset-password-union.js
frontend/schema.faker.graphql
frontend/src/ResetPasswordPage.js
frontend/src/graphql/mutations.js

Once again, creating a new union type to better handle non-server side errors, and return a meaningful response to the front end.
```graphql
mutation {
resetPassword(input: { password: "", confirmPassword: "", resetToken: "" }) {
result {
... on ResetPasswordError {
code
description
}
... on ResetPasswordResult {
status
}
}
}
}
```

Reset Password Union Introduction

---

api-js/src/user/mutations/__tests__/authenticate.test.js
api-js/src/user/mutations/authenticate.js
api-js/src/user/objects/__tests__/authenticate-error.test.js
api-js/src/user/objects/authenticate-error.js
api-js/src/user/objects/index.js
api-js/src/user/unions/__tests__/authenticate-union.test.js
api-js/src/user/unions/authenticate-union.js
api-js/src/user/unions/index.js
frontend/schema.faker.graphql
frontend/src/TwoFactorAuthenticatePage.js
frontend/src/__tests__/TwoFactorAuthenticatePage.test.js
frontend/src/graphql/mutations.js

This PR introduces the new `AuthenticateUnion` allowing for softer errors to be handling when executing the mutation.
Example Mutation:
```graphql
mutation {
authenticate(
input: { 
authenticationCode: <auth code (6 digit int)>, 
authenticateToken: "<token string from signIn>"
}
) {
result {
... on AuthResult {
authToken
user {
id
userName
displayName
preferredLang
phoneValidated
emailValidated
}
}
... on AuthenticateError {
code
description
}
}
}
}
```

Authenticate Union Introduction

---

clients/python/tests/test_core.py
clients/python/tracker_client/client.py
clients/python/tracker_client/core.py

This PR adds the ability to request French content from Tracker when creating a `Client` like so: `my_client = Client(language='fr')`. This sets the `accept-language` header included with all requests. The header is set to `en` by default.

Client add accept language header

---

services/scanners/results/utils.py

This change addresses an issue where an error is encountered if `fetch_schema_from_transport=True`
Not really sure why... but that's just the way it goes sometimes :/

Do not fetch schema with Python GraphQL

---

api-js/index.js
api-js/src/__tests__/server.test.js
api-js/src/server.js

Small PR refactoring the way the server factory function takes its args, from a list to an object.

Refactor Server Factory Function

---

clients/python/tests/conftest.py
clients/python/tests/test_client.py
clients/python/tests/test_organization.py
clients/python/tracker_client/client.py
clients/python/tracker_client/core.py
clients/python/tracker_client/organization.py
clients/python/tracker_client/queries.py

This PR updates `Client.get_domains`, `Client.get_organizations` and `Organization.get_domains` to use pagination to get as many items as exist, rather than just the first 100.

Client deal with pagination

---

clients/python/tracker_client/core.py
clients/python/tracker_client/queries.py

This PR updates `get_auth_token` to not swallow errors passed back in the SignInUnion and instead raise an exception with error details. Also changed `create_transport` to `_create_transport` as there is no reason to access it from outside core.py.

Client handle login error

---

clients/python/tests/conftest.py
clients/python/tests/test_core.py
clients/python/tracker_client/core.py
clients/python/tracker_client/queries.py

This PR adds support for TFA enabled users in the client. When TFA is enabled, users will be prompted to enter their TFA code at runtime when creating a `Client` object. Tests are included.

Client add TFA support.

---

clients/python/tests/conftest.py
clients/python/tests/test_domain.py
clients/python/tracker_client/domain.py
clients/python/tracker_client/formatting.py
clients/python/tracker_client/queries.py

This PR:
- Adds more fields to scan results queries (timestamps all around + more info on ssl and dkim).
- Adds ordering to scan results queries so most recent scans are first.
- Updates scan results formatting to handle multiple scans.
- Refactors scan results formatting.
- Adds `all_scans` arg to scan results methods. Defaults to `False`, if `True` will give all scans instead of just most recent.
- Adds code examples for scan results methods.
- Updates tests and fixtures as necessary.

Client update get results

---

api-js/src/locale/en/messages.js
api-js/src/locale/en/messages.po
api-js/src/locale/fr/messages.js
api-js/src/locale/fr/messages.po
api-js/src/organization/mutations/__tests__/update-organization.test.js
api-js/src/organization/mutations/update-organization.js

Adding a quick fix to check and see if the name being submitted for update is already in use, prevent errors from occurring when two organizations have the same name/slug, etc.

Add Name Check in updateOrganization Mutation

---

frontend/src/EditableUserPhoneNumber.js
frontend/src/fieldRequirements.js
frontend/src/locales/en.js
frontend/src/locales/en.po
frontend/src/locales/fr.js
frontend/src/locales/fr.po

This PR fixes issue #1685 by adding validation of phone numbers with regex on the front end according to the format specified in API docs.

Fe fix phone number validation

---

.github/dependabot.yml

Adds a `dependabot.yml` config file to tame dependabot slightly and switch to the newer version.
Configuration is based on the automatically generated file from PR #897 with the open PR limit changed to 10 (from 99) and updated to the repo's current structure. It may be worth tweaking options more, so please suggest changes or make them yourself if you think of anything. You can find information about possible options [here](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates).

Configure Dependabot V2

---

api-js/src/affiliation/mutations/__tests__/invite-user-to-org.test.js
api-js/src/affiliation/mutations/invite-user-to-org.js
api-js/src/affiliation/objects/__tests__/invite-user-to-org-error.test.js
api-js/src/affiliation/objects/__tests__/invite-user-to-org-result.test.js
api-js/src/affiliation/objects/index.js
api-js/src/affiliation/objects/invite-user-to-org-error.js
api-js/src/affiliation/objects/invite-user-to-org-result.js
api-js/src/affiliation/unions/__tests__/invite-user-to-org-union.test.js
api-js/src/affiliation/unions/index.js
api-js/src/affiliation/unions/invite-user-to-org-union.js
api-js/src/locale/en/messages.po
api-js/src/locale/fr/messages.po
frontend/schema.faker.graphql
frontend/src/UserList.js
frontend/src/graphql/mutations.js

Another union introduction, bringing in better handling of soft errors for the `inviteUserToOrg` mutation.
Example Mutation
```graphql
mutation {
inviteUserToOrg(
input: {
userName: ""
requestedRole: USER
orgId: ""
preferredLang: ENGLISH
}
) {
result {
... on InviteUserToOrgResult {
status
}
... on InviteUserToOrgError {
code
description
}
}
}
}
```

Invite User to Org Union Introduction

---

frontend/src/graphql/fragments.js

Apollo has a global cache of fragments and gets upset when fragments have names
that are not unique. This commit ensures they are.

Make fragment names unique

---

services/super-admin/package-lock.json
services/super-admin/package.json
services/super-admin/src/__tests__/create-super-admin-account.test.js
services/super-admin/src/__tests__/create-super-admin-affiliation.test.js
services/super-admin/src/__tests__/create-super-admin-org.test.js
services/super-admin/src/__tests__/remove-super-admin-affiliation.test.js
services/super-admin/src/database/create-super-admin-account.js
services/super-admin/src/database/create-super-admin-affiliation.js
services/super-admin/src/database/create-super-admin-org.js
services/super-admin/src/database/remove-super-admin-affiliation.js

Update Super Admin Service Dependencies

---

api-js/src/organization/loaders/load-organization-connections-by-domain-id.js
api-js/src/organization/loaders/load-organization-connections-by-user-id.js

Seems Like I had messed with the AQL var names and missed a few causing it not to order them correctly, this fixes those issues.

Fix for Ordering Orgs by Domain Count

---

api-js/src/domain/mutations/__tests__/update-domain.test.js
api-js/src/domain/mutations/update-domain.js
api-js/src/domain/unions/__tests__/update-domain-union.test.js
api-js/src/domain/unions/index.js
api-js/src/domain/unions/update-domain-union.js
api-js/src/locale/en/messages.po
api-js/src/locale/fr/messages.po
frontend/schema.faker.graphql
frontend/src/AdminDomains.js
frontend/src/graphql/mutations.js

This PR introduces a new union to be used with the `updateDomain` mutation.
Example GraphQL
```graphql
mutation {
updateDomain (input: { ... }) {
result {
... on Domain {
...
}
... on DomainError {
code
description
}
}
}
}
```

Update Domain Union Introduction

---

api-js/src/domain/mutations/__tests__/remove-domain.test.js
api-js/src/domain/mutations/remove-domain.js
api-js/src/domain/objects/__tests__/domain-result.test.js
api-js/src/domain/objects/domain-result.js
api-js/src/domain/objects/index.js
api-js/src/domain/unions/__tests__/remove-domain-union.test.js
api-js/src/domain/unions/index.js
api-js/src/domain/unions/remove-domain-union.js
frontend/schema.faker.graphql
frontend/src/AdminDomains.js
frontend/src/graphql/mutations.js

Another union introduction for handling of soft errors, this time for the `removeDomain` mutation.
```graphql
mutation {
removeDomain (input: { ... }) {
result {
... on DomainResult {
status
}
... on DomainError {
code
description
}
}
}
}
```

Introduce Remove Domain Union

---

frontend/schema.faker.graphql
frontend/src/ScanCard.js

adds orderby options for HTTPS, SSL, DKIM, DMARC, and SPF

Add OrderBy faker results to web and email categories

---

api-js/src/organization/mutations/__tests__/update-organization.test.js
api-js/src/organization/mutations/update-organization.js
api-js/src/organization/unions/__tests__/update-organization-union.test.js
api-js/src/organization/unions/index.js
api-js/src/organization/unions/update-organization-union.js
frontend/schema.faker.graphql

Another union introduction for handling of soft errors, this time for the `updateOrganization` mutation.
```graphql
mutation {
updateOrganization (input: { ... }) {
result {
... on Organization {
...
}
... on OrganizationError {
code
description
}
}
}
}
```

Introduce Update Organization Union

---

app/bases/knative/config/dmarc-report.yaml
services/dmarc-report/Dockerfile

This includes two fixes for the dmarc report service.
- Fix missing .env.example file in docker image
- Fix timezone issue (k8s time is GMT, so shifted it by 3 hours)

DMARC Report Service Fixes

---

api-js/src/locale/en/messages.po
api-js/src/locale/fr/messages.po
api-js/src/organization/mutations/__tests__/remove-organization.test.js
api-js/src/organization/mutations/remove-organization.js
api-js/src/organization/objects/__tests__/organization-result.test.js
api-js/src/organization/objects/index.js
api-js/src/organization/objects/organization-result.js
api-js/src/organization/unions/__tests__/remove-organization-union.test.js
api-js/src/organization/unions/index.js
api-js/src/organization/unions/remove-organization-union.js
frontend/schema.faker.graphql

This PR introduces a new union for the `removeOrganization` mutation, allowing for handling of soft errors.
```graphql
mutation {
removeOrganization (input: { ... }) {
result {
... on OrganizationResult {
status
}
... on OrganizationError {
code
description
}
}
}
}
```

Remove Organization Union Introduction

---

api-js/database-options.js
api-js/src/domain/loaders/__tests__/load-domain-conn-org-id.test.js
api-js/src/domain/loaders/__tests__/load-domain-connections-by-user-id.test.js
api-js/src/domain/loaders/load-domain-connections-by-organizations-id.js
api-js/src/domain/loaders/load-domain-connections-by-user-id.js
api-js/src/domain/queries/__tests__/find-my-domains.test.js
api-js/src/domain/queries/find-my-domains.js
api-js/src/organization/objects/organization.js

This PR introduces searching for domains, through domain connection args as an example:
```graphql
query {
findMyDomains (first: 5, search: "domain.com") {
edges {
node {
id
domain
}
}
totalCount
pageInfo {
hasNextPage
hasPreviousPage
}
}
}
```

Searching for Domains

---

api-js/package-lock.json
api-js/package.json

This commit pulls in a fix for arango-tools that addresses Trackers usage: no
options are passed in when creating collections. With an existing collection,
this triggered an update which ended up checking for properties of the
non-existent options object resulting in an error.

Update to arango-tools 0.4.1

---

clients/python/tests/test_client.py
clients/python/tracker_client/client.py
clients/python/tracker_client/queries.py

This PR adds support for searching domains in the form of an optional argument for `Client.get_domains`. For example, to get only sub-domains of the `gc.ca` second level domain, you could call the method like `my_client.get_domains(".gc.ca")`.

Add search arg to Client.get_domains

---

api-js/database-options.js
api-js/src/domain/objects/domain.js
api-js/src/organization/loaders/__tests__/load-organization-connections-by-domain-id.test.js
api-js/src/organization/loaders/__tests__/load-organization-connections-by-user-id.test.js
api-js/src/organization/loaders/load-organization-connections-by-domain-id.js
api-js/src/organization/loaders/load-organization-connections-by-user-id.js
api-js/src/organization/queries/find-my-organizations.js
frontend/schema.faker.graphql

This PR introduces a search argument for organization connections, example:
```graphql
query {
findMyOrganizations (first: 5, search: "org one") {
edges {
node {
name
acronym
}
}
totalCount
pageInfo {
startCursor
endCursor
hasNextPage
hasPreviousPage
}
}
}
```

Search for Organizations

---

api-js/src/organization/mutations/__tests__/verify-organization.test.js
api-js/src/organization/mutations/verify-organization.js
api-js/src/organization/unions/__tests__/verify-organization-union.test.js
api-js/src/organization/unions/index.js
api-js/src/organization/unions/verify-organization-union.js
frontend/schema.faker.graphql

This PR introduces a new union for use with the verify org mutation to handle soft errors.
```graphql
mutation {
verifyOrganization(input: { orgId: " ... " }) {
result {
... on OrganizationResult {
status
}
... on OrganizationError {
code
description
}
}
}
}
```

Verify Org Union Introduction

---

services/scanners/ssl/requirements.txt
services/scanners/ssl/ssl_scanner.py

This PR:
- Updates sslyze to 4.1.0 from 3.1.0 for bug fixes and stability improvements.
- Removes preferred cipher suite detection as results were not used anywhere. This capability was removed from sslyze for unreliability and the use of it was forcing us to stay on sslyze 3.1.0.
- Includes minor refactoring:
- Ran Black.
- The function `get_server_info` was conditionally returning `None` based on an exception being raised, and its return type was used for control-flow. Refactored so that the exception is caught by the caller instead and the function always returns the same type OR raises an exception.

Update sslyze and minor refactor of SSL scanner

---

app/bases/knative/config/dmarc-report.yaml

Shift run time by 30mins, we were currently running at the same time as the summaries were being computed

Shift DMARC Report API Run Time

---

api-js/src/user/mutations/__tests__/verify-account.test.js
api-js/src/user/mutations/verify-account.js
api-js/src/user/mutations/verify-phone-number.js

This pr disables the automatic switching of the `tfaSendMethod` when users verify their email, or phone number.

Don't Switch tfaSendMethod Automatically

---

api-js/src/organization/loaders/__tests__/load-organization-connections-by-domain-id.test.js
api-js/src/organization/loaders/__tests__/load-organization-connections-by-user-id.test.js
api-js/src/organization/loaders/load-organization-connections-by-domain-id.js
api-js/src/organization/loaders/load-organization-connections-by-user-id.js

This PR introduces support for when org related search strings are left empty, it also introduces support for french related searches.

Support Empty Org Search Strings

---

clients/python/tests/test_client.py
clients/python/tracker_client/client.py
clients/python/tracker_client/queries.py

This PR adds an optional argument to `Client.get_organizations` that allows use of the API's search capabilities. For example, `my_client.get_organizations("canada")` will return only Organizations that have "Canada" in their names.

Add optional search arg to Client.get_organizations

---

frontend/src/fixtures/dmarcGuidancePageData.js

This commit updates the test data to use a string instead of the old int value,
fixing an error visible in the tests where `status.toUpperCase()` was called on
the number `2`.

Update guidance page fixture

---

api-js/src/locale/en/messages.js
api-js/src/locale/en/messages.po
api-js/src/locale/fr/messages.js
api-js/src/locale/fr/messages.po
api-js/src/user/mutations/__tests__/remove-phone-number.test.js
api-js/src/user/mutations/index.js
api-js/src/user/mutations/remove-phone-number.js
api-js/src/user/objects/__tests__/remove-phone-number-error.test.js
api-js/src/user/objects/__tests__/remove-phone-number-result.test.js
api-js/src/user/objects/__tests__/user-personal.test.js
api-js/src/user/objects/index.js
api-js/src/user/objects/remove-phone-number-error.js
api-js/src/user/objects/remove-phone-number-result.js
api-js/src/user/objects/user-personal.js
api-js/src/user/unions/__tests__/remove-phone-number-union.test.js
api-js/src/user/unions/index.js
api-js/src/user/unions/remove-phone-number-union.js
frontend/schema.faker.graphql

This PR introduces a new PR that allows users to remove a phone number from their account.
Example GrahpQL:
```graphql
mutation {
removePhoneNumber(input: {}) {
result {
... on RemovePhoneNumberResult {
status
}
... on RemovePhoneNumberError {
code
description
}
}
}
}
```

Remove Phone Number Mutation

---

frontend/src/DomainsPage.js
frontend/src/__tests__/DomainsPage.test.js
frontend/src/client.js
frontend/src/graphql/queries.js

This PR enables the domain page search bar and uses it to set the new `search` domain connection argument. This allows domains to be searched by name.

Enable searching for domains on domain page

---

frontend/src/AdminPage.js
frontend/src/DomainsPage.js
frontend/src/Organizations.js
frontend/src/RelayPaginationControls.js
frontend/src/__tests__/DomainsPage.test.js
frontend/src/__tests__/Organizations.test.js
frontend/src/client.js
frontend/src/locales/en.js
frontend/src/locales/en.po
frontend/src/locales/fr.js
frontend/src/locales/fr.po
frontend/src/usePaginatedCollection.js

This PR enables the items per page Select component in `RelayPaginationControls` on the domains and organizations pages so that the user can opt to see more items at once. This addresses informal user feedback that was received last week.

Add items per page dropdown to Organizations and Domains pages

---

api-js/src/organization/loaders/load-organization-by-slug.js

This PR adds an `OR` statement to the `orgLoaderBySlug` to permit either slug being submitted with different language headers.

Check for EN and FR Slugs

---

api-js/src/dmarc-summaries/loaders/__tests__/load-dmarc-sum-connections-by-user-id.test.js
api-js/src/dmarc-summaries/loaders/load-dmarc-sum-connections-by-user-id.js
api-js/src/dmarc-summaries/queries/find-my-dmarc-summaries.js
api-js/src/enums/dmarc-summary-order-field.js
frontend/schema.faker.graphql

This PR adds a search field to the `findMyDmarcSummaries` query to filter the data returned by entering a domain in the search string argument. This PR also adds support for ordering the return based on the domain the summary is related to.
```graphql
query {
findMyDmarcSummaries (first: 5, month: JANUARY, year: "2021", search: "cyber") {
edges {
node {
id
domain {
domain
}
categoryTotals {
fail
fullPass
passDkimOnly
passSpfOnly
}
...
}
}
}
}
```

Add Search Field to findMyDmarcSummaries Query

---

api-js/database-options.js

This option tells arangodb to ensure that data gets written to 2 of the 3 db
servers.

Add replicationFactor option for all collections

---

clients/python/setup.py
clients/python/tracker_client/__version__.py
clients/python/tracker_client/core.py

This PR adds a custom `user-agent` header for the API client as requested in #2079. It also implements a single source of truth for versioning, `__version__.py`.
Closes #2079.

Add custom user-agent header for client

---

app/bases/arangodb-deployment.yaml
app/bases/arangodb-operator.yaml
app/gke/arangodb-deployment.yaml
app/gke/kustomization.yaml
app/gke/storage-classes.yaml
app/test/kustomization.yaml
app/test/storage-classes.yaml

This commit reworks the way we do persistent volume claims, finally giving us a
much better setup: db servers now get fast ssd of a reasonable size, and we're
now using storage classes set to reclaim so that drives don't disappear when
the cluster does.

Rework db storage

---

deploy/bases/dns-scanner-registry.yaml
deploy/bases/https-scanner-registry.yaml
deploy/bases/result-processor-registry.yaml
deploy/bases/ssl-scanner-registry.yaml

Flux was set to check the wrong GCR directory for updated scanner images, this is now fixed.

Fix scanner image updates

---

frontend/src/DmarcByDomainPage.js
frontend/src/DmarcReportTable.js
frontend/src/DomainsPage.js
frontend/src/Organizations.js
frontend/src/client.js
frontend/src/fixtures/dmarcReportSummaryTable.js
frontend/src/graphql/queries.js

This PR fixes the bug described in #2050 by switching the DMARC Summary table to using the newer `findMyDmarcSummaries` query instead of `findMyDomains`. It also refactors DmarcReportTable.js to pull pagination code out into its parent component, which requires less code, behaves more predictably, and is more maintainable.
It additionally:
- Makes it so pagination controls are displayed even if the "no messages" error replaces the DMARC report table
- This will reduce the severity of the issue mentioned above should it reoccur by not requiring a reload to see the table
- updates relevant test fixtures
- changes page size options elsewhere to be more consistent
Closes #2050.

Fix DMARC Summary Report Pagination

---

api-js/src/organization/loaders/__tests__/load-organization-connections-by-user-id.test.js
api-js/src/organization/loaders/load-organization-connections-by-user-id.js
api-js/src/organization/queries/find-my-organizations.js

This PR adds a new `isAdmin` filter to the `findMyOrganizations` query filtering the orgs for ones that the given user is an admin or higher to.

Update Org Loader and Query to Support Admin Filter

---

deploy/creds/bases/flux-system-namespace.yaml
deploy/creds/bases/kustomization.yaml
deploy/creds/kustomization.yaml
deploy/creds/readwrite/kustomization.yaml

The deploy creds generate the secrets flux needs to commit back to the repo.
The secrets are marked as belonging to the flux-system namespace, but that
doesn't necessarily exist... so this commit ensures that it does.

Add flux-system namespace to deploy creds

---

Makefile

This commit makes the following commands work:
```
make print-arango-deployment env=aks
make print-ingress env=gke
```
While working on config, it's common to want to take a look at these two
crucial bits of config to ensure they are doing what you expect.
These commands render the config, and use yq to sift through the result and
print the appropriate object.
Options for the env are any of our overlay names: aks, gke, test, minikube.
For these commands to work you will need the python version of yq installed:
https://pypi.org/project/yq/

Add commands to print key config bits per env

---

app/aks/storage-classes.yaml
app/gke/storage-classes.yaml
app/test/storage-classes.yaml

This prevents our db pods from getting blocked by waiting for the pods to exist
before binding the pvcs.

Set pvc volumeBindingMode to waitForFirstConsumer

---

api-js/src/domain/loaders/load-domain-connections-by-organizations-id.js
api-js/src/domain/loaders/load-domain-connections-by-user-id.js
api-js/src/domain/mutations/create-domain.js
api-js/src/domain/mutations/update-domain.js
api-js/src/locale/en/messages.po
api-js/src/locale/fr/messages.po

This PR makes the search algorithm ignore case, as well as updating the `createDomain` and `updateDomain` mutations to force domains to lower case before inserting into db.

Domain Search Ignore Case

---

api-js/src/affiliation/mutations/__tests__/remove-user-from-org.test.js
api-js/src/affiliation/mutations/remove-user-from-org.js
api-js/src/affiliation/objects/__tests__/remove-user-from-org-result.test.js
api-js/src/affiliation/objects/remove-user-from-org-result.js
frontend/schema.faker.graphql

This adds a `user` field of the type `userSharedType`, example:
```graphql
mutation {
removeUserFromOrg (
input: {
userId: "<user id>"
orgId: "<org id>"
}
) {
result {
... on RemoveUserFromOrgResult {
status
user {
id
userName
}
}
... on AffiliationError {
code
description
}
}
}
}
```

Return Removed User from Org

---

api-js/src/organization/mutations/__tests__/remove-organization.test.js
api-js/src/organization/mutations/__tests__/verify-organization.test.js
api-js/src/organization/mutations/remove-organization.js
api-js/src/organization/mutations/verify-organization.js
api-js/src/organization/objects/__tests__/organization-result.test.js
api-js/src/organization/objects/organization-result.js
frontend/schema.faker.graphql

This mutation adds in an organization field on the `organizationResult` type, allowing org fields to be queried when being removed or verified.

Return Org When Verified or Removed

---

api-js/src/domain/mutations/__tests__/remove-domain.test.js
api-js/src/domain/mutations/remove-domain.js
api-js/src/domain/objects/__tests__/domain-result.test.js
api-js/src/domain/objects/domain-result.js
frontend/schema.faker.graphql

This pr allows the domain being removed to be queried in the `removeDomain` mutation.

Return Domain When Removed

---

api-js/src/auth/__tests__/generate-jwt.test.js

This commit adds a test proving that jwt expires in 1 hour by default.

Add explicit test for JWT expiry time

---

Makefile
platform/components/istio/istio.yaml

The latest version of istio allows the use of distroless images. After some
testing, these are working well, so here we go!

Use distroless images for istio

---

app/namespaces/db-namespace.yaml

This commit disables istio's sidecar injection for the db namespace. This seems to resolve some mysterious errors we were seeing.
In the logs for the sidecar we were seeing:
`warning envoy config  StreamAggregatedResources gRPC config stream closed: 0,`
And in the coordinators:
`2021-05-18T16:11:49Z [1] ERROR [abcde] {communication} communication error: 'Error: invalid server response' from destination 'server:CRDN-yyunugrj'`
We'll need to revisit sidecar injection shortly.

Disable injection for db namespace

---

api-js/src/domain/mutations/__tests__/create-domain.test.js
api-js/src/domain/objects/__tests__/domain.test.js
api-js/src/domain/objects/domain.js
api-js/src/organization/loaders/__tests__/load-organization-connections-by-domain-id.test.js
api-js/src/organization/loaders/__tests__/load-organization-connections-by-user-id.test.js
api-js/src/organization/loaders/load-organization-connections-by-domain-id.js
api-js/src/organization/loaders/load-organization-connections-by-user-id.js
api-js/src/organization/queries/find-my-organizations.js

This PR adds in `includeSuperAdminOrg` a boolean filter argument to the `findMyOrganizations` query, and `organizations` field on the `Domain` GQL object.

Add Super Admin Org Filter

---

Makefile

Now we can do a backup with the following command:
```
$ make backup to=~/tracker-backup-$(date --iso-8601)
```

Accept backup directory variable

---

frontend/src/LocaleSwitcher.js
frontend/src/__tests__/App.test.js
frontend/src/__tests__/TopBanner.test.js
frontend/src/client.js
frontend/src/i18n.config.js
frontend/src/index.js

- Sets the 'Accept-Language' header according to the current locale
- Resets the cache on language switch
- Sets the frontend language to the browser's language by default

Add 'Accept-Language' header to requests on frontend

---

frontend/src/DmarcGuidancePage.js
frontend/src/DomainCard.js
frontend/src/GuidanceTagList.js
frontend/src/ScanCategoryDetails.js
frontend/src/fixtures/dmarcGuidancePageData.js
frontend/src/graphql/queries.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

- Separated Guidance into Web Results and Email Results (closes #2227)
- Changed link button text on domain card from 'DMARC Guidance' to 'Guidance' to be more general
- Added additional information to top of HTTPS and SSL guidance
- Added lists of ciphers to SSL guidance (closes #2226)

Fe add ciphers to guidance

---

guidance/chartSummaryCriteria.json
guidance/scanSummaryCriteria.json
services/scanners/results/result_processor.py
services/scanners/results/tests/test_data.py

This PR contains a fix to logic that resulted in the "no HSTS" tag never being applied, moves tags related to HSTS preload out of the negative category, and also removes them from fail criteria to reflect that official guidance does not mention HSTS preload.

Fix HSTS guidance issues

---

services/core/core.py
services/dmarc-report/database-options.js
services/super-admin/database-options.js

This PR adds various args to the `db.create_collection` method, and the options to the `databaseOptions` object to ensure replication and sharding.
Also removing unused collections in the super admin service and dmarc report service.
Closes #2199 and Closes #2135

Update Core Service Collection Creations

---

frontend/src/DomainCard.js
frontend/src/DomainsPage.js

Fix DomainCard from overflowing on smaller screens. Also switches breakpoints for some properties (such as the scan result circle's flexDirection) and aligns the scan result circles.
Before:
After:
Before:
After:
Before:
After:

Fix formatting of domain cards

---

frontend/src/ScanCategoryDetails.js

Fix guidance page when no scans for a category exist

---

frontend/src/OrganizationCard.js

Allow for null return from org summaries

---

frontend/src/OrganizationDetails.js
frontend/src/OrganizationSummary.js
frontend/src/SummaryGroup.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

Adds text in place of summary cards when summary data does not exist.

Allow for organization summaries to be null on org summary page

---

frontend/.dockerignore
frontend/Dockerfile

This commit switches the frontend to using a distroless image from RedHat Engineer
Antonin Stefanutti: https://github.com/astefanutti/scratch-node
Our image was built with the following command and pushed to our image registry:
```
docker build --build-arg version=16.1.0 --build-arg arch=x86_64 .
```
This change removes all components of a usable operating system from the image
leaving only the node interpreter and our code.

Use distroless node image for frontend

---

api-js/src/domain/mutations/__tests__/create-domain.test.js
api-js/src/domain/mutations/create-domain.js

This PR fixes the issues when adding a domain that already exists in Tracker to another organization, it originally reset the `status` and `lastRan`  values.
Closes #2317

Update Create Domain Issues

---

api-js/src/organization/loaders/__tests__/load-organization-by-slug.test.js
api-js/src/organization/loaders/load-organization-by-slug.js

This PR updates the `loadOrganizationBySlug` DataLoader to support dealing with switching translations and returning the other translated version of the org. This is a temporary fix, until the API and FE can be updated to receive both english and french slugs and when switching between translations it will also switch out the slugs.

Update Organization Slug DataLoader

---

Makefile
app/creds/dev/kustomization.yaml
app/creds/prod/kustomization.yaml
app/jobs/super-admin.yaml
app/namespaces/kustomization.yaml
app/namespaces/sa-namespace.yaml

This commit finally makes it easier to use the superadmin service.
A superuser .env is created by the makefile, and the job definition now uses
the credentials that are in the secret that .env file creates.
Both the job and the secret are in the superadmin namespace.
`make secrets` now accepts parameters that set the values of the superadmin.env.
The following values are the default and are optional, but specifying them
obviously supplies better values.
```
make credentials mode=dev displayname=admin email=admin@example.com password=admin
```
This means that setting up an instance for the first time, you have an easy way
to get a base account going.

Get superadmin job working

---

deploy/README.md

Clarify what `make deploy` is doing and add some context about credentials.

Update deploy readme.

---

frontend/src/DmarcByDomainPage.js

The text was a hyperlink, but not readily viable in anyway.
I only noticed it was a link by accident. This button is a much clearer indicator to navigating to the DMAR Report page

add report button to table

---

frontend/src/CreateUserPage.js

Create account was on the left, and the back button was on the right. This original ordering is unintuitive.

Reverse order of create account buttons

---

api-js/src/user/mutations/__tests__/verify-account.test.js
api-js/src/user/mutations/verify-account.js

So with the new updates to the frontend with regards to the email verification, I think it's time I fix this small issue on the API side. Now users no longer need to be signed in to verify their email, they can just click on the link from the email and they're all set.

Fix Verify Account Mutation

---

frontend/src/Navigation.js

This change makes it so that the Sign out button no longer ends up on its own line for medium sizes.

Fix Sign-out button ending up on its own line for small widths

---

frontend/cloudbuild.yaml

This commit requests a high CPU machine for Cloud build, to speed up the
frontend build pipeline.

Moar CPU for frontend builds

---

frontend/src/App.js

smallDevice was only set at page load:
If loaded large, the footer would still be displayed when small.

Update footer to Responsive Styling

---

frontend/src/Doughnut.js
frontend/src/SummaryCard.js
frontend/src/SummaryGroup.js
frontend/src/__tests__/Doughnut.test.js

Doughnut colours were hardcoded, and the passed colour was ignored

added colour support to Doughnut

---

frontend/src/App.js
frontend/src/DmarcByDomainPage.js
frontend/src/FloatingMenu.js
frontend/src/__tests__/DmarcByDomainPage.test.js
frontend/src/locales/en.js
frontend/src/locales/en.po
frontend/src/locales/fr.js
frontend/src/locales/fr.po

paths to /dmarc-summaries used DMARC Report, and the summary table was labeled DMARC Messages.
These are all now referenced as DMARC Summaries

Reference /dmarc-summaries by name

---

api-js/src/organization/loaders/__tests__/load-organization-connections-by-domain-id.test.js
api-js/src/organization/loaders/__tests__/load-organization-connections-by-user-id.test.js
api-js/src/organization/loaders/load-organization-connections-by-domain-id.js
api-js/src/organization/loaders/load-organization-connections-by-user-id.js

This PR fixes changes with the new slug for the super admin organization so that it can be filtered in the admin profile org list.

Fix Super Admin Org Filter

---

frontend/src/UserList.js

Fixes the initial value set in the invitation area on the admin page. The super-admin org does not have a 'USER' option, but the initial value was still set to 'USER'.

Fix user role value for super-admin org

---

scripts/loadtesting/frontend.js

This commit changes the load testing script so it doesn't assume a length...
something that makes for messy output in the case of refused connections.

Handle connection refused better in loadtests

---

app/staging/README.md
app/staging/arangodb-deployment.yaml
app/staging/certificate.yaml
app/staging/knative/config/queues.yaml
app/staging/kustomization.yaml
app/staging/publicgateway.yaml
app/staging/storage-classes.yaml
deploy/staging/app-kustomization.yaml
deploy/staging/kustomization.yaml
deploy/staging/platform-kustomization.yaml
platform/staging/README.md
platform/staging/domain-config.yaml
platform/staging/istio-ingressgateway-service.yaml
platform/staging/kustomization.yaml

This commit adds the overlays needed for an AKS based staging environment.
This should be enough to get Tracker going:
```sh
make secrets # env=dev is the default
make deploy env=staging
```

Add staging overlays

---

frontend/src/OrganizationAffiliations.js
frontend/src/UserCard.js
frontend/src/UserList.js
frontend/src/__tests__/OrganizationAffiliations.test.js
frontend/src/fixtures/adminPanelData.js
frontend/src/fixtures/orgUserListData.js
frontend/src/graphql/queries.js

Adds each users displayName to the User Card
They display Hello World on the local build, but I'm not sure how to check the data structure that we pull from, or edit it so that they have proper display names for testing.

add display names to UserCard

---

frontend/src/AdminDomains.js
frontend/src/DmarcByDomainPage.js
frontend/src/DomainsPage.js
frontend/src/Organizations.js
frontend/src/__tests__/Organizations.test.js
frontend/src/client.js

Changes the fetchPolicy for queries with search to 'cache-and-network', and sets nextFetchPolicy to 'cache-first'.
This behaviour causes the first instance of a query (with its specific arguments) to send a network request. Setting the nextFetchPolicy to 'cache-first' will ensure that subsequent requests for the same query can be pulled from the cache. This cycle is destroyed on component unmount or if the query changes. In practice, this means that changing search/order or switching off the page and coming back will ensure the user gets fresh data.

FE Change Network Policy for Queries with Search

---

frontend/Dockerfile

This commit removes and extraneous build step and uses `npm prune` to slim down
the modules in the final image while still keeping the ones like webpack that
are needed to build.

Simplify frontend Dockerfile

---

platform/aks/istio-ingressgateway-service.yaml
platform/aks/kustomization.yaml
platform/staging/istio-ingressgateway-service.yaml
platform/staging/kustomization.yaml

This commit gets rid of the old istio-ingressgateway-service patches, in favor of an JSON patch on the IstioOperator done inline in the kustomization file.

Move internallb annotations

---

frontend/mocking/mocker.js
frontend/src/AdminDomains.js

Domain names were not right-aligned when not scanned. This fix allows the domain name area to FlexGrow to fill the rest of its parent's card width.
Before:
After:

Right-align domains in domain cards when not scanned

---

frontend/mocking/mocker.js
frontend/src/ScanCard.js
frontend/src/ScanCategoryDetails.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

Add steps to Email guidance card based on displayed DMARC phase

add translated next steps to guidance page based on dmarc phase

---

platform/base/istio-operator.yaml
platform/minikube/kustomization.yaml

This commit ensures we are running more than a single copy of istiod and that
they don't end up on the same node. Also included; JSON patch to remove this
setting when running locally in minikube.

Run 2 replicas of istiod

---

platform/components/istio/envoy-security-headers-filter.yaml

This commit follows isito's advice to result the following warning:
```sh
Warning: using deprecated filter name "envoy.router"; use "envoy.filters.http.router" instead
```

Fix istio warning

---

services/scanners/dns/dns_scanner.py

This PR fixes an error caused by the DNS scanner attempting to examine the DMARC record of domains that lack one.

Fix KeyError when domain has no dmarc record

---

frontend/src/FloatingMenu.js
frontend/src/TopBanner.js

implements the recommendations in #2475
Hides sign in buttons on mobile width, since they are located in the floating menu

add create account button to floating menu

---

frontend/src/LocaleSwitcher.js

Rounds the corners of the language button to match the other buttons.
Current:
Proposed:

round corners of language button

---

api-js/src/affiliation/loaders/load-affiliation-connections-by-org-id.js
api-js/src/affiliation/loaders/load-affiliation-connections-by-user-id.js
api-js/src/dmarc-summaries/loaders/load-dkim-failure-connections-by-sum-id.js
api-js/src/dmarc-summaries/loaders/load-dmarc-failure-connections-by-sum-id.js
api-js/src/dmarc-summaries/loaders/load-dmarc-sum-connections-by-user-id.js
api-js/src/dmarc-summaries/loaders/load-full-pass-connections-by-sum-id.js
api-js/src/dmarc-summaries/loaders/load-spf-failure-connections-by-sum-id.js
api-js/src/domain/loaders/load-domain-connections-by-organizations-id.js
api-js/src/domain/loaders/load-domain-connections-by-user-id.js
api-js/src/email-scan/loaders/load-dkim-connections-by-domain-id.js
api-js/src/email-scan/loaders/load-dkim-results-connections-by-dkim-id.js
api-js/src/email-scan/loaders/load-dmarc-connections-by-domain-id.js
api-js/src/email-scan/loaders/load-spf-connections-by-domain-id.js
api-js/src/organization/loaders/load-organization-connections-by-domain-id.js
api-js/src/organization/loaders/load-organization-connections-by-user-id.js
api-js/src/verified-domains/loaders/load-verified-domain-connections-by-organization-id.js
api-js/src/verified-domains/loaders/load-verified-domain-connections.js
api-js/src/verified-organizations/loaders/load-verified-organization-connections-by-domain-id.js
api-js/src/verified-organizations/loaders/load-verified-organizations-connections.js
api-js/src/web-scan/loaders/load-https-connections-by-domain-id.js
api-js/src/web-scan/loaders/load-ssl-connections-by-domain-id.js

Currently there are issues with sorting the data coming from connection loaders because keys weren't being sent to number.

Fix Sorting Issues on Connection Loaders

---

Makefile
app/bases/backup-service-account.yaml
app/bases/kustomization.yaml
app/jobs/backup/aks/backup-job.yaml
app/jobs/backup/aks/kustomization.yaml
app/jobs/backup/base/backup-job.yaml
app/jobs/backup/base/kustomization.yaml
app/jobs/backup/gke/README.md
app/jobs/backup/gke/backup-job.yaml
app/jobs/backup/gke/kustomization.yaml
app/jobs/backup/staging/backup-job.yaml
app/jobs/backup/staging/kustomization.yaml
app/jobs/backup/test/README.md
app/jobs/backup/test/backup-job.yaml
app/jobs/backup/test/kustomization.yaml
app/test/backup-service-account.yaml
app/test/kustomization.yaml

This commit adds a one time backup job.
The makefile has been changed to create a backup job in the db namespace.
The backup job uses `arangodump` and `rclone` create a backup and upload it to
either Google Cloud Storage or Azure Blob Storage.
The backup job can be triggered like so:
```
make backup env=gke
```

Add one time backup job

---

frontend/src/OrganizationCard.js

The whole card is a link, So trying to render a TrackerButton inside it was causing errors.
fixes #2391

Remove TrackerButton from OrgCard

---

services/scanners/https/scan/models.py

Resolves issue related to accessing non-existent endpoint attribute.
To replicate, scan `aanc-inac.gc.ca` for HTTPS configuration
`'Endpoint' object has no attribute 'https_cert_revoked'`

Update models.py to add required attribute

---

api-js/src/affiliation/mutations/invite-user-to-org.js
api-js/src/organization/mutations/__tests__/verify-organization.test.js
api-js/src/organization/mutations/create-organization.js
api-js/src/organization/mutations/verify-organization.js
api-js/src/user/mutations/sign-up.js

This new owner field on affiliation connections, allows us to see who the owner of a given sandbox organization is. This field is set to true to the user who created the org, and eventually will be able to be transferred to another user. 
This field is also added in when an existing user is invited to an org, or when they sign up with a token, the field is set to false.
When a super admin verifies an org, all owner fields are set to false.

Implement New Owner Field on Affiliations

---

services/scanners/results/result_processor.py

These changes facilitate the functional display of one-time scan results on the frontend by providing the use of corresponding domain keys.

Send domain key along with results for one-time scans

---

api-js/src/domain/loaders/load-domain-connections-by-organizations-id.js
api-js/src/domain/loaders/load-domain-connections-by-user-id.js
api-js/src/verified-domains/loaders/load-verified-domain-connections-by-organization-id.js
api-js/src/verified-domains/loaders/load-verified-domain-connections.js

This PR removes unneeded calls to `DOCUMENT` in AQL query strings that were found to have a negative performance impact. Affected operations (domain retrieval by user or by org) should see a large performance improvement.
For example, here is a comparison of the performance of a query getting 100 domains after a particular ID, sorted by HTTPS status:
Before:
After:

Api domain query optimizations

---

frontend/mocking/faked_schema.js
frontend/src/OrganizationDetails.js
frontend/src/__tests__/OrganizationDetails.test.js
frontend/src/graphql/queries.js

adds a isUserAdmin query to the org details page.
If the user is not an admin, the Users tab is not rendered
fixes #2463

Organization user affiliation error

---

api-js/src/affiliation/mutations/__tests__/remove-user-from-org-en.test.js
api-js/src/affiliation/mutations/__tests__/remove-user-from-org-fr.test.js
api-js/src/verified-organizations/loaders/__tests__/load-verified-org-conn-by-domain-id.test.js

When these tests were re-factored the database creation was moved into a `beforeEach` without dropping the database in a `afterEach` so this PR moves the database creation in the `beforeAll` function.

Drop Tables When Testing

---

frontend/src/OrganizationCard.js

Changes width of the org name to 30% for medium (down from 50%). 
Returns to 50% width for large size.
fixes  #2410
Replaces #2502

Ux organization overflow fix

---

Makefile

Set `TRACING_ENABLED` to be false by default in makefile

Disable query tracing by default

---

frontend/src/DmarcByDomainPage.js
frontend/src/DmarcReportPage.js
frontend/src/DmarcReportTable.js
frontend/src/DomainsPage.js
frontend/src/InfoPanel.js
frontend/src/Organizations.js
frontend/src/__tests__/DmarcByDomainPage.test.js
frontend/src/__tests__/InfoPanel.test.js

Showing the button with the closed window
Showing the Button and the expanded glossary

Add Glossary sections

---

app/bases/knative/config/config.yaml
app/bases/kustomization.yaml
app/bases/netpol-arangodb.yaml

This commit adds network policies for ArangoDB's coordinator pods and a
separate one that covers all the pods and the operator too.

Add networkpolicy for ArangoDB

---

services/scanners/dns/dns_scanner.py

These changes prevent a potential TypeError exception from being thrown upon handling exceptions within rua/ruf arrangement validation blocks.

Amend error handling for reporting arrangement verification

---

app/bases/knative/config/autoscan.yaml
app/bases/netpol-arangodb.yaml
app/jobs/scan-job.yaml

Add role labels for "autoscan" and "scan-job" and include them in NetworkPolicy so that they can communicate with the coordinator.

Update ArangoDB network policy

---

services/scanners/dns/dns_scanner.py

Address invalid dict key assignment when catching TypeError, otherwise mark as "undetermined"

"Undetermined" reporting arrangement status

---

api-js/src/affiliation/mutations/__tests__/invite-user-to-org.test.js
api-js/src/affiliation/mutations/invite-user-to-org.js
api-js/src/user/mutations/__tests__/send-email-verification.test.js
api-js/src/user/mutations/__tests__/send-password-reset.test.js
api-js/src/user/mutations/__tests__/sign-up.test.js
api-js/src/user/mutations/send-email-verification.js
api-js/src/user/mutations/send-password-reset.js
api-js/src/user/mutations/sign-up.js

This updates the links sent through Notification to use `https` over `http`, because **security**.

Update Notification Links with HTTPS

---

api-js/src/domain/mutations/__tests__/remove-domain.test.js
api-js/src/domain/mutations/remove-domain.js
api-js/src/locale/en/messages.po
api-js/src/locale/fr/messages.po

This PR brings in fixes to the `removeDomain` mutation when it comes to removing `dkimResults` and `dmarcSummaries` previously these would just be left hanging in the database. As well some quite large updates to the way things were being tested previously to increase testing performance.

Update removeDomain Mutation

---

api-js/src/domain/loaders/load-domain-connections-by-organizations-id.js
api-js/src/domain/loaders/load-domain-connections-by-user-id.js

This PR switches several traversals to breadth first as it was discovered that this drastically improved execution time in some cases.
Before:
After:

Switch traversals in domain connection loaders to breadth first

---

api-js/src/email-scan/loaders/load-dkim-connections-by-domain-id.js
api-js/src/email-scan/loaders/load-dkim-results-connections-by-dkim-id.js
api-js/src/email-scan/loaders/load-dmarc-connections-by-domain-id.js
api-js/src/email-scan/loaders/load-spf-connections-by-domain-id.js
api-js/src/web-scan/loaders/load-https-connections-by-domain-id.js
api-js/src/web-scan/loaders/load-ssl-connections-by-domain-id.js

This PR improves performance when getting scan results by switching a traversal in the results queries to breadth first.
Before (profiling done on HTTPS results):
After:

Use breadth first traversal in results loaders

---

api-js/src/locale/en/messages.po
api-js/src/locale/fr/messages.po
api-js/src/organization/mutations/__tests__/remove-organization.test.js
api-js/src/organization/mutations/remove-organization.js

This PR updates the `removeOrganization` mutation with the same updates that were applied to the `removeDomain` mutation ensuring that `dkimResults` and related dmarc summary data is also removed alongside. As well the entire test suite for this mutation has been completely re-written.

Updates to the Removing Organization Mutations

---

api-js/src/user/mutations/__tests__/authenticate.test.js
api-js/src/user/mutations/__tests__/refresh-tokens.test.js
api-js/src/user/mutations/__tests__/sign-in.test.js
api-js/src/user/mutations/__tests__/sign-out.test.js
api-js/src/user/mutations/__tests__/sign-up.test.js
api-js/src/user/mutations/authenticate.js
api-js/src/user/mutations/refresh-tokens.js
api-js/src/user/mutations/sign-in.js
api-js/src/user/mutations/sign-out.js
api-js/src/user/mutations/sign-up.js

This commit changes cookies to signal the browser that they should only be
accepted if they come via https.

Mark cookies as https only with secure: true.

---

frontend/mocking/faked_schema.js
frontend/src/App.js
frontend/src/SignInPage.js
frontend/src/TopBanner.js
frontend/src/__tests__/SignInPage.test.js
frontend/src/graphql/mutations.js

- `Remember me` option added to sign in page
- `signOut` mutation executed on logout, clearing refresh token
- Login persisted upon refresh, navigation, and tab creation
- silent refresh to be implemented later
closes #1476

Fe Persist Login with Refresh Tokens

---

api-js/index.js
api-js/package-lock.json
api-js/package.json
api-js/src/__tests__/create-context.test.js
api-js/src/__tests__/on-connect.test.js
api-js/src/__tests__/server.test.js
api-js/src/create-context.js
api-js/src/on-connect.js
api-js/src/server.js

This PR updates the API's dependencies, including the update to Apollo Server V3.

API Dependency Updates

---

api-js/src/user/mutations/__tests__/update-user-profile.test.js
api-js/src/user/mutations/update-user-profile.js

This PR updates the `updateUserProfile` mutation and will set the users `emailVerified` value to `false`, only when the user updates their username. In turn a notify email is sent so the user can verify their new username.

Unverify Usernames When Updated

---

frontend/src/AuthenticateField.js
frontend/src/EditableUserLanguage.js
frontend/src/EditableUserTFAMethod.js
frontend/src/ErrorFallbackMessage.js
frontend/src/ForgotPasswordPage.js
frontend/src/GuidanceTagDetails.js
frontend/src/LandingPage.js
frontend/src/Organization.js
frontend/src/OrganizationCard.js
frontend/src/OrganizationDetails.js
frontend/src/OrganizationSummary.js
frontend/src/PageNotFound.js
frontend/src/PhaseBanner.js
frontend/src/ScanCard.js
frontend/src/ScanCategoryDetails.js
frontend/src/ScanDomain.js
frontend/src/SummaryGroup.js
frontend/src/WelcomeMessage.js

change from array notation to object notation:
```
fontSize={['2xl', '2xl', '2xl', '3xl', '4xl']}
fontSize={{ base: '2xl', lg: '3xl', xl: '4xl' }}
```
This means that breakpoints are much clearer
also fixes points that were given two items in the array, where the breakpoint should have been medium, but was actually small.

update ambiguous arrays to objects

---

frontend/src/DmarcReportPage.js
frontend/src/GuidanceTagList.js
frontend/src/ScanCard.js
frontend/src/ScanCategoryDetails.js
frontend/src/TrackerAccordionItem.js
frontend/src/__tests__/ScanCategoryDetails.test.js

Uses built in Chakra Accordion
Buttons now show state of panel with the Chevron
Categories are now clearly buttons that collapse
Ownership is shown by small x padding
(Button is orange due to hover)
mobile

Replace collapse and states, with Accordion

---

frontend/src/OrganizationCard.js
frontend/src/__tests__/OrganizationCard.test.js
frontend/src/__tests__/Organizations.test.js
frontend/src/helpers/matchMedia.js

As described. Avoids the "anchor tag in anchor tag" error by using `useBreakpointValue` to change the card's render type (`as` prop doesn't accept responsive styles).

Add 'view details' button to org card

---

api-js/src/locale/en/messages.js
api-js/src/locale/en/messages.po
api-js/src/locale/fr/messages.js
api-js/src/locale/fr/messages.po
api-js/src/user/mutations/__tests__/close-account.test.js
api-js/src/user/mutations/close-account.js
api-js/src/user/mutations/index.js
api-js/src/user/objects/__tests__/close-account-error.test.js
api-js/src/user/objects/__tests__/close-account-result.test.js
api-js/src/user/objects/close-account-error.js
api-js/src/user/objects/close-account-result.js
api-js/src/user/objects/index.js
api-js/src/user/unions/__tests__/close-account-union.test.js
api-js/src/user/unions/close-account-union.js
api-js/src/user/unions/index.js

This PR introduces a new mutation: `closeAccount` this mutation allows a user to close their own account or a super admin to close a users account. This mutation removes all the relevant information that the user is affiliated with, owned organizations, domains, scan results, dmarc summaries, etc.

Close Your Account Today

---

frontend/src/DomainCard.js

Groups the two kinds of compliances visually on the domain card.

Add border to Web and Email groups

---

api-js/src/affiliation/mutations/__tests__/leave-organization.test.js
api-js/src/affiliation/mutations/leave-organization.js

This PR updates the removal steps to follow along with the new `closeAccount` mutation. The current implementation will leave some hanging data in the db, the changes in this PR will correct this.

More Updates to Leave Organization Mutation

---

api-js/index.js
api-js/package-lock.json
api-js/package.json
api-js/src/__tests__/server.test.js
api-js/src/server.js

This commit adds middleware which attaches the query and transaction functions
to the express request object.
This allows us to get at the query function without needing to pass it around
separately. It also helps our observability by passing the
x-cloud-trace-context header along with database queries allowing for end to
end tracing.

Use arango middleware

---

frontend/src/App.js
frontend/src/PrivatePage.js
frontend/src/__tests__/PrivatePage.test.js

This change allows us to easily pass route params to the components we're
rendering.

Use child as a function pattern for PrivatePage

---

frontend/src/App.js

Changed footer TOS link to be `react-router` link so app does not reload on click

Fix "Terms and Conditions" link to prevent reload

---

frontend/src/AdminDomains.js
frontend/src/DomainsPage.js
frontend/src/LoadingMessage.js
frontend/src/OrganizationAffiliations.js
frontend/src/OrganizationDomains.js
frontend/src/Organizations.js
frontend/src/UserList.js
frontend/src/theme/canada.js

Should fix #2628
but unable to properly test because local environment always displays some users/domains/orgs

Make `No ...` messages the same size as loading messages

---

frontend/src/OrganizationDetails.js
frontend/src/OrganizationSummary.js
frontend/src/__tests__/OrganizationDetails.test.js
frontend/src/client.js

Organization details includes the org tombstone stuff, a list of domains, and a list of affiliated users.
Normal users don't have permission to list users, so the query returns the org tombstone, the domains, affiliations set to "null" and an error: "Cannot query affiliations on organization without admin permission or higher."
This error causes the entire response to the thrown away.
This commit uses an error policy of "ignore" to ignore the permissions error and use whatever was returned.
Closes #2689

Let affiliations fail and display the rest

---

frontend/src/graphql/queries.js

Exposes IDs to accounts with only user permissions in an org
significantly increases query response size
Results were not being used
Replaces  #2505

Remove id query from ORG_DETAILS_PAGE

---

frontend/src/locales/en.po
frontend/src/locales/fr.po

This commit is the result of running `npm run extract -- --clean`, which
deleted 242 unused translations from the files.

Clean out translations

---

app/bases/knative/config/config.yaml
services/queues/ots-result/docker-entrypoint.sh
services/queues/ots-scan/docker-entrypoint.sh
services/queues/result/docker-entrypoint.sh
services/queues/scan/docker-entrypoint.sh
services/results/Dockerfile

This PR drastically improves scanner throughput by increasing the number of RQ workers on each queue to 4 (to match the number of workers on each scanner), and allowing them to watch other queues after their own queue is empty. This allows Knative autoscaling to intelligently rebalance the number of scanner replicas if a backlog of scan requests in one category occurs.

Improve scanner scaling

---

frontend/mocking/mocker.js
frontend/src/LandingPage.js
frontend/src/LandingPageSummaries.js
frontend/src/SummaryCard.js
frontend/src/SummaryGroup.js
frontend/src/graphql/queries.js

adds  #2726
Don't appear if the user is logged out

add Summary Doughnuts to landing page for users

---

frontend/src/client.js

Since the PersonalUser type is reserved for the currently logged in user, there is only one instance of this type at a time. Making this a singleton will let any queries that include a PersonalUser easily check the cache.

Make PersonalUser have a singleton cache policy

---

frontend/src/DmarcReportPage.js

Pages with dmarc reports say they don't support aggregate data while the query is loading.

add not isLoading check for does not support aggregate data

---

frontend/src/DmarcReportPage.js

Page is still rendering tables before any requests return.

add tableLoading to the main loading for DMARC Report Page

---

guidance/tags_aggregate.json
guidance/tags_dkim.json
guidance/tags_dmarc.json
guidance/tags_https.json
guidance/tags_spf.json
guidance/tags_ssl.json
services/results/result_processor.py
services/summaries/summaries.py

Some domains monitored by Tracker are not used for web hosting, but still need email protection. This PR exempts domains that are not reachable by both HTTP and HTTPS from calculation of the percentage of domains in compliance with web security policy, to reflect that they do not serve web traffic.

Exclude unreachable domains from web summary calculation

---

app/bases/knative/config/config.yaml

Tracker's scanners can accept a timeout value from their environment, but defaults to 80 seconds. This PR adds the environment variable in question and uses it to set a 20 second timeout.

Make scanner timeout more aggressive

---

frontend/src/ScanDomain.js

add `.toLowerCase()` to one-time scan domain submission
closes #2770

ensure submitted one-time scan domain is lower case

---

api-js/src/scalars/__tests__/scalar-domain.test.js
api-js/src/scalars/domain.js

This PR updates the `Domain` GraphQL scalar to automatically send domains to lower case.

Update Domain Scalar to Send Domains to Lower Case

---

api-js/src/dmarc-summaries/objects/__tests__/category-percentages.test.js
api-js/src/dmarc-summaries/objects/category-percentages.js
services/dmarc-report/src/__tests__/calculate-percentages.test.js
services/dmarc-report/src/calculate-percentages.js

This PR updates the `calculatePercentages` function in the dmarc report service. These changes that are being introduced will help calculate percentages that always add up to 100% rather than 99% or 101%.

Update DMARC Report Percentage Calculation

---

frontend/src/DmarcReportSummaryGraph.js
frontend/src/ScanCategoryDetails.js
frontend/src/theme/canada.js
frontend/src/theme/components/Text.js

adds a shadow to the cipher/curve names to fix the contrast
This will still read as a contrast failure by automated software.

add text shadow

---

api-js/src/__tests__/on-connect.test.js
api-js/src/on-connect.js

This PR updates how we get the users desired language from a connection param rather than through headers.
Closes #2809

Get Language Value from AcceptLanguage Connection Param

---

frontend/src/UserList.js

Fixes issue where two queries would be sent while querying for users part of an organization.

Stop extra affiliations query

---

services/scanners/dns/server.py
services/scanners/https/server.py
services/scanners/ssl/server.py

Hopefully stops the `string indices must be integers` issue in the result processor.

Stop double encoding payloads on timeout

---

api-js/src/dmarc-summaries/objects/__tests__/dkim-failure-table.test.js
api-js/src/dmarc-summaries/objects/__tests__/spf-failure-table.test.js
api-js/src/dmarc-summaries/objects/dkim-failure-table.js
api-js/src/dmarc-summaries/objects/spf-failure-table.js

This is a quick fix regarding the null guidance tag values, this PR returns an empty object which in turn returns a `null` value to the fe.

API Handle Null Values in DKIM and SPF Failure Tables

---

app/bases/knative/config/config.yaml

Attempting to pass an int as an environment variable is not valid and was causing new images to not be applied to the scanners.

Make timeout environment variables strings

---

services/scanners/dns/dns_scanner.py
services/scanners/https/https_scanner.py
services/scanners/ssl/ssl_scanner.py

`os.getenv` returns a string, but timeout value must be an int. Without parsing to int, the scanners will crash if a non-default value is provided.

Parse timeout environment variable to int

---

frontend/src/auth/LanguageSelect.js
frontend/src/auth/__tests__/LanguageSelect.test.js
frontend/src/components/AuthenticateField.js
frontend/src/components/DisplayNameField.js
frontend/src/components/EmailField.js
frontend/src/components/FormField.js
frontend/src/components/PasswordField.js
frontend/src/components/__tests__/AuthenticateField.test.js
frontend/src/components/__tests__/DisplayNameField.test.js
frontend/src/components/__tests__/EmailField.test.js
frontend/src/components/__tests__/PasswordField.test.js
frontend/src/createOrganization/CreateOrganizationField.js
frontend/src/createOrganization/__tests__/CreateOrganizationField.test.js
frontend/src/domains/DomainField.js
frontend/src/domains/__tests__/DomainField.test.js

As described. Now spreads props to top level parent for field components.
Before:
After:

Fix extra spacing for error messages

---

clients/python/Pipfile
clients/python/Pipfile.lock

Setup.py already specifies `python_requires=">=3.6"` and pipenv does not support multiple Python version requirements, or ranges, so this section should be removed from the pipfile.

Remove Python version req from pipfile

---

frontend/src/components/TrackerTable.js
frontend/src/dmarc/DmarcReportPage.js
frontend/src/graphql/queries.js

Replace DMARC report guidance with linked descriptions

---

frontend/src/admin/AdminDomainModal.js
frontend/src/admin/AdminDomains.js
frontend/src/admin/OrganizationInformation.js
frontend/src/admin/UserListModal.js
frontend/src/admin/__tests__/AdminDomains.test.js
frontend/src/auth/CreateUserPage.js
frontend/src/auth/SignInPage.js
frontend/src/auth/TwoFactorAuthenticatePage.js
frontend/src/components/FormField.js
frontend/src/createOrganization/CreateOrganizationField.js
frontend/src/createOrganization/CreateOrganizationPage.js
frontend/src/createOrganization/__tests__/CreateOrganizationField.test.js
frontend/src/domains/DomainField.js
frontend/src/domains/ScanDomain.js
frontend/src/domains/__tests__/DomainField.test.js
frontend/src/domains/__tests__/ScanDomain.test.js
frontend/src/user/EditableUserDisplayName.js
frontend/src/user/EditableUserEmail.js
frontend/src/user/EditableUserLanguage.js
frontend/src/user/EditableUserPassword.js
frontend/src/user/EditableUserPhoneNumber.js
frontend/src/user/PhoneNumberField.js
frontend/src/user/UserPage.js
frontend/src/utilities/fieldRequirements.js

Also adds more changes to FormField. Some were missed in the first pass 😅

Field requirements

---

services/queues/scan/scan_queue.py
services/queues/scan/supervisord.conf

This commit attempts to make the retrying of failed jobs a little less intense
by adding an interval before they are retried.

Add intervals to scan queue

---

scanners/https-scanner/scan/https.py

This commit moves the call to initialize_external_data() so that it executes
when the event loop starts.

initialize_external_data() at startup

---

api-js/package-lock.json
api-js/package.json
api-js/src/scalars/domain.js

This PR aims to fix the issues with the `gc.ca` domain. The issue that is being brought up is that `gc.ca` is itself a tld on the public suffix list [package](https://www.npmjs.com/package/psl) that we were originally using. This PR removes the `psl` package entirely and switches to using regex to validate the domains.
Closes #2841

Fix gc.ca Domain Scalar Issues

---

scanners/dns-scanner/Pipfile
scanners/dns-scanner/service.py

This commit simplifies the way that the scanner connects to Nats to fix the
fact that a nested array of servers was being passed.

Fix dns-scanner nats connection

---

scanners/kustomization.yaml
scanners/scanners-namespace.yaml

This commit adds a kustomize file to the root of the scanners to tie the config
from all the folders together.
The namespace file which all the scanners share is included in the root.

Add kustomization to scanner root

---

scanners/domain-dispatcher/domain-dispatcher-cronjob.yaml
scanners/domain-dispatcher/index.js

This commit properly uses `servers` instead of `url` to connect to nats.

Fix nats connection logic

---

scanners/https-scanner/https-scanner-deployment.yaml
scanners/https-scanner/tls.py

This commit passes the pod name into the container, so it can be properly
identified by nats.

Add name for https-scanner

---

scanners/tls-scanner/service.py
scanners/tls-scanner/tls-scanner-deployment.yaml

Passing in the podname to the tls scanner so it can identify itself to nats.

Add nats name to tls-scanner

---

scanners/dns-scanner/dns-scanner-deployment.yaml
scanners/dns-scanner/service.py

This adds a nat client name for the dns-scanner and defaults it to dns-scanner
if the NAME env var isn't supplied.

Add nats name for dns-scanner

---

scanners/dns-scanner/Pipfile
scanners/dns-scanner/Pipfile.lock
scanners/dns-scanner/dns-scanner-deployment.yaml
scanners/dns-scanner/dns_scanner/dns_scanner.py
scanners/dns-scanner/requirements.txt
scanners/dns-scanner/service.py

Finally making dns-scanner event loop friendly by using a ThreadpoolExecutor
for both the dmarc and dkim scans. This lets us drop pebble as a dependency.

Make dns-scanner event loop friendly

---

scanners/domain-dispatcher/domain-dispatcher-job.yaml
scanners/domain-dispatcher/kustomization.yaml

This commit renames the job file to reflect that it's a job and not a cronjob,
and adds a ttl to clean up the job after it runs.

Add ttl to scan job

---

frontend/src/dmarc/DmarcReportPage.js

Guidance link focus size filled the entire width of parent (1/3 of total main content width). These changes fix this issue.

Fix guidance link focus size on report page

---

frontend/src/components/fields/FormField.js

As described, turns off autocomplete for authenticate field.
Closes #3017

Pass autocomplete to Input in FormField.js

---

scanners/https-scanner/Pipfile
scanners/https-scanner/Pipfile.lock
scanners/https-scanner/requirements.txt
scanners/https-scanner/scan/https.py
scanners/https-scanner/tls.py

This commit switches from publicsuffix2 to publicsuffixlist to stop the
suffixlist from being loaded at runtime (which fails in some environments) and
removes a logging statement that was throwing an error.

Fix https-scanner

---

api/src/organization/objects/__tests__/organization-summary.test.js
api/src/organization/objects/organization-summary.js
services/summaries/summaries.py
services/summaries/tests/test_summaries.py

Currently the organization page does not show a DMARC phase donut for its domains, this PR creates an API query to enable this by:
- Adding summaries to organizations in the database as part of the summeries.py service
- Adds a dmarcPhase to organizations in the API to get summary data from the database

Add dmarc phase summary to organization

---

scanners/tls-scanner/Pipfile
scanners/tls-scanner/Pipfile.lock
scanners/tls-scanner/service.py

This commit switches the tls-scanner from a ThreadPoolExecutor to a
ProcessPoolExecutor since sslyze is launching a bunch of threads and doesn't
seem to clean up after itself.
mprof says memory usage is now stable. 🤞

Switch tls-scanner to ProcessPoolExecutor

---

scanners/dns-scanner/service.py

This commit drops ThreadPoolExecutor in favour of ProcessPoolExecutor to
resolve a memory leak.
mprof now says that memory usage is stable.

Switch dns-scanner to ProcessPoolExecutor

---

app/bases/dmarc-report-cronjob.yaml
app/bases/guidance-cronjob.yaml
app/bases/summaries-cronjob.yaml

Switch retention policy for previous CronJob pods to default limits (3 for successful, 1 for failure)

Switch to default pod retention policy

---

scripts/domain-loader/src/add-organizations-domains.js
scripts/domain-loader/src/align-organizations-domains.js
scripts/domain-loader/src/helpers/remove-edges.js

Uses "WITH" to add "organizations" to AQL traversal context.
Also fixes the conditional when checking if claims exist for a domain.

Add "organizations" to AQL context in scripts

---

app/aks/arangodb-deployment.yaml
app/gke/arangodb-deployment.yaml
app/production/arangodb-deployment.yaml
app/staging/arangodb-deployment.yaml

Noticing the pvcs for the agents piling up in a Released state, so the idea is
that these disks should just be deleted altogether since they don't store data
anyway.

Set Kube-ArangoDB agent disks to Delete

---

app/aks/backup-cronjob.yaml
app/bases/scan-dispatcher-cronjob.yaml
app/gke/backup-cronjob.yaml
app/production/backup-cronjob.yaml
app/staging/backup-cronjob.yaml
app/test/backup-cronjob.yaml
scanners/domain-dispatcher/domain-dispatcher-job.yaml
services/guidance/guidance-job.yaml

Increase job ttl to 6hr from 100sec. Remove usage of ttlSecondsAfterFinished from CronJobs. Using CronJob's default `successfulJobsHistoryLimit` and `failedJobsHistoryLimit` options, 3 successful and 1 failed job will be allowed for history.

Remove usage of ttl cron jobs

---

scanners/docker-compose.yaml

Docker-compose would fail to start https-processor because this env var was misnamed.

Correct https-processor env var in docker-compose

---

scanners/docker-compose.yaml
scanners/https-scanner/https-scanner-deployment.yaml
scanners/https-scanner/https_scanner.py
scanners/https-scanner/scan/https.py
scanners/https-scanner/scan/models.py
scanners/https-scanner/tls.py

Previously timeouts where dealt with via pebble by giving the process as a
whole a timeout:
```bash scanners/https/https_scanner.py
5:from pebble import concurrent
20:    @concurrent.process(timeout=TIMEOUT)
```
We dropped pebble while switching to the async model for the scanners, and
timeout handling was a casualty of that.  This commit fixes timeout handling in
the https-scanner by adding a timeout directly to invocations of requests.get.
Where all of a domains various endpoints are not "live", that domain is now
marked as "unreachable"... which is what the timeout used to be used for.

Fix https-scanner timeout

---

scanners/kustomization.yaml

Given the recent speed increase in the https-scanner, the tls-scanner is now
the slowest. This commit rebalances the number of replicas to reflect the
current performance.

Adjust scanner numbers

---

scanners/dns-processor/dns_processor/__init__.py
scanners/https-processor/https_processor.py
scanners/https-processor/result_processor.py
scanners/tls-processor/tls_processor/__init__.py

This commit adds timestamps to the various edges so that graph traversals can
be constrained by time. For example, a traversal that gets the latest https
scan result for a domain.
Currently this is harder than it needs to be because timestamps live on the
scan result, rather than the edge that connects it to a domain.

Add timestamps to edges before saving them

---

scripts/db/cipher-failures.js
scripts/db/curve-failures.js

Failing people for stuff that is explicitly marked as "phase out" or "weak" by
the Cybercentre is pretty uncontroversial. However there are many cases where
we fail people for using things that aren't explicitly approved by the
Cybercentre. This is a different ball of wax that we need to take stock of.
These scripts do that job: generating a summary of cipher and curve failures
that are *not* on the Cybercentre's naughty list. This is both a sanity check
for Tracker itself and also potentially helpful information for the Cybercentre
so they can prioritize their cryptographic work.

Add failure analysis scripts

---

frontend/src/domains/__tests__/DomainCard.test.js

This fixes a printed warning in the test.

Add missing policy data to DomainCard test

---

frontend/src/summaries/__tests__/Doughnut.test.js

This fixes a warning that was being printed in the test output.

Add missing id prop to doughnut test

---

frontend/package-lock.json
frontend/package.json

Apollo server 3 dropped support for subscriptions as part of it's focus on
federation. Mocker uses this functionality and therefore broke.
Since Apollo Server is just a dev dependency, this commit fixes mocker by
simply downgrading Apollo server.

Fix mocker by downgrading Apollo server

---

frontend/src/client.js
frontend/src/organizationDetails/OrganizationAffiliations.js

As described. 
This issue occured as we weren't using the `relayStylePagination()` helper function when creating the apollo client cache. Using this caching method creates issues for individual organization pages as we return the organization's affiliation count but not the affiliation nodes. `relayStylePagination()` sees that no edges are returned when querying for the affiliations and creates an empty array instead (even though affiliations may exist, we just may not be asking for them). Cache hits for affiliations  would then just encounter the empty array and no affiliation connections would end up being returned as the client thinks none exist. Adding a `fetchPolicy: "network-only"` and `nextFetchPolicy: "cache-first"` to queries which only want the totalCount (such as the individual …

Fix affiliation connections for organizations (caching issue)

---

frontend/src/landing/LandingPage.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

This commit adds links to Standard on Email Management and ITPIN to the
description on the landing page.
Closes #3200

Add policy links to description

---

scanners/log4shell-processor/index.js

Adds a bit of a terrible way to catch the domain name from the LDAP request coming back from the Log4J server
this should work on an exploited server
```
curl server:8080 -H 'X-Api-Version: ${jndi:ldap://app:1389/cn=canada.ca}'
```

feat: catch domain name from after call

---

scanners/https-scanner/Pipfile
scanners/https-scanner/Pipfile.lock
scanners/https-scanner/counter.logs
scanners/https-scanner/requirements.txt
scanners/https-scanner/tls.py

This commit finally silences the urllib warnings we get from using verify=false
with requests.

Silence urllib warnings

---

app/gke/publicgateway.yaml

This was disabled briefly for log4shell scanning reasons, but it's back now.

Re-enable http redirect

---

app/arangodb/kustomization.yaml
app/bases/arangodb-operator.yaml

This commit updates the Kube-ArangoDB operator to 1.2.6 and also fixes the
storage operator CRD by following this comment:
https://github.com/arangodb/kube-arangodb/issues/780#issuecomment-942796751

Update to Kube-ArangoDB 1.2.6+

---

scanners/docker-compose.yaml
scanners/https-scanner/https-scanner-deployment.yaml

The timeout was causing false negative HSTS results as some requests don't complete in time. ex. canada.ca has 3 redirects and would time out before finishing, resulting in HSTS = false.

Increase scan timeout from 0.5 -> 2.0 (fixes false negative HSTS)

---

scripts/codemods/package-lock.json
scripts/codemods/package.json
scripts/codemods/test.js
scripts/codemods/upgrade-at.js

The latest version of arango-tools has been changed to make it viable in an
initContainer. Adopting this version requires a complex edit to 120 files, so
this commit adds a codemod to do that work.
The codemod is run with the following command in the codemods folder:
```
npm run transform -- -t upgrade-at.js ../../api/src/ --schemaPath=/home/mike/projects/tracker/api/database.json
```

Add Codemod to upgrade arango-tools

---

scripts/codemods/remove-collectionstrings.js

This script transforms the following code:
```js
const collectionStrings = []
for (const property in collections) {
collectionStrings.push(property.toString())
}
const trx = await transaction(collectionStrings)
```
into
```js
const trx = await transaction(collections)
```

Add remove-collectionstrings codemod

---

api/index.js

This commit addresses a weird bug: starting the api with `npm run dev` would
result in the notify client throwing an error.
This ends up being due to how import/require are evaluated, and the previous
ordering meant that our .env wasn't actually added to the environment.
Details in motdotla/dotenv/#509
Since we use dotenv via dotenv-safe... we never saw that.

Fix dotenv import

---

api/index.js
api/src/server.js

This commit moves createcontext out of server.js and into the index so we can
flatten out and simplify the context.

Move createcontext into index file

---

scanners/dns-scanner/dns_scanner/dns_scanner.py

DNS query would not resolve in cluster due to search in `/etc/resolv.conf` - question would be for `selector1._domainkey.canada.ca.scanners.svc.cluster.local.` instead of `selector1._domainkey.canada.ca`. Add period to end of query name to fix (`selector1._domainkey.canada.ca` -> `selector1._domainkey.canada.ca.`)

Fix DNS lookup - add period to end of name

---

app/bases/kustomization.yaml
app/gke/kustomization.yaml

This commit removes the config that deploys the log4shell scanner, thus "undeploying" it.

Stop log4shell scanning

---

platform/gke/kustomization.yaml

This commit follows cert-manager's advice to annotate the ServiceAccount so that
cert-manager works with Google's workload identity and can manipulate Cloud DNS
to complete the Let's Encrypt DNS-01 challenge.
https://cert-manager.io/docs/configuration/acme/dns01/google/#link-ksa-to-gsa-in-kubernetes

Annotate the cert-manager service account

---

platform/components/cert-manager/kustomization.yaml

This is to get CM playing nicely with Google's workload identity.

Enable ambient-credentials for cert-manager

---

app/gke/publicgateway.yaml

This was briefly disabled due to issues with the http-01 challenge. We're now
doing certs via dns-01 so this commit enables redirects again.

Re-enable http redirect.

---

frontend/src/landing/LandingPage.js

Don't show donuts on tracker/suivi alpha.

Reverse match on donut display

---

services/dmarc-report/jest.config.js
services/dmarc-report/package.json
services/dmarc-report/src/loaders/__tests__/load-ownership.test.js
services/dmarc-report/src/loaders/load-ownerships.js

The github.com/canada-ca/dmarc-domains repo has a slightly simplified format
for the domains file, so this is updates the code to work with that.

Update to use the new domains repo format

---

services/dmarc-report/package-lock.json
services/dmarc-report/package.json

Also removing deprecated eslint-plugin-standard as per:
https://github.com/standard/standard/issues/1316

Update dmarc-report service deps

---

scanners/domain-dispatcher/Dockerfile
scanners/domain-dispatcher/package.json

This commit bumps the domain dispatcher to node 17, and adds the ipv4 dns
ordering options so that it doesn't freak out.

Use node 17 for domain dispatcher

---

k8s/infrastructure/bases/istio/istio-operator.yaml

This adds the missing pieces to the hpaSpec to allow the horizontal pod
autoscaler that the operator creates to properly target istiod and the
ingressgateway.

Fix istio hpaspec

---

api/package-lock.json
api/package.json
api/src/server.js
k8s/apps/bases/api/virtual-service.yaml

GraphQL Voyager has not been supported for approx 2 years, resulting in security issues from unupdated deps. This PR removes the local capabilities of Voyager. A guide on how to access the view online will be published to the wiki.

remove graphql-voyager

---

app/bases/scan-dispatcher-cronjob.yaml
k8s/apps/bases/scanners/domain-dispatcher-cronjob/cronjob.yaml

istio sidecar injection forces pod from job to stay alive even if main container is complete. This causes a pile-up of pods as they are never terminated. This workaround turns off concurrency for pods - replacing the previous pod instead of only creating a new one.

Remove cronjob concurrency as istio sidecar forces pod to stay alive

---

frontend/src/admin/SuperAdminUserList.js
frontend/src/auth/TwoFactorAuthenticatePage.js
frontend/src/landing/LandingPageSummaries.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

Super admins can now close user accounts from the super admin userlist on the Admin Profile page
closes #3786

add close account button to SA userlist

---

frontend/package.json
frontend/src/admin/AdminPage.js
frontend/src/admin/SuperAdminUserList.js
frontend/src/admin/UserListModal.js
frontend/src/admin/__tests__/AdminPage.test.js
frontend/src/admin/__tests__/SuperAdminUserList.test.js
frontend/src/admin/__tests__/UserListModal.test.js
frontend/src/app/__tests__/FloatingMenu.test.js
frontend/src/app/__tests__/TopBanner.test.js
frontend/src/auth/SignInPage.js
frontend/src/auth/__tests__/SignInPage.test.js
frontend/src/auth/__tests__/TwoFactorAuthenticatePage.test.js
frontend/src/guidance/DmarcGuidancePage.js
frontend/src/user/__tests__/UserPage.test.js

Improve Frontend Tests

---

k8s/infrastructure/bases/istio/ingress-gateway.yaml
k8s/infrastructure/overlays/production/ingress-gateway-tls-patch.yaml
k8s/infrastructure/overlays/staging/ingress-gateway-tls-patch.yaml

TLS1.3 is very difficult to configure as cipher suites are often non-configurable and chacha is not compliant.

Disable tls1.3 by default for compliance

---

frontend/src/dmarc/__tests__/DmarcByDomainPage.test.js
frontend/src/dmarc/__tests__/DmarcReportPage.test.js

as described, should prevent issue in the future

add dynamic year to dmarc data tests

---

frontend/src/domains/DomainsPage.js
frontend/src/domains/SubdomainWarning.js
frontend/src/guidance/DmarcGuidancePage.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

Add subdomain warning to domain and guidance pages.
Closes #4051

Add www subdomain warning

---

services/guidance/guidance.json

This is replace links to ITPIN with links to [Web Sites and Services Management Configuration Requirements](https://www.canada.ca/en/government/system/digital-government/policies-standards/enterprise-it-service-common-configurations/web-sites.html).
After merge, the `make guidance` job must be run in each environment

replace ITPIN references with WSSMCR

---

frontend/src/guidance/StrengthCategory.js
frontend/src/guidance/WebGuidance.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

All categories were listed as "Strong" - this PR fixes this.

Fix titles for curves and ciphers areas

---

frontend/src/admin/AdminPanel.js

Use AB testing for activity logs

---

api/src/enums/affiliation-user-order-field.js
api/src/user/loaders/load-user-connections-by-user-id.js
api/src/user/mutations/sign-up.js
api/src/user/mutations/update-user-profile.js
api/src/user/objects/user-personal.js
api/src/user/objects/user-shared.js
frontend/mocking/faked_schema.js
frontend/src/admin/AuditLogTable.js
frontend/src/admin/SuperAdminUserList.js
frontend/src/admin/__tests__/AdminDomains.test.js
frontend/src/admin/__tests__/UserListModal.test.js
frontend/src/app/ABTestWrapper.js
frontend/src/auth/CreateUserPage.js
frontend/src/auth/SignInPage.js
frontend/src/auth/TwoFactorAuthenticatePage.js
frontend/src/graphql/fragments.js
frontend/src/graphql/mutations.js
frontend/src/graphql/queries.js
frontend/src/index.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/user/EditableUserTFAMethod.js
frontend/src/user/InsideUserSwitch.js
frontend/src/user/UserPage.js
frontend/src/user/__tests__/InsideUserSwitch.test.js
frontend/src/utilities/userState.js

Adds boolean values for users that represents their preference in viewing insider features behind AB testing.

Add Feature Preview Toggle

---

frontend/src/guidance/WebGuidance.js

We were showing ciphers in the curves area (introduced when moving to composition).

Show curves on guidance page

---

api/src/affiliation/mutations/invite-user-to-org.js
api/src/affiliation/mutations/remove-user-from-org.js
api/src/audit-logs/objects/target-resource.js
api/src/domain/mutations/create-domain.js
api/src/domain/mutations/update-domain.js
api/src/organization/mutations/remove-organization.js
frontend/src/admin/AuditLogTable.js
frontend/src/admin/__tests__/AuditLogTable.test.js

- changes query defaults to show more logs and most recent first
- shows updated props when users/domains are added
- fix bug where removing users logged as update
- changed filters styling to take less room
- fix bug when logging remove-organization
- 
closes #3995

Activity log fixes

---

k8s/apps/bases/scanners/https-scanner/deployment.yaml
k8s/apps/bases/scanners/tls-scanner/deployment.yaml

Bypass envoy proxy for external traffic for web scanners. The scanners were returning bad results for the https check when a domain pointed to an ip address but there was not traffic being served at that ip. Envoy would return a 503 HTTP result, making the scanner think it had received a response from the server.
Before bypass:
After bypass:
Closes #4131

Bypass envoy proxy for external traffic for web scanners

---

api/src/organization/loaders/load-all-organization-domain-statuses.js
api/src/organization/queries/__tests__/get-all-organization-domain-statuses.test.js
api/src/organization/queries/get-all-organization-domain-statuses.js

Currently if an organization name contains a comma, the comma creates an additional column (which it should not). Surrounding the fields with quotes should fix this.
Fixes #4184

Fix CSV export of org list when any org contains a comma

---

api/src/audit-logs/objects/audit-log.js
api/src/email-scan/objects/__tests__/dkim.test.js
api/src/email-scan/objects/__tests__/dmarc.test.js
api/src/email-scan/objects/__tests__/spf.test.js
api/src/email-scan/objects/dkim.js
api/src/email-scan/objects/dmarc.js
api/src/email-scan/objects/email-scan.js
api/src/email-scan/objects/spf.js
api/src/verified-domains/objects/__tests__/verified-domain.test.js
api/src/verified-domains/objects/verified-domain.js
api/src/web-scan/objects/__tests__/https.test.js
api/src/web-scan/objects/__tests__/ssl.test.js
api/src/web-scan/objects/https.js
api/src/web-scan/objects/ssl.js
api/src/web-scan/objects/web-scan.js

Shows timestamps in format `2007-12-03T10:15:30Z`. 
We can make the timestamp even more human-readable on the frontend by using: 
`new Date("2007-12-03T10:15:30Z").toLocaleString()`
resulting in:
`"2007-12-03, 6:15:30 a.m." `
Closes #4280.

Show full timestamp instead of just date

---

api/src/domain/mutations/__tests__/remove-domain.test.js
api/src/domain/mutations/remove-domain.js

Receiving the following error when attempting to remove a domain (and scan data):
```
collection` not known to traversal: 'domains'. please add 'WITH domains' as the first line in your AQL (while executing)
```
This seems like an odd error since we aren't returning any domains and are only pivoting off of one. Including `WITH domains` does fix this issue still.

Fix domain removal

---

api/src/auth/check-domain-ownership.js
api/src/domain/loaders/load-domain-connections-by-user-id.js
api/src/domain/loaders/load-domain-tags-by-org-id.js
api/src/domain/mutations/favourite-domain.js
api/src/domain/mutations/unfavourite-domain.js
api/src/user/loaders/load-my-tracker-by-user-id.js
api/src/user/mutations/update-user-profile.js
api/src/user/queries/is-user-admin.js
api/src/user/queries/is-user-super-admin.js

We are getting "collection not known to traversal" errors during traversal when not including the pivot collection in the "WITH" statement. This seems like it may be due to the database upgrade - but I haven't been able to find this in the ArangoDB changelog **_yet_**.

Add pivot collection to "WITH" for traversals

---

api/src/domain/loaders/load-domain-connections-by-organizations-id.js

fixes issue where after filtering, "next page" button was clickable when it shouldn't be

add domain filters to pagination logic

---

api/src/scalars/domain.js

The current regex only checks if a valid domain exists within the input - meaning something like `iojwseiowefjewoif example.com aiowdjaiowdj` matches and inserted into Tracker. This updates the regex to match the beginning and end of string.

Fix domain regex

---

scanners/web-processor/web_processor/web_processor.py

fix adding ssl19 as a negative tag when there are invalid ciphers

fix ssl19 tag being negative

---

scanners/web-scanner/scan/tls_scanner/tls_scanner.py

In sslyze 5.1.3, the method `extract_dns_subject_alternative_names` has become `parse_subject_alternative_name_extension`

change sslyze method name in tls_scanner to match new name

---

frontend/src/components/InfoPanel.js
frontend/src/components/RelayPaginationControls.js
frontend/src/components/SearchBox.js
frontend/src/theme/components/Button.js

fixes colour and styling of info buttons in search boxes

Fix info button styling

---

frontend/src/utilities/useDebouncedFunction.js

wrap called function within function to prevent potential code injection. This isn't called with user input anyway, but still a best practice.

Added protection in useDebouncedFunction

---

api/src/affiliation/mutations/__tests__/invite-user-to-org.test.js
api/src/affiliation/mutations/invite-user-to-org.js
frontend/mocking/faked_schema.js
frontend/src/admin/UserListModal.js
frontend/src/admin/__tests__/UserListModal.test.js
frontend/src/graphql/mutations.js

Currently when a user is invited, the email they receive is in the preferred language of the user submitting the invitation, not the one receiving the invitation. This PR fixes this.
Closes #4514

Use the invited user's preferred language in email

---

frontend/src/guidance/WebConnectionResults.js

Show unavailable results as "Not available"
closes #4492, closes #4483

Update connection chain results display

---

api/src/organization/mutations/__tests__/archive-organization.test.js
api/src/organization/mutations/archive-organization.js
api/src/organization/mutations/index.js

New mutation that allows super admins to "archive" an org. This mutation:
- takes an org ID as input
- unverifies the org
- archives any domains that **only belong to this org**

Archive organization mutation

---

api/src/domain/inputs/domain-filter.js
api/src/domain/loaders/load-domain-connections-by-organizations-id.js
api/src/enums/domain-tag-label.js
frontend/src/domains/DomainsPage.js
frontend/src/graphql/queries.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/organizationDetails/OrganizationDomains.js

Add new ways to filter domains on org details page. Filter by:
- NXDOMAIN: if the domain has an rcode status of "NXDOMAIN", meaning it does not exist
- Blocked: if the domain is suspected to be blocked by a firewall
- Scan Pending: If the domain is currently being scanned or in queue for scanning

Filter domains by rcode blocked pending status

---

scanners/web-processor/Dockerfile
scanners/web-scanner/Dockerfile

Upgrade base image

---

api/cloudbuild.yaml
api/src/domain/loaders/load-domain-connections-by-organizations-id.js
frontend/src/admin/AdminDomainCard.js
frontend/src/admin/AdminDomainModal.js
frontend/src/domains/DomainCard.js
services/summaries/cloudbuild.yaml
services/summaries/summaries.py

- Allow org admins and above the ability to view and modify their domains marked as hidden
- Domains marked as hidden will now affect landing page summaries (larger totals)

Reveal hidden domains to admins

---

api/src/domain/mutations/__tests__/remove-domain.test.js
api/src/domain/mutations/remove-domain.js
frontend/src/admin/AdminDomainCard.js
frontend/src/admin/AdminDomains.js
frontend/src/fixtures/orgDomainListData.js
frontend/src/graphql/queries.js

- Allows admins of verified orgs to remove domains if they have an rcode of NXDOMAIN (not on the DNS)
- show NXDOMAIN status on admin page
closes #4523

Allow removal of nxdomains

---

api/src/domain/loaders/load-domain-connections-by-user-id.js

Remove extra loop through domains. This adjustment should reduce loading time for the domains page (no login required) from ~4.3s to ~2.0s.
Effort for  #4573

Optimize domain connections by user id loader

---

api/src/domain/loaders/load-domain-connections-by-user-id.js

Query was missing `WITH domains` for traversal.

Fix collected domains query for myTracker

---

api/src/domain/loaders/load-domain-connections-by-user-id.js

Should be returning the entire domain object instead of just the `._key` for domains.

Return domain object for collected domains in myTracker view

---

api/src/domain/mutations/__tests__/add-organizations-domains.test.js
api/src/domain/mutations/add-organizations-domains.js

add flag to tag domains as staging in bulk add

---

api/src/affiliation/mutations/request-org-affiliation.js
frontend/mocking/faked_schema.js
frontend/src/organizationDetails/OrganizationDetails.js
frontend/src/organizationDetails/OrganizationDomains.js
frontend/src/organizations/Organizations.js
frontend/src/summaries/TieredSummaries.js

Bring the following features to the A stream:
- Request Invite btn
- show "hidden domain" summaries btn
- allow domain filtering by hidden status

Reveal 2.1615 features

---

scanners/web-scanner/Dockerfile
scanners/web-scanner/requirements.txt
scanners/web-scanner/service.py

sslyze currently has a memory leak for long running processes. This PR runs the scans using mutliprocessing (through `ProcessPoolExecutor`) which seems to fully clean up after the leak. 
Also includes Python image updates, a newer version of rust-query-crlite, and adds the `--features=rustls/dangerous_configuration` flag which is required for rust-query-crlite when using newer versions of rustls.
Closes #4499

Fix web scanner memory leak

---

k8s/apps/bases/api/domain-cleanup-cronjob.yaml

K8s Cronjob `batch/v1beta1` is deprecated, update to `batch/v1`.

Update cronjob version

---

frontend/mocking/faked_schema.js
frontend/src/domains/DomainCard.js
frontend/src/graphql/queries.js
frontend/src/guidance/GuidancePage.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

As described, to ensure users know this is an option they can receive upon login and affiliation

Make view results button visible on DomainCard for unauth'd users 

---

scanners/dns-processor/service.py

Results for DMARC, SPF, DKIM were being overwritten by `null` if no A records exist. This PR fixes this problem.

Fix dns status results

---

k8s/infrastructure/bases/arangodb/arangodb-deployment.yaml
k8s/infrastructure/overlays/production/storage-classes.yaml
k8s/infrastructure/overlays/staging/storage-classes.yaml

The PR changes the ArangoDeployment from `Cluster` mode to `Single` mode. This creates major speedups as it allows for better indexing and removes the inter-server communication required for our many edge-join queries.
Also changes the `fast` disk type on Azure to `PremiumV2_LRS` as it is much more suited to this job (cheaper and faster).
PR effort for #4573.

Change database from cluster to single server

---

frontend/mocking/faked_schema.js

update faker schema to prevent errors

---

api/src/organization/loaders/load-organization-domain-statuses.js
api/src/organization/objects/organization.js
frontend/src/graphql/queries.js
frontend/src/organizationDetails/OrganizationDetails.js
frontend/src/organizationDetails/OrganizationDomains.js

Takes applied filters as input for domain exports
Extends csv to include tags, hidden, blocked, rcode
closes #4697

Feature export filtered org domains

---

frontend/src/guidance/EmailGuidance.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

Display MX record info exposed on the API
closes #4609

Add mx records to guidance

---

k8s/infrastructure/overlays/gke/backup-cronjob.yaml
k8s/infrastructure/overlays/production/backup-cronjob.yaml
k8s/infrastructure/overlays/staging/backup-cronjob.yaml
k8s/infrastructure/overlays/test/backup-cronjob.yaml

Keep old runs of jobs from cronjobs to ensure jobs are completing properly.

Keep old jobs from backups

---

frontend/src/admin/UserListModal.js

Super admins should have the option to change any user's role to the `USER` role. Currently this option doesn't appear if the user to be changed has the `OWNER` role.

Fix option to change role to user for super admins

---

k8s/infrastructure/bases/istio/istio-operator-deployment.yaml

The operator image was missed during the previous istio update.

Update istio operator to 1.18.5

---

api/src/auth/verify-jwt.js
frontend/src/client.js

This solves the issue of the auth token being unable to properly refresh when the user's computer is asleep.
- `RefreshTokens` mutation is called with no auth token to prevent expiry error
- Error and retry Apollo links are used to refresh tokens when a query fails due to expired token

No longer refresh tokens with expired jwt

---

k8s/apps/bases/api/progress-report-cronjob/cronjob.yaml
k8s/clusters/auto-image-update/bases/image-repo-policies/kustomization.yaml
k8s/clusters/auto-image-update/bases/image-repo-policies/progress-report-image-repo-policy.yaml
services/progress-report/cloudbuild.yaml
services/progress-report/src/progress-report-service.js

fix issue in progress-report manifests where there were two names given: `progress-report` and `org-progress-report`.
Also added triggers on GCP

give progress report service common name throughout cloud files

---

frontend/src/app/TopBanner.js

Wrap login buttons instead of making them shrink.
Closes #4931
Before:
After:

Move login buttons not shrink, wrap instead

---

services/guidance/guidance.json

Update missing selector guidance as selectors are now read-only and Tracker should auto-detect them.
Closes [#4935](https://github.com/canada-ca/tracker/issues/4935)

Update missing selector guidance

---

api/src/domain/mutations/create-domain.js
api/src/domain/mutations/update-domain.js
services/domain-cleanup/index.js
services/domain-cleanup/src/__tests__/get-new-domains.test.js
services/domain-cleanup/src/database/get-new-domains.js
services/domain-cleanup/src/database/index.js
services/domain-cleanup/src/index.js
services/domain-cleanup/src/untag-new-domains-service.js

- Use the weekly domain-cleanup service to remove NEW tags on domain claims older than 120 days
- add `firstSeen` value to claims when domains are created (and old ones updated)

Remove new tags after 120 days

---

k8s/infrastructure/bases/arangodb/arangodb-deployment.yaml
k8s/infrastructure/overlays/gke/backup-cronjob.yaml
k8s/infrastructure/overlays/production/backup-cronjob.yaml
k8s/infrastructure/overlays/staging/backup-cronjob.yaml

Sets CPU request for backup jobs to 1000m.
Also sets CPU and memory requests for the arangodb server to 1000m and 4GB. 
Closes  [#4957](https://github.com/canada-ca/tracker/issues/4957)

Set backup cpu request

---

api/src/organization/mutations/create-organization.js
api/src/organization/mutations/update-organization.js
api/src/organization/objects/organization.js
frontend/src/graphql/queries.js
frontend/src/guidance/EmailGuidance.js
scanners/dns-processor/notify/send_mx_diff_email_alerts.py
scanners/dns-processor/service.py

- add `externallyManaged` bool value to organizations
- only send emails if org is verified and externally managed
- change formatting to include more info, including old + new mx records, org names, record type
- only send emails if hostnames change (IPs and preference not checked anymore)

Improve MX Diff Notifications

---

api/src/dmarc-summaries/loaders/__tests__/load-dmarc-sum-connections-by-user-id.test.js
api/src/dmarc-summaries/loaders/load-dmarc-sum-connections-by-user-id.js
api/src/dmarc-summaries/queries/find-my-dmarc-summaries.js
api/src/domain/loaders/__tests__/load-domain-connections-by-user-id.test.js
api/src/domain/loaders/load-domain-connections-by-user-id.js
api/src/domain/queries/find-my-domains.js
api/src/organization/loaders/__tests__/load-organization-connections-by-user-id.test.js
api/src/organization/loaders/load-organization-connections-by-user-id.js
api/src/organization/queries/find-my-organizations.js

add `isAffiliated` arg to the following queries so users can filter out other orgs' assets
- findMyDomains
- findMyOrganizations
- findMyDmarcSummaries

Add filter by affiliated domains dmarc summaries

---

api/src/domain/loaders/load-domain-connections-by-user-id.js
api/src/organization/loaders/load-organization-connections-by-user-id.js
frontend/src/components/AffiliationFilterSwitch.js
frontend/src/dmarc/DmarcByDomainPage.js
frontend/src/dmarc/__tests__/DmarcByDomainPage.test.js
frontend/src/domains/DomainsPage.js
frontend/src/domains/__tests__/DomainsPage.test.js
frontend/src/graphql/queries.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
frontend/src/organizations/Organizations.js
frontend/src/organizations/__tests__/Organizations.test.js

add `AffiliationFilterSwitch` component to frontend on the following pages:
- /organizations
- /domains
- /dmarc-summaries
This switch allows the user to filter resources based on their account's affiliation with orgs.

Add is affiliated switches to frontend

---

services/progress-report/src/progress-report-service.js

to avoid long floating point values

progress-report/always return values with fixed decimal points

---

frontend/src/guidance/WebTLSResults.js
frontend/src/locales/en.po
frontend/src/locales/fr.po
scanners/web-processor/web_processor/web_processor.py
services/guidance/guidance.json

The [CCCS guidance on TLS](https://www.cyber.gc.ca/en/guidance/guidance-securely-configuring-network-protocols-itsp40062#a31) includes columns of ciphers and curves that are recommended, but should be phased out asap. Instead of marking them as "weak", this PR marks them as "phase_out" and includes an informative guidance tag informing the user they should be transitioned.
closes #5075

Handle "phase out" ciphers/curves

---

api/src/summaries/loaders/load-chart-summary-connections-by-period.js
api/src/summaries/objects/chart-summary.js

fetch historical summary charts beyond https and dmarc

add all metrics to find-chart-summaries query return object

---

services/guidance/guidance.json

fixes issue where tech guidance links are not available
closes #5079

change 'tech_link' key to 'ref_link' in guidance.json

---

scanners/dns-scanner/dns_scanner/dns_scanner.py

Make DNS scan have more clear logging when throwing error while checking if domain is alive - use string version of DNS query type.

Stringify dns rdatatype for more clear error logging

---

api/src/dns-scan/objects/dns-scan.js
api/src/dns-scan/objects/mx-record.js
frontend/mocking/faked_schema.js
frontend/src/client.js
frontend/src/graphql/queries.js
frontend/src/guidance/EmailGuidance.js

Guidance page currently crashes if mx or ns checks gave error as `warnings` will be null. This PR fixes that issue and shows the errors if they occur.

Include errors for mx and ns checks

---

Makefile

This commit updates the `make cluster` command in a few ways:
* Removed `beta` since no options require it
* replaced project name with project variable
* Hardcode k8s version to 1.24 (since higher requires config changes)
* Set release channel to stable (rapid is... rapid.)
* Uses a least privilege service account
The makefile now includes a command for making that least privilege service account as well.
The result is that cluster can be created, and
existing config can be applied without errors/warnings.

Update `make cluster` command

---

frontend/docker-compose.yaml
frontend/envoy-dev.yaml
frontend/webpack.config.js

Pulls the proxy into the host network and doesn't run the frontend and mocker in designated containers. 
Run the frontend directly with `npm run dev`, and the mocker with `npm run mocker` or a dev api with `npm run dev` from within the /api directory.
**Will fix the session cookies not being saved during local development.**

Rework dev proxy for frontend

---

scanners/run-scanners.sh

Switch to custom directories for scanner script.
Simply add the following to `.bashrc` or equivalent:
```
export TRACKER_DIR=<TRACKER ROOT DIRECTORY>
export TRACKER_SCANNER_VENV_DIRNAME=<VENV DIRNAME>
```
With `<VENV DIRNAME>` being the venv directory name in the individual scanners (such as `.venv` )

Use environment variables in scanner script

---

frontend/docker-compose.yaml

Set `restart: always` on the dev proxy so it starts on system boot (and always restarts).

Always restart frontend dev proxy

---

scanners/dns-processor/dns_processor/dns_processor.py

Statuses are strings but we were treating them as bools for the DMARC phase check, so "assess" was never possible. This PR fixes this state (and will likely drop a lot of domains into "assess")

Fix dmarc phase (assess not possible)

---

scanners/web-scanner/scan/tls_scanner/tls_scanner.py

We only use the raw json output of the scan results for logging in case there was an error, we should catch the error and let the scan finish as it doesn't affect the actual scan results.
Closes #5235.

Handle uncaught ValidationError to allow scans to finish

---

scanners/dns-scanner/dns_scanner/dns_scanner.py
scanners/dns-scanner/dns_scanner/email_scanners.py
scanners/dns-scanner/requirements.txt

Upgrades checkdmarc to new major version and ignores unrelated records at the _dmarc subdomain when checking for DMARC records. Currently a bug exists in checkdmarc if unrelated records exist at _dmarc but there is no record found - gives a `list index out of range` error. I created an issue and PR over there to fix it.
Closes #5269

Upgrade checkdmarc and ignore unrelated records at _dmarc

---

api/src/domain/mutations/create-domain.js

allows users to see that domain has been successfully added despite scan failing to dispatch

Bugfix: add trycatch blocks to NATS publish in create-domain

---

k8s/apps/bases/api/domain-cleanup-cronjob.yaml
k8s/apps/bases/api/org-footprint-cronjob/cronjob.yaml
k8s/apps/bases/api/progress-report-cronjob/cronjob.yaml
k8s/apps/bases/azure-defender-easm/add-easm-assets-to-tracker-cronjob/cronjob.yaml
k8s/apps/bases/azure-defender-easm/import-easm-additional-findings-cronjob/cronjob.yaml
k8s/apps/bases/azure-defender-easm/label-known-easm-assets-cronjob/cronjob.yaml
k8s/apps/bases/scanners/dmarc-report-cronjob/cronjob.yaml
k8s/apps/bases/scanners/domain-dispatcher-cronjob/cronjob.yaml
k8s/apps/bases/scanners/summaries-cronjob/cronjob.yaml
k8s/apps/bases/scanners/update-selectors-cronjob/cronjob.yaml
k8s/infrastructure/overlays/gke/backup-cronjob.yaml
k8s/infrastructure/overlays/production/backup-cronjob.yaml
k8s/infrastructure/overlays/staging/backup-cronjob.yaml
k8s/infrastructure/overlays/test/backup-cronjob.yaml

Move to the following timings:
Task | Start time | Rough Duration | Dependencies | Notes
-- | -- | -- | -- | --
add-easm-assets-to-tracker | 7:00 | ? |   | Only on Saturdays
import-easm-additional-findings | 7:00 | ? |   | Only on Sundays
label-known-easm-assets | 7:00 | 8h |   | Only on Fridays
summaries | 8:00 | 5m | Run in morning after scans complete |  
org-footprint | 9:00 | 5s |   |  
progress-report | 9:00 | 10s | Start after summaries completed | Only on 1st of each month
backup | 18:30 | 30m | Finish before anything starts |  
domain-cleanup | 19:30 | 5s | Finish before domain-dispatcher start |  
dmarc-report | 19:40 | 5m | Finish before domain-dispatcher start?? |  
update-selectors | 19:50 | 10s | Finish before domain-dispatcher start |  
domain-dispatcher | 20:00 | 2m |   | …

Adjust cronjobs to start scans earlier

---

k8s/infrastructure/bases/arangodb/arangodb-deployment.yaml

add two configs to the ArangoDeployment to enhance baseline security:
- server.harden
- javascript.endpoints-allowlist
closes #3773

Security: ArangoDB security options

---

k8s/apps/bases/api/domain-cleanup-cronjob.yaml
k8s/apps/bases/api/kustomization.yaml
k8s/apps/bases/api/network-policy.yaml
k8s/apps/bases/api/org-footprint-cronjob/cronjob.yaml
k8s/apps/bases/api/progress-report-cronjob/cronjob.yaml
k8s/apps/bases/frontend/kustomization.yaml
k8s/apps/bases/frontend/network-policy.yaml
k8s/apps/bases/scanners/dmarc-report-cronjob/cronjob.yaml
k8s/apps/bases/scanners/summaries-cronjob/cronjob.yaml
k8s/infrastructure/bases/arangodb/kustomization.yaml
k8s/infrastructure/bases/arangodb/network-policy.yaml
k8s/infrastructure/overlays/production/backup-cronjob.yaml
k8s/infrastructure/overlays/production/kustomization.yaml
k8s/infrastructure/overlays/production/restrict-instance-metadata.yaml
k8s/infrastructure/overlays/staging/kustomization.yaml
k8s/infrastructure/overlays/staging/restrict-instance-metadata.yaml
k8s/jobs/bases/backup/aks/backup-job.yaml
k8s/jobs/bases/backup/base/backup-job.yaml
k8s/jobs/bases/backup/gke/backup-job.yaml
k8s/jobs/bases/backup/staging/backup-job.yaml
k8s/jobs/bases/backup/test/backup-job.yaml
k8s/jobs/bases/guidance/job.yaml
k8s/jobs/bases/restore-backup/bases/restore-backup-job.yaml
k8s/jobs/bases/restore-backup/overlays/gke/patch-restore-backup-download.yaml
k8s/jobs/bases/restore-backup/overlays/minikube/patch-restore-backup-download.yaml
k8s/jobs/bases/restore-backup/overlays/production/patch-restore-backup-download.yaml
k8s/jobs/bases/restore-backup/overlays/staging/patch-restore-backup-download.yaml
k8s/jobs/bases/restore-backup/overlays/test/patch-restore-backup-download.yaml
k8s/jobs/bases/super-admin/super-admin-job.yaml

Add Kubernetes network policies to restrict ingress and egress between pods to only expected traffic:
- Create netpols for the frontend, api, and arangodb pods.
- Labels have been added to pods so they can be allowed to send/receive traffic.
- Create netpols to default-deny pod access to VM instance metadata on AKS.
closes #3774

Security: Add network policies

---

azure-defender-easm/add-easm-assets-to-tracker/clients/kusto_client.py
azure-defender-easm/add-easm-assets-to-tracker/service.py

To avoid importing vast amounts of invalid wildcard domains, this PR filters the labelled assets further to only import ones without CNAME records.

Bugfix: Restrict EASM asset import to non-CNAMEs

---

api/src/organization/loaders/load-organization-connections-by-domain-id.js
api/src/organization/loaders/load-organization-connections-by-user-id.js

Require **every** search term to be in the org (even partially, as a substring) instead of **any** of the search terms.

Require each search term when searching orgs

---

api/src/organization/loaders/load-all-organization-domain-statuses.js
api/src/organization/loaders/load-organization-domain-statuses.js
api/src/organization/objects/organization.js
api/src/organization/queries/__tests__/get-all-organization-domain-statuses.test.js
api/src/organization/queries/get-all-organization-domain-statuses.js
azure-defender-easm/import-easm-additional-findings/clients/kusto_client.py
frontend/src/guidance/AdditionalFindings.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

- add CVE list to domain export CSV
- fix bug where scan-pending filters returned empty list
- filter imported web components by last seen up to 30 days ago

Top 25: List CVEs in exported CSV

---

services/progress-report/src/database/get-org-admins.js

This email can still be turned off under `Account Settings` -> `Email Updates`.

Send progress report email to A or B stream admins/owners

---

azure-defender-easm/import-easm-additional-findings/clients/kusto_client.py

fixes edge case when importing assets from EASM that have null values for 'LastSeen' values

bugfix: add exception handling to filter_recent_data()

---

frontend/src/Server.js
frontend/src/index.js

Doesn't work with dev server since the dev server bypasses express. To test:
- Build with:
```
webpack --env development --config webpack.config.js
```
- Run with:
```
PORT=3300 HOST=0.0.0.0 FRENCH_HOSTS=localhost npm run start
```

Change frontend default language based on server host

---

api/src/organization/loaders/load-organization-summaries-by-period.js
api/src/summaries/loaders/load-chart-summaries-by-period.js
services/summaries/summaries.py

- when summaries service runs more than once a day, summaries should be updated instead of adding a new document
- filter out any current dupes so data/frontend chart is clean

Bugfix: stop duplicating summaries on same date

---

frontend/src/landing/LandingPage.js
frontend/src/userOnboarding/__tests__/TourButton.test.js
frontend/src/userOnboarding/__tests__/TourComponent.test.js
frontend/src/userOnboarding/components/TourButton.js
frontend/src/userOnboarding/components/TourComponent.js

Only show tour button on some pages

---

api/src/domain/mutations/create-domain.js
api/src/domain/mutations/update-domain.js
azure-defender-easm/add-domain-to-easm/clients/easm_client.py
azure-defender-easm/add-domain-to-easm/service.py

reverting changes due to multiple orgs being able to "claim" an org causes approved assets to be given inaccurate state.

Revert easm asset state sync

---

k8s/infrastructure/bases/arangodb/platform/kustomization.yaml

Operator is quite outdated. This also enables the [.spec.single.memoryReservation](https://arangodb.github.io/kube-arangodb/docs/api/ArangoDeployment.V1.html#specsinglememoryreservation) option. 
Will need to manually apply after merging.

Update arango operator to 1.2.43

---

k8s/infrastructure/bases/istio/istio-operator.yaml

Setting `externalTrafficPolicy: Local` to preserve the client IP address.

Set externalTrafficPolicy to local for gateways

---

scanners/web-scanner/scan/web_scanner.py

Endpoint scan only creates a couple connections, should try running it before the TLS scan. Might improve endpoint results in some cases.

Run web http endpoint scan before tls scan

---

frontend/src/guidance/WebTLSResults.js
scanners/web-processor/web_processor/web_processor.py
services/guidance/guidance.json

Add `ssl25` tag for "Invalid Chain Order" as negative finding that fails certificates status
closes #6090

Feature: Add invalid chain order negative finding

---

frontend/src/app/ReadGuidancePage.js
frontend/src/locales/en.po
frontend/src/locales/fr.po

adds IP and User-Agent to read guidance page to help orgs unblock our scanners

Feature: Add allow list guidance

---

api/src/collection-names.js
api/src/initialize-loaders.js
api/src/locale/en/messages.po
api/src/locale/fr/messages.po
api/src/mutation.js
api/src/query.js
api/src/tags/index.js
api/src/tags/loaders/__tests__/load-all-tags.test.js
api/src/tags/loaders/__tests__/load-tag-by-tag-id.test.js
api/src/tags/loaders/index.js
api/src/tags/loaders/load-all-tags.js
api/src/tags/loaders/load-tag-by-tag-id.js
api/src/tags/mutations/create-tag.js
api/src/tags/mutations/index.js
api/src/tags/mutations/update-tag.js
api/src/tags/objects/index.js
api/src/tags/objects/tag-error.js
api/src/tags/objects/tag.js
api/src/tags/queries/__tests__/find-all-tags.test.js
api/src/tags/queries/find-all-tags.js
api/src/tags/queries/index.js
api/src/tags/unions/__tests__/create-tag-union.test.js
api/src/tags/unions/__tests__/update-tag-union.test.js
api/src/tags/unions/create-tag-union.js
api/src/tags/unions/index.js
api/src/tags/unions/update-tag-union.js
database-migration/database.json

adds API capabilities for generating dynamic tags users will use for tagging domains
- super admins can create and update tags
- anyone can see them
- tags must be given a unique `tagId` and bilingual labels
- tags can optionally have a (bilingual) description to explain what they mean
- tags have a `visible` value that indicates if users should be able to see them

Feature: Create, update, and fetch dynamic tags

---

azure-defender-easm/add-easm-assets-to-tracker/service.py
azure-defender-easm/label-known-easm-assets/service.py

Because there is a 24 hour gap between the latest labeling and ADX import, there should be a redundancy check for matching root domains. This will reduce the amount of false positives going to the unclaimed org.

Bugfix: Add label redundency logic to easm sync

---

frontend/src/admin/AdminDomainCard.js
frontend/src/admin/AdminDomainModal.js
frontend/src/admin/AdminDomains.js
frontend/src/domains/DomainCard.js
frontend/src/guidance/GuidancePage.js
frontend/src/organizationDetails/OrganizationDomains.js
frontend/src/organizations/Organizations.js

move the following features to the A stream:
- asset state labels and filters
- pinned unclaimed org
- wildcard entry vs sibling

feature: remove B stream wrappers

---

frontend/src/domains/DomainsPage.js

A user with 'en-US' locale will have their filename with MM/DD/YYYY format, leading to the slashes being removed and ending up with 12312025. 'en-CA' provides dates in YYYY-MM-DD.

Update export file name format to force 'en-CA' locale

---

frontend/src/domains/DomainsPage.js
frontend/src/organizationDetails/OrganizationDomains.js

Updates Top 25 report and organization domains export buttons to use "en-CA" locale.

Update export button file names to use en-CA locale date format

---

k8s/infrastructure/bases/istio/istio-operator.yaml
k8s/infrastructure/bases/istio/platform/crds.yaml

Enabling native sidecars will allow jobs (and cronjobs) pods to reach the "Completed" state after the service is done running instead of staying "NotReady".

Enable native sidecars in istio operator configuration
