- web/Dockerfile
Switching to an Alpine based image, and running Pipenv inside. This
gives some nice deterministic builds but it's kinda big.
> Rework dockerfile

- web/cloudbuild.yaml
This commit fixes the directories since the build context is the repo
root.
> Fix cloudbuild

- web/track/templates/en/logout.html
- web/track/templates/en/sign-in.html
- web/track/templates/en/user-profile.html
- web/track/user_model.py
- web/track/views.py
- Added basic 'user-profile' html template and appropriate route.
- Updated 'user_model.py' to include two query functions for getting a specific user by either email or id from the Database.
- Implemented basic 'logout' html template that confirms a successful logout to the user.
- Required that a user be logged in to be able to access either the 'user-profile' route or the 'logout' route.
- Redirect a user to the 'user-profile' route if they try to access 'sign-in' while already logged in.
> Implemented Flask-login package for logging in users

- web/track/models.py
- web/track/templates/en/user-profile.html
- web/track/user_model.py
- web/track/views.py
This branch enables tracking failed login attempts. The functionality is dependent on two function calls in the user_model.py file (increment_failed_login_attempts & reset_failed_login_attempts). Any update to the schema simply requires changes to the user_models.py and not the views.py section of code.
Also adds basic data passing to reflect the currently logged in user on the user_profile template.
> Implement auth track failed login attempts

- web/Pipfile
- web/Pipfile.lock
- web/track/error_messages.py
- web/track/templates/en/new-password.html
- web/track/templates/en/reset-email-temp.html
- web/track/user_model.py
- web/track/views.py
Password reset completed minus the sending of emails, temp page in place
> Implement auth password reset

- web/track/views.py
Sets a default value of zero failed login attempts for newly registered users.
> Updated register function

- web/track/views.py
Notification api has been successfully tested with a new email template
> Password reset now includes email functionality

- web/Pipfile
- web/Pipfile.lock
- web/track/__init__.py
Compression is something we'll handle elsewhere, like the ingress edge
router.
> Don't handle compression in the app

- api/Pipfile
- api/Pipfile.lock
- api/app.py
Created initial files for graphql api, and associated pipfiles
> Graphql inital setup

- web/tests/test_routes.py
- web/tests/test_validators.py
Add the first round of unit tests to cover some of the  'implement-auth' functionality.
> Add unit tests for parts of Auth functionality

- api/Pipfile
- api/Pipfile.lock
- api/app.py
- api/schemas/user.py
Fixed some imports and got the app so it runs with `pipenv run server`.
> Get the app running with Waitress

- api/.dockerignore
- api/Dockerfile
- api/Pipfile
- api/Pipfile.lock
- api/cloudbuild.yaml
- api/tests/test_placeholder.py
This commit gets a CI pipeline going, but there is just a single
true==true test currently as a placeholder for the real deal.
> Build the api with cloudbuild

- api/app.py
- api/functions/input_validators.py
- api/models.py
- api/queries.py
- api/schemas/user.py
- Added error checking into the create user mutation
- Created signing in functionality, with error checking
- Added query property to all models to allow querying of each model
> Graph ql sign up in functions

- api/functions/error_messages.py
- api/schemas/user.py
- api/tests/test_placeholder.py
- api/tests/test_user_schema.py
This PR adds unit tests for password based api calls.
This PR also refactors error messages into their own functions file so that a single function can be used for both api code as well as testing code.
> Update Error Messages & Add unit tests

- frontend/jest.setup.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/Layout.js
- frontend/src/__tests__/App.test.js
This commit adds React Router and client side routing for just a single
route: /.
> Add react router

- platform/overlays/minikube/api-namespace.yaml
- platform/overlays/minikube/frontend-namespace.yaml
> Enable automatic sidecar injection

- api/functions/update_user_password.py
- api/schemas/user.py
This PR adds the ability to have the user returned to you after successfully updating their password.
> Update the API endpoint for updating user password.

- api/functions/error_messages.py
Simple PR to update invalid password error message.  Mostly a paper trail here!
> Update error message to reflect new password standards

- api/app.py
Uses port number ENV when connecting to DB.  To use local postgres with different port number!
> Use DB_PORT env when connecting to postgres

- api/functions/create_user.py
- api/functions/error_messages.py
Checks that email address is unique upon sign up, just a quick check to make sure email addresses in the DB are not repeated.
> Checks that email address is unique upon sign up

- platform/.flux.yaml
- platform/overlays/flux/bases/flux-account.yaml
- platform/overlays/flux/bases/flux-deployment.yaml
- platform/overlays/flux/bases/flux-namespace.yaml
- platform/overlays/flux/bases/flux-ns.yaml
- platform/overlays/flux/bases/flux-secret.yaml
- platform/overlays/flux/bases/kustomization.yaml
- platform/overlays/flux/bases/memcache-dep.yaml
- platform/overlays/flux/bases/memcache-svc.yaml
- platform/overlays/flux/kustomization.yaml
- platform/overlays/flux/patch.yaml
- platform/overlays/gke/cluster-admin-rolebinding.yaml
- platform/overlays/gke/kustomization.yaml
- platform/overlays/gke/tracker-api-deployment.yaml
- platform/overlays/gke/tracker-frontend-deployment.yaml
The goal here is getting continuous deployment working using flux.
Details about pull based deployments: https://alex.kaskaso.li/post/pull-based-pipelines
> Automate deployments with Flux

- .gitignore
- platform/.flux.yaml
- platform/overlays/flux/README.md
- platform/overlays/flux/kustomization.yaml
- platform/overlays/flux/patch.yaml
- platform/overlays/gke/.flux.yaml
- platform/overlays/gke/api.enc.env
- platform/overlays/gke/kustomization.yaml
- platform/overlays/gke/postgres.enc.env
This commit encrypts secrets with sops and decrypts those secrets during
manifest generation.
> Fix secret handling so manifest generation works

- api/functions/generate_enums.py
- api/model_enums/organiztions.py
- api/queries.py
- api/resolvers/organizations.py
- api/tests/test_groups_resolver.py
- api/tests/test_organizations_resolver.py
- api/tests/test_sector_resolver.py
- Created auto generation of enums with descriptions
- Implemented Organization enums, via auto generation
- Implemented Organizations initial resolvers 
- Fixed resolver tests to work with auto generation of enums through Azure
> Graphql organizations resolvers

- api/functions/create_user.py
- api/functions/error_messages.py
- api/functions/input_validators.py
- api/functions/sign_in_user.py
- api/functions/update_user_password.py
- api/functions/update_user_role.py
- api/functions/validate_two_factor.py
- api/resolvers/users.py
> Add doc strings where needed.

- api/queries.py
- api/resolvers/domains.py
- api/scalars/email_address.py
- api/scalars/url.py
- api/tests/test_domains_resolver.py
- Completed initial resolvers for domains
- Created test for initial domain resvolers
- Added domain resovlers into queries.py
- Fixed styling issues in url.py, and added new REGEX to find help reduce incorrect input
- Fixed styling issues in email_address.py
> GraphQL Domains Resolvers

- api/Pipfile
- api/cloudbuild.yaml
- api/functions/db_seeding/__init__.py
- api/functions/db_seeding/admin_affiliations.py
- api/functions/db_seeding/admins.py
- api/functions/db_seeding/ciphers.py
- api/functions/db_seeding/classification.py
- api/functions/db_seeding/dkim_scans.py
- api/functions/db_seeding/dmarc_scans.py
- api/functions/db_seeding/domains.py
- api/functions/db_seeding/groups.py
- api/functions/db_seeding/guidance.py
- api/functions/db_seeding/http_scans.py
- api/functions/db_seeding/organizations.py
- api/functions/db_seeding/scans.py
- api/functions/db_seeding/sectors.py
- api/functions/db_seeding/spf_scans.py
- api/functions/db_seeding/ssl_scans.py
- api/functions/db_seeding/user_affiliations.py
- api/functions/db_seeding/users.py
- api/manage.py
- api/tests/test_domains_resolver.py
- api/tests/test_groups_resolver.py
- api/tests/test_organizations_resolver.py
- api/tests/test_sector_resolver.py
- api/tests/test_that_migrations_have_a_single_revision_head.py
- Created new cli commands for inserting and removing data to postgres
- Created new directory and files to put data for inserts
- Functions added into manage.py, in an order that complies with constraints of the db, may have to be changed if models.py is changed and new constraints are added
> Flask migrate seeding data

- frontend/src/TopBanner.js
- frontend/src/__tests__/TopBanner.test.js
- frontend/src/locales/en.po
- frontend/src/locales/fr.po
This commit makes better use of Lingui to simplify the component.
> Refactor TopBanner alt text handling

- api/queries.py
- api/resolvers/organizations.py
- api/resolvers/scans.py
- api/schemas/user.py
- api/tests/test_scans_resolver.py
- Initial Scan Resovlers
- Testing for Scan Resolvers
> Graphql resolvers scans

- frontend/src/App.js
- frontend/src/TopBanner.js
This commit drops unused props, and removes dependency on the Layout component.
> Simplify TopBanner component

- frontend/package-lock.json
- frontend/package.json
- frontend/src/setupTests.js
This commit removes some cruft from the test setup, and adds the missing
jest-emotion library.
> Lint clean

- api/resolvers/users.py
- api/tests/test_user_roles.py
Updated relevant test to reflect the change also.
> Update resolvers/users.py to raise a graphql error.

- frontend/package-lock.json
- frontend/package.json
- frontend/schema.faker.graphql
- frontend/src/TwoFactorPage.js
- frontend/src/components/SignInPage/TwoFactorPage.js
This PR adds a component for verifying an OTP code.
* Uses Formik for form handling, field validator requires the input be a 6 digit string only.
* Uses a very nice & pretty lock Icon
Use the following tag to add the component to a in routing section.
`<TwoFactorPage/>`
> Enter two factor code component

- frontend/src/App.js
- frontend/src/QRcodePage.js
- frontend/src/components/QRcodePage/QRcodePage.js
Component takes a url prop that defines what the QRcode module will generate.
* Uses the [qrcode.react](https://www.npmjs.com/package/qrcode.react) package from npm to generate the actual QR code based on a URL.
To use the component,  import it from `components/QRcodePage/QRcodePage` and the include it by adding the tag:
```<QRcodePage url={"https://google.ca"}/>```
To your file!  :D
> Add QRcodePage component

- api/functions/auth_functions.py
- api/functions/update_user_role.py
- api/resolvers/user_affiliations.py
- api/tests/test_auth_functions.py
Just switching to using the org_id instead of org to pass into auth check functions
> Update auth functionality to use org_id for checking roles

- frontend/package-lock.json
- frontend/package.json
- frontend/src/SignInPage.js
- frontend/src/TwoFactorPage.js
- frontend/src/__tests__/TwoFactorPage.test.js
This PR adds tests for the TwoFactorPage
This PR updates the 'prettier' format of the files included.
> Test TwoFactorPage and prettify

- frontend/package-lock.json
- frontend/package.json
- frontend/schema.faker.graphql
- frontend/src/App.js
- frontend/src/CreateUserPage.js
- frontend/src/QRcodePage.js
- frontend/src/__tests__/QRcodePage.test.js
This PR enables the QRcode component to be loaded based on a generated URL from the back end.
* Adds faker data to the query responsible for the functionality.
* username is a prop passed into component -- This user name is what the backend takes to generate the url.
* Adds test to ensure that component renders correctly
> QRcode generated via GQL backend & Test

- frontend/package-lock.json
- frontend/package.json
- frontend/src/SignInPage.js
- frontend/src/__tests__/SignInPage.test.js
This PR adds Tests for SignInPage component as well as updates code format and linting issues.
> Update SignIn component and add Tests

- platform/overlays/gke/publicgateway.yaml
This commit adds proper TLS options to the public gateway object.
> Better TLS settings

- frontend/src/Server.js
- frontend/src/__tests__/Server.test.js
> Remove x-powered-by header

- frontend/src/App.js
> Display toast when signout button is clicked

- frontend/src/CreateUserPage.js
- frontend/src/__tests__/CreateUserPage.test.js
Uses ChakraUI toast instead of rendering new text elements and buttons.
* Removes test that is no longer relevant
> Use toast for creation confirmation

- frontend/src/SignInPage.js
* Add toast for successful sign in
* Add toast for sign in errors
> Add toasts to sign in page

- frontend/src/__tests__/TwoFactorNotificationBar.test.js
> Update test name -- Fix copy&paste typo!

- api/queries.py
- api/scalars/organization_acronym.py
- api/schemas/organizations.py
- api/schemas/organizations_mutations.py
- api/schemas/user_affiliations.py
- api/tests/test_auth_wrapper.py
- api/tests/test_domains_resolver_access_control.py
- api/tests/test_organization_resolver_access_control.py
- api/tests/test_organization_resolver_values.py
- api/tests/test_user_roles.py
- api/tests/test_users_access_control.py
- api/tests/test_users_values.py
:tada: Now we can create organizations through the API !!! :tada: 
- Created mutations that will allow the creation and modification of organizations.
- Created new scalar for organization acronyms to replace the enums
- Refactored all instances of organization enums
- Removed references to organization enums, as final decision will be made to bring them back or to leave them out.
> Let's Create Some Organizations Folks!

- frontend/src/CreateUserPage.js
> Add Icons to input fields on createuserpage

- api/functions/input_validators.py
- api/queries.py
- api/schemas/organizations.py
- api/schemas/organizations_mutations.py
- api/tests/test_organization_mutations.py
- api/tests/test_organization_resolver_values.py
Removing organizations have been brought to life in this PR :tada: 
- Mutation for removing organizations and all related information (Affiliations, Domains, Scans, etc.)
- Testing for all Organization Mutations
- Minor Bug Fixes
> Adding More Organizational Mutations

- api/queries.py
- api/schemas/domains_mutations.py
- api/tests/test_domains_mutations.py
Domain Mutations Are Finally Here :tada: 
- Create, Update, and Remove Domains
- Testing for all mutation functionality, and access control
> Domain Mutation Time

- api/functions/auth_functions.py
- api/functions/update_user_role.py
- api/resolvers/domains.py
- api/resolvers/organizations.py
- api/resolvers/user.py
- api/resolvers/user_affiliations.py
- api/resolvers/users.py
- api/schemas/domains_mutations.py
- api/schemas/organizations_mutations.py
- api/tests/test_auth_functions.py
Slight re-work of how the super admin check works, allowing for easier auth checks in various functions.
> Fixing Super Admin Checks

- frontend/src/CreateUserPage.js
- frontend/src/PasswordConfirmation.js
- frontend/src/__tests__/CreateUserPage.test.js
- frontend/src/__tests__/PasswordConfirmation.test.js
* Refactors out password and confirmPassword into new component
* Updates validator functions
* Adds icon 'animations' to the create-user component
* Adds tests for new component
_Note: I do not love the double conditional in the validator that handles the state and error messages.  Let me know if you see a better way! :smile:_
> Create user passwords component

- frontend/src/CreateUserPage.js
- frontend/src/EmailField.js
- frontend/src/__tests__/CreateUserPage.test.js
- frontend/src/__tests__/EmailField.test.js
- frontend/src/locales/en.po
- frontend/src/locales/fr.po
This commit continues the process of breaking down the CreateUserPage by
extracting an EmailField component.
> Extract EmailField component from CreateUserPage

- frontend/schema.faker.graphql
This PR fixes an accidental addition in the faker file.
> Fix schema faker

- frontend/schema.faker.graphql
- frontend/src/DmarcReportPage.js
- frontend/src/__tests__/DmarcReportPage.test.js
- frontend/src/graphql/queries.js
- Update file and tests to use new types.
- Move type to graphql/queries file.
> Create Custom type and sub-types for dmarc report page.

- frontend/src/__tests__/App.test.js
- frontend/src/__tests__/CreateUserPage.test.js
- frontend/src/__tests__/QRcodePage.test.js
- frontend/src/__tests__/SignInPage.test.js
- frontend/src/__tests__/TwoFactorPage.test.js
This commit removes the last traces of our use of Apollo's local state from our
tests.
> Remove remnants of local state

- frontend/src/__tests__/App.test.js
- frontend/src/__tests__/SignInPage.test.js
- frontend/src/graphql/queries.js
This commit updates the query to get a list of domains. For some reason this
was never updated when we change the api so visiting this page always threw an
error. No longer!
> Fix domains query

- api/scalars/email_address.py
- api/scalars/url.py
- api/tests/test_email_address_scalar.py
- api/tests/test_organization_acronym_scalar.py
- api/tests/test_url_scalar.py
Just a quick fix for a return type, adding in some more tests for some scalars, and switching tabs to spaces
> Quick Update To GraphQL Scalars

- frontend/src/DmarcReportPage.js
- frontend/src/DomainsPage.js
- frontend/src/__tests__/DmarcReportPage.test.js
This commit sets and authorization header along with requests for Domains and
Dmarc reports.
> Send bearer token with api requests

- frontend/package-lock.json
- frontend/package.json
- frontend/src/Server.js
This was inexplicably missing after the jump from CRA to the new setup. 🤦
> Add missing express dependency

- api/json_web_token.py
- api/tests/test_json_web_token.py
This function puts the logic for creating jwts in one place. This isn't used in the codebase just yet but will be in followup commits.
> Add function for creating jwt

- api/json_web_token.py
This commit adds an auth_header function to the json_web_token module. This
function is an extraction of the auth header creation logic that was duplicated
throughout the tests.
> Add auth_header function

- frontend/.eslintrc
- frontend/src/SignInPage.js
- frontend/src/UserList.js
- frontend/src/UserPage.js
- frontend/src/UserState.js
- frontend/src/__tests__/UserState.test.js
- frontend/src/__tests__/client.test.js
This commit fixes all the linting errors that resulted from our lack of linting
in CI during the "create-react-app" days.
> Get code linting clean

- api/functions/sign_in_user.py
This commit uses the tokenize function and the hybrid roles property that was
added to the Users model and uses them to simplify the sign_in_user function.
With users now getting an organization added by default there is no longer a
"user has no roles" case so this code isn't needed.
Everything else is functionally equivalent, with the sole exception that the
tokenize function generates tokens valid for  1 hour by default.
> Simplify the sign_in_user function

- platform/overlays/flux/patch.yaml
This commit reduce the cpu resources for flux which had been raised while
trying to debug deployment issues.
> Reduce cpu resource claims for flux

- frontend/src/DomainsPage.js
- frontend/src/__tests__/DomainsPage.test.js
As advertised, this adds more fulsome error handling to the DomainsPage.
> Handle jwt/other errors for DomainsPage

- frontend/src/UserPage.js
> Add auth token to UserPage queries

- frontend/src/App.js
- frontend/src/RouteIf.js
- frontend/src/__tests__/RouteIf.test.js
This commit fixes the RouteIf component so that it properly updates the Routes.
> Fix routeif component

- frontend/src/UserList.js
- frontend/src/__tests__/UserList.test.js
This commit includes the jwt token along with the UserList query.
> Add auth token to userlist query

- frontend/src/UserList.js
- frontend/src/__tests__/UserList.test.js
- frontend/src/graphql/queries.js
- frontend/src/slugify.js
This commit updates the graphql query from the UserList to work with the
current API schema.
> Fix UserList query

- api/functions/verification_email.py
- api/tests/test_send_verification_email_function.py
- api/tests/test_sign_up.py
Just a few fixes to remove talks with the Notifications API. There is a few more tests using notification, however they will require more direct fixes which will be fixed shortly.
> Fix notification test errors

- platform/overlays/gke/.flux.yaml
- platform/overlays/gke/flux-patch.yaml
This commit adds a strategic merge patch for flux to use to update the
generated manifests with.
> Switch flux from commandUpdated to patchUpdated

- platform/overlays/gke/.flux.yaml
Add missing version, remove extra patchUpdated.
> Fix flux config

- scanners/dispatcher/cloudbuild.yaml
- scanners/dkim/cloudbuild.yaml
- scanners/dmarc/cloudbuild.yaml
- scanners/https/cloudbuild.yaml
- scanners/results/cloudbuild.yaml
- scanners/ssl/cloudbuild.yaml
Update cloudbuild paths within each scanner's cloudbuild.yaml
> Update cloudbuild path

- frontend/src/App.js
A missing import statement was all that was standing in the way.
> Add missing import to get QRCodePage displaying

- api/db.py
Quick possible fix for db issues
> Add pool_pre_ping check

- platform/overlays/gke/knative/config/config.yaml
- scanners/dispatcher/Dockerfile
- scanners/dispatcher/cloudbuild.yaml
- scanners/dispatcher/requirements.txt
- scanners/dkim/Dockerfile
- scanners/dkim/cloudbuild.yaml
- scanners/dkim/requirements.txt
- scanners/dmarc/Dockerfile
- scanners/dmarc/cloudbuild.yaml
- scanners/dmarc/requirements.txt
- scanners/https/Dockerfile
- scanners/https/cloudbuild.yaml
- scanners/https/requirements.txt
- scanners/results/Dockerfile
- scanners/results/cloudbuild.yaml
- scanners/results/requirements.txt
- scanners/ssl/Dockerfile
- scanners/ssl/cloudbuild.yaml
- scanners/ssl/requirements.txt
Knative was not seeing Scanner services as "Ready" and were stuck in a constant state of "Deploying". The implementation of gunicorn with uvicorn workers for ASGI resolves this.
> Gunicorn uvicorn workers

- api/schemas/dmarc_report_bar_graph/resolver.py
- api/schemas/shared_structures/detail_tables/table_structure.py
- api/tests/testdata/get_dmarc_report_bar_graph/get_dmarc_report_bar_graph_data.py
Small fix for updating queries to match update to dmarc-report-api
> Update dmarc report api queries

- frontend/schema.faker.graphql
- frontend/src/Domain.js
- frontend/src/DomainList.js
- frontend/src/DomainsPage.js
- frontend/src/__tests__/Domain.test.js
- frontend/src/__tests__/DomainList.test.js
- frontend/src/__tests__/DomainsPage.test.js
- frontend/src/graphql/queries.js
This commit breaks down the domains page by extracting some smaller components
from it and modifies the graphql query to fetch domains via the organization.
There are some weird workarounds in here that will be removed in a followup
commit after some of the api stuff is improved.
> Rework domains page

- api/functions/fire_scan.py
- scanners/dispatcher/dispatcher.py
- scanners/dispatcher/tests/test_dispatcher.py
- scanners/dispatcher/utils.py
- scanners/results/result_processor.py
Amendment to database insertions and dispatcher functionality
> Scanner fix

- api/schemas/authenticate/sign_in_user.py
- api/schemas/sign_up/create_user.py
This may fix the issue when creating an account
> Don't query the db again for information we already have

- frontend/src/SummaryCard.js
- frontend/src/SummaryGroup.js
- frontend/src/SummaryTable.js
- frontend/src/makeSummaryTableData.js
Just what it says on the tin. Doing away with unused vars and adding keys where needed.
> Clean up linting errors

- frontend/cloudbuild.yaml
This commit adds a linting step to out CI process to catch unused vars and
other badness.
> Add linting to CI

- api/.pre-commit-config.yaml
- api/Pipfile
- api/Pipfile.lock
- api/README.md
- Moved things around to ensure that they are only being installed for dev purposes. 
- Added in `pre-commit` so that all files are forcefully ran through black so we don't miss any. 
- Updated main API README to reflect changes.
- Dependencies Updated
> Cleaning Up API Dependencies

- api/db.py
Just adding back in this check
> Add back missing pool_pre_ping check

- platform/bases/istio.yaml
- platform/overlays/gke/istio.yaml
This commit fixes the mismatching istio config that was messing up kustomize.
> Fix istio config

- platform/bases/istio.yaml
- platform/overlays/gke/istio.yaml
Exactly what it says on the tin.
> Update to istio 1.6.2

- api/schemas/organizations.py
- api/tests/test_organization_resolver_access_control.py
- api/tests/test_organization_resolver_values.py
Just simply running black on the API code-base again ...
> Running Black

- frontend/src/ListOf.js
- frontend/src/__tests__/ListOf.test.js
This component builds in some error handling and provides a clean interface for
rendering lists, simplifying work which we are doing a fair bit throughout the
app. This component will be used in a follow up commit.
> Add ListOf component

- frontend/src/DmarcReportPage.js
- frontend/src/__tests__/DmarcReportPage.test.js
> Fix dmarc report page (bad slug)

- frontend/src/DmarcReportPage.js
- frontend/src/__tests__/DmarcReportPage.test.js
> Fix dmarc report page (bad slug still)

- frontend/src/DmarcReportSummaryGraph.js
> Fix summary page graph sorting in firefox

- api/models/Domains.py
- api/models/Organizations.py
- api/models/__init__.py
- api/schemas/organizations.py
- api/tests/test_findOrganizationDetailsBySlug.py
- api/tests/test_organizations.py
This commit adds a domain_count method to the Organization model and exposes it
in the API via the OrganizationDetail type.
> Add OrganizationDetail.domainCount field

- services/scanners/dispatcher/cloudbuild.yaml
- services/scanners/dns/cloudbuild.yaml
- services/scanners/https/cloudbuild.yaml
- services/scanners/results/cloudbuild.yaml
- services/scanners/ssl/cloudbuild.yaml
Cloudbuild updates to support recent scanner/service directory restructuring
> Update cloudbuild.yaml for each scanner to reflect changes

- api/schemas/request_scan/fire_scan.py
Fixing the little things, so we can move onto bigger and brighter things!
> More fixes to scan mutation

- frontend/src/Domain.js
- frontend/src/sanitizeUrl.js
This commit actions the advice of this article to sanitize our domains for
display to prevent XSS:
https://pragmaticwebsecurity.com/articles/spasecurity/react-xss-part1.html
> Sanitize urls for display

- frontend/src/DmarcReportPage.js
- frontend/src/DmarcReportTable.js
This commit fixes some multiple import warnings that turned up in linting.
> Clean up imports

- frontend/src/AdminDomains.js
- frontend/src/AdminPage.js
- frontend/src/AdminPanel.js
- frontend/src/App.js
- frontend/src/Domain.js
- frontend/src/DomainsPage.js
- frontend/src/Navigation.js
- frontend/src/Organizations.js
- frontend/src/UserCard.js
- frontend/src/UserList.js
- frontend/src/UserPage.js
- frontend/src/__tests__/AdminDomains.test.js
- frontend/src/__tests__/AdminPage.test.js
- frontend/src/__tests__/AdminPanel.test.js
- frontend/src/__tests__/App.test.js
- frontend/src/__tests__/UserList.test.js
- frontend/src/graphql/queries.js
- frontend/src/locales/en.po
- frontend/src/locales/fr.po
- Created admin page that includes lists of domains and users in a given organisation
- Ability to add/remove domains and users
- Navbar link only appears if current user is admin or super admin of one or more orgs
> Add Admin Page

- services/db-migration/cloudbuild.yaml
Fix cloudbuild.yaml for db-migration
> Fix cloudbuild.yaml for db-migration

- api/schemas/shared_structures/domain/mail_scan/spf.py
Small fix to make sure error doesn't occur when trying to access a none valued variable.
> Add check to see if dkim_orm is none

- frontend/schema.faker.graphql
> Add enums for faking guidance tags

- frontend/src/AdminPage.js
- frontend/src/App.js
- frontend/src/SignInPage.js
- frontend/src/UserList.js
- frontend/src/__tests__/AdminPage.test.js
- frontend/src/__tests__/App.test.js
- frontend/src/graphql/queries.js
- frontend/src/locales/en.po
- frontend/src/locales/fr.po
Fix for graphql error on cluster:
- moved UserAffiliations query from App.js to AdminPage.js
- made some cosmetic changes to UserList, added translations
> GraphQL, AdminPage error fix

- frontend/src/AdminDomains.js
- frontend/src/AdminPage.js
- frontend/src/__tests__/AdminPage.test.js
- frontend/src/__tests__/AdminPanel.test.js
This commit adds the missing authorization header so that the query succeeds.
> Fix Graphql query on Admin page

- frontend/src/Organization.js
- frontend/src/Organizations.js
- frontend/src/__tests__/Organizations.test.js
Cleaning up some misc log statements.
> Remove leftover console.log statements

- frontend/package-lock.json
- frontend/package.json
Pulling in Recharts 2 beta here, in order to silence a tonne of warnings that
have been plaguing us... the dreaded "Warning: componentWillReceiveProps has
been renamed, and is not recommended for use" that is littering out test
output.
> Update to Recharts 2

- api/schemas/create_domain/create_domain.py
- api/tests/test_createDomain_mutation.py
- frontend/schema.faker.graphql
Updating mutation to use an input object rather than normal arguments, all tests passing, and faker has been updated.
> Use Input Object for CreateDomain

- api/tests/test_find_my_organizations.py
- api/tests/testdata/find_my_organizations/__init__.py
- api/tests/testdata/find_my_organizations/org_admin_return_data.py
- api/tests/testdata/find_my_organizations/super_admin_return_data.py
- api/tests/testdata/find_my_organizations/user_read_return_data.py
- api/tests/testdata/find_my_organizations/user_write_return_data.py
Just adds in some extra return data structures to account for randomness in the return data, this should stop the tests from failing in those cases
> Adding extra expected return data to fix tests failing

- api/schemas/shared_structures/domain/__init__.py
- api/schemas/shared_structures/domain/mail_scan/__init__.py
- api/schemas/shared_structures/domain/web_scan/__init__.py
- api/schemas/shared_structures/organization_detail.py
- api/schemas/shared_structures/organizations.py
- api/schemas/user_page/user_page.py
This is a quick PR fixing issues with python's `return` functionality not actually executing the line of code following and returning more things it shouldn't.
> Fix for things returning things they shouldn't

- api/schemas/create_organization/create_organization.py
- api/tests/test_createOrganization_mutation.py
- frontend/schema.faker.graphql
Update to createOrganization to use an input object rather than the standard arguments. Faker has also been updated.
> Use Input Object for CreateOrganization

- api/schemas/shared_structures/domain/__init__.py
Quick fix to ensure proper ordering of return results, so that the most up to date data is returned to the front end.
> Quick Fix for ensuring data is returned in proper order.

- api/schemas/shared_structures/domain/mail_scan/spf.py
Just missed another `if not None` check
> Another spf guidance tag fix

- api/schemas/dmarc_report_summary/__init__.py
- api/schemas/dmarc_report_summary/resolver.py
- api/schemas/dmarc_report_summary_list/__init__.py
- api/schemas/dmarc_report_summary_list/resolver.py
- api/tests/test_dmarc_report_summary.py
- api/tests/test_dmarc_report_summary_list.py
- frontend/schema.faker.graphql
- frontend/src/graphql/queries.js
Updating `dmarcReportSummary` and `dmarcReportSummaryList` queries, and they're respective demo queries. All tests updated, and front-end queries and faker also updated.
> Dmarc report summary and list convert to input object

- api/schemas/shared_structures/category_totals.py
- api/schemas/shared_structures/detail_tables/__init__.py
- api/schemas/shared_structures/detail_tables/table_structure.py
- api/schemas/shared_structures/domain/__init__.py
- api/schemas/shared_structures/domain/mail_scan/__init__.py
- api/schemas/shared_structures/domain/mail_scan/dkim.py
- api/schemas/shared_structures/domain/mail_scan/dmarc.py
- api/schemas/shared_structures/domain/mail_scan/spf.py
- api/schemas/shared_structures/domain/web_scan/__init__.py
- api/schemas/shared_structures/domain/web_scan/https.py
- api/schemas/shared_structures/domain/web_scan/ssl.py
- api/schemas/shared_structures/organization_detail.py
- api/schemas/shared_structures/organizations.py
- api/schemas/user/user.py
- api/schemas/user_affiliations.py
- api/schemas/user_list/user_list_item.py
- api/schemas/user_page/user_page.py
- api/schemas/users.py
Adding kwargs to resolvers to soak up extra variables being passed in for relay, and adding extra none checks in guidance tags generation.
> Fixing relay sub item filters breaking

- services/scanners/dispatcher/Dockerfile
- services/scanners/dns/Dockerfile
- services/scanners/https/Dockerfile
- services/scanners/results/Dockerfile
- services/scanners/ssl/Dockerfile
As the title suggests, these changes update the ASGI implementation to facilitate faster scanning.
> Scanners - Increase worker count, thread count, timeout

- frontend/schema.faker.graphql
Updating Faker once again to match new DKIM structure, and to rip out old dmarc report stuff.
> Another faker update once again

- scripts/README.md
- scripts/insert_csv.py
Addition of insert_csv script and corresponding directory structure.
> Addition of "Scripts" sub-directory

- frontend/schema.faker.graphql
- frontend/src/DmarcReportPage.js
- frontend/src/SummaryCard.js
- frontend/src/SummaryGroup.js
- frontend/src/SummaryTable.js
- frontend/src/__tests__/DmarcReportPage.test.js
- frontend/src/__tests__/SummaryCard.test.js
- frontend/src/fixtures/summaryCardData.js
- frontend/src/graphql/queries.js
- frontend/src/locales/en.po
- frontend/src/locales/fr.po
- frontend/src/theme/canada.js
This commit reworks and simplifies the SummaryCard component and extracts an
API from the test data will be exposed via GraphQL in a subsequent PR.
For now, the test data is still in place, but using the new structure.
> Refactor SummaryCard component

- api/queries.py
- api/schemas/update_domain/update_domain.py
- api/schemas/update_organization/update_organization.py
- api/tests/test_updateDomain_mutation.py
- api/tests/test_updateOrganization_mutation.py
- frontend/schema.faker.graphql
More input objects updates to the API, this time its for `updateDomain` and `updateOrganization`
> Update mutations getting the input object treatment

- api/schemas/email_verify_account/email_verify_account.py
- api/tests/test_email_verify_account.py
- frontend/schema.faker.graphql
Updating `emailVerifyAccount` to use an input object rather than plain old arguments
> Email verify account convert to input object

- api/functions/external_graphql_api_request.py
This was supposed to have been completed a while ago, however it got sorta lost, and I got busy working on other things, well its better late than never.
> Veryifying Domains for External API Calls

- api/schemas/dmarc_report_detail_tables/__init__.py
- api/schemas/dmarc_report_detail_tables/resolver.py
- api/schemas/dmarc_report_summary/__init__.py
- api/schemas/dmarc_report_summary/resolver.py
- api/schemas/dmarc_report_summary_list/__init__.py
- api/schemas/dmarc_report_summary_list/resolver.py
- api/tests/test_dmarc_report_summary.py
- api/tests/test_dmarc_report_summary_list.py
- api/tests/testdata/dmarc_report_detail_table/dmarc_report_table_query.py
- frontend/schema.faker.graphql
- frontend/src/graphql/queries.js
Removing input objects from queries, as it makes them more complex for no apparent reason.
> Anti input treatment on queries

- api/functions/auth_wrappers.py
- api/functions/verification_email.py
- api/json_web_token.py
- api/schemas/authenticate/sign_in_user.py
- api/schemas/email_verify_account/email_verify_account.py
- api/schemas/sign_up/create_user.py
- api/tests/test_email_verify_account.py
- api/tests/test_functions/run_query.py
- api/tests/test_json_web_token.py
This is a small PR just switching up the JWT a little bit to make it a little more versatile in different use cases, coming soon<sup>TM</sup>
> New Parameters Dict in the JWT

- frontend/src/Navigation.js
> Stop nav elements from wrapping at whitespace

- api/tests/test_find_my_organizations.py
- api/tests/testdata/find_my_organizations/super_admin_return_data.py
> Another x2 findMyOrg test

- platform/bases/postgres-deployment.yaml
Alter postgres-deployment.yaml to improve availability and stability of postgres cluster at peak traffic load
> Postgres Deployment Amendment

- frontend/package-lock.json
- frontend/package.json
Waiting for prettier/vim-prettier#238
> Downgrade prettier

- frontend/src/LandingPage.js
- frontend/src/SummaryCard.js
- frontend/src/SummaryGroup.js
This commit further simplifies the SummaryCard component and some of the
containing components to fix some weird rendering in both Firefox (weirdly
big), and Chrome (one too big, the other is fine).
> Fix SummaryCard component rendering

- frontend/src/Organizations.js
- frontend/src/__tests__/Organizations.test.js
This commit fixes the "Each child in a list should have a unique "key" prop."
warning we were getting when running the tests
> Fix React key error

- api/schemas/update_user_role/update_user_role.py
- frontend/schema.faker.graphql
> Forgot to include updateUserRole mutation in frontend faker

- api/queries.py
- api/schemas/update_user_profile/__init__.py
- api/schemas/update_user_profile/update_user_profile.py
- api/tests/test_update_user_profile_mutation.py
- frontend/schema.faker.graphql
Thought this already existed, apparently not. Soooooooooo here it is, you can update your user name, display name, preferred language, and your password all at once.
> Update User Profiles

- api/schemas/authenticate/sign_in_user.py
- api/schemas/sign_up/create_user.py
> Fixing create user and sign in user name issue

- frontend/package-lock.json
- frontend/package.json
> Update prettier to 1.19.1

- frontend/src/UserCard.js
- frontend/src/UserList.js
- frontend/src/__tests__/AdminPanel.test.js
This commit fixes a test whose test data had gotten out of sync and was failing
the build.
> Fix failing AdminPanel test

- frontend/package-lock.json
- frontend/package.json
- frontend/src/client.js
This commit removes a bunch of dependencies obsoleted by the update to Apollo
Client 3.
> Clean up Apollo dependencies

- frontend/src/Organizations.js
- frontend/src/__tests__/Organizations.test.js
This commit fixes up a flaky test and resolves minor bugs with the pagination
of Organizations.
> Fix Organizations pagination tests

- frontend/src/UserList.js
This is a little commit that swaps Text for a proper FormLabel component.
> Replace Text with FormLabel in UserList

- scripts/insert_csv.py
> Slugification of the slugs (.csv insertion)

- frontend/schema.faker.graphql
- frontend/src/AdminDomains.js
- frontend/src/AdminPanel.js
- frontend/src/__tests__/AdminDomains.test.js
- frontend/src/fieldRequirements.js
- frontend/src/graphql/mutations.js
- frontend/src/locales/en.po
- frontend/src/locales/fr.po
Bonus PR to hook up domain components in the admin portal. Enables users to:
- Add new domain
- Remove domain
- Update domain
> Frontend hook up domain mutations

- frontend/src/AdminDomains.js
- frontend/src/__tests__/AdminDomains.test.js
- frontend/src/locales/en.po
- frontend/src/locales/fr.po
> Fix mutation calls for domains on admin portal (missing auth)

- frontend/src/AdminDomains.js
> Fix mutations for domains in admin portal (missing selector variables)

- frontend/src/DmarcReportTable.js
- frontend/src/SummaryCard.js
> Use blue consistently

- frontend/src/ForgotPasswordPage.js
- frontend/src/QRcodePage.js
- frontend/src/SignInPage.js
- frontend/src/SummaryCard.js
- frontend/src/TopBanner.js
- frontend/src/TrackerButton.js
- frontend/src/TwoFactorPage.js
- frontend/src/UserCard.js
This commit finishes the job started previously in stamping out all the
blue.900's and replacing them with "primary". This lets us set the color of our
app by changing a single variable in the theme.
> Use primary instead of blue.900

- platform/overlays/gke/knative/monitoring/grafana/dashboard.config
- platform/overlays/gke/knative/monitoring/prometheus.yaml
Overhaul of Grafana dashboard for backend logging/monitoring.
> Grafana Dashboard Update

- api/functions/external_graphql_api_request.py
- api/schemas/dmarc_report_detail_tables/resolver.py
- api/schemas/dmarc_report_summary/resolver.py
- api/schemas/dmarc_report_summary_list/resolver.py
- api/schemas/dmarc_report_summary_table/resolver.py
I have a slight feeling that the problem that we have been facing with the dmarc-report-api is due to missing secrets. I have since added these secrets and restarted the pod, however the secrets are not being pulled. I am hoping this will force them to get pulled.
> Try to get pod to pull secrets

- platform/overlays/gke/knative/monitoring/README.md
- platform/overlays/gke/knative/monitoring/loki-stack.yaml
- platform/overlays/gke/kustomization.yaml
Changes include the addition of a brief tutorial outlining the steps required to set up the application's backend monitoring system and dashboard with the provided configuration.
> Monitoring Documentation

- platform/overlays/gke/knative/config/autoscan.yaml
Update to autoscan manifest to perform scans twice daily.
> Scan once every 12 hours

- api-js/src/__tests__/check-permission.test.js
- api-js/src/auth/check-permission.js
Handle cursor errors within auth function and reflect behaviour within tests.
> Check-permission cursor error handling + tests

- api-js/src/__tests__/create-domain.test.js
- api-js/src/__tests__/find-domain-by-domain.test.js
- api-js/src/__tests__/load-domain-by-domain.test.js
- api-js/src/__tests__/update-domain.test.js
- api-js/src/loaders/domains/index.js
- api-js/src/loaders/domains/load-domain-by-domain.js
- api-js/src/loaders/index.js
- api-js/src/mutations/domain/create-domain.js
- api-js/src/mutations/domain/update-domain.js
- api-js/src/queries/domains/find-domain-by-domain.js
- api-js/src/queries/domains/index.js
- api-js/src/server.js
- api-js/src/types/base/index.js
Getting rid of those pesky domain slugs in favour of just using the domain itself
> Refactor find domain by slug query

- platform/bases/istio.yaml
- platform/overlays/gke/istio.yaml
- platform/overlays/gke/jaeger.yaml
- platform/overlays/gke/kiali.yaml
These changes bring us to Istio 1.7!
Notable changes include an overhaul of the way addon components work. Thus, rather than generating istio.yaml with Kiali/Jaeger enabled, they have been added into `platform/overlays/gke` as individual manifests. 
[More info here](https://istio.io/latest/news/releases/1.7.x/announcing-1.7/change-notes/)
> Istio 1.7 update

- api-js/src/__tests__/find-my-domains.test.js
- api-js/src/__tests__/load-domains-connections-by-user-id.test.js
- api-js/src/loaders/domains/index.js
- api-js/src/loaders/domains/load-domain-connections-by-user-id.js
- api-js/src/queries/domains/find-my-domains.js
- api-js/src/server.js
These changes introduce the find-my-domains query and load-domain-connections-by-user-id loader to the in-progress JavaScript API.
> Implementation of 'Find my domains' query and underlying loader

- api-js/src/__tests__/find-organization-by-slug.test.js
- api-js/src/__tests__/update-domain.test.js
- api-js/src/locale/en/messages.js
- api-js/src/locale/fr/messages.js
- api-js/src/queries/organizations/find-organization-by-slug.js
- api-js/src/server.js
Adds org slug querying to the JS API. Tests included + ran prettier
> Implementation of find-organization-by-slug query

- api-js/src/__tests__/create-organization.test.js
- api-js/src/__tests__/remove-organization.test.js
- api-js/src/__tests__/update-organization.test.js
- api-js/src/locale/en/messages.js
- api-js/src/locale/en/messages.po
- api-js/src/locale/fr/messages.js
- api-js/src/locale/fr/messages.po
- api-js/src/mutations/organizations/create-organization.js
- api-js/src/mutations/organizations/remove-organization.js
- api-js/src/mutations/organizations/update-organization.js
> Organization mutations translations

- frontend/src/SignInPage.js
Corrects the forgot password link width from 100% to "fit-content"
> Fix forgot password link width

- api-js/src/__tests__/is-user-admin.test.js
- api-js/src/loaders/organizations/load-organization-connections-by-user-id.js
- api-js/src/queries/index.js
- api-js/src/queries/user/is-user-admin.js
Implementation of is-user-admin query and associated tests.
> is-user-admin

- api-js/src/__tests__/notify-send-authenticate-email.test.js
- api-js/src/__tests__/notify-send-authenticate-text-msg.test.js
- api-js/src/__tests__/notify-send-org-invite-create-account.test.js
- api-js/src/__tests__/notify-send-org-invite-email.test.js
- api-js/src/__tests__/notify-send-password-reset-email.test.js
- api-js/src/__tests__/notify-send-tfa-text-msg.test.js
- api-js/src/__tests__/notify-send-verification-email.test.js
- api-js/src/locale/en/messages.js
- api-js/src/locale/en/messages.po
- api-js/src/locale/fr/messages.js
- api-js/src/locale/fr/messages.po
- api-js/src/notify/notify-send-authenticate-email.js
- api-js/src/notify/notify-send-authenticate-text-msg.js
- api-js/src/notify/notify-send-org-invite-create-account.js
- api-js/src/notify/notify-send-org-invite-email.js
- api-js/src/notify/notify-send-password-reset-email.js
- api-js/src/notify/notify-send-tfa-text-msg.js
- api-js/src/notify/notify-send-verification-email.js
- api-js/src/server.js
> API Notify Function Translations

- api/Pipfile.lock
Updating the old api to keep it current
> Python API Updates

- frontend/package-lock.json
> Update node-forge dependency.

- frontend/src/CreateUserPage.js
> Fix userOrgToken variable not found on sign up

- frontend/package-lock.json
- frontend/package.json
> Updating Supertest to 5.0.0

- api-js/src/__tests__/is-user-admin.test.js
Little fix with this test as it was leaving behind empty db's in arango
> Is user admin test fix

- api-js/Dockerfile
switch Dockerfile to use latest
> Use node:alpine latest in JS API

- platform/overlays/flux/bases/flux-deployment.yaml
> Update to flux 1.21.0

- api-js/src/loaders/domains/load-domain-connections-by-organizations-id.js
- api-js/src/loaders/domains/load-domain-connections-by-user-id.js
Just a quick fix to the connection loader to switch up the if statement format
> Domain connection loader small fix

- platform/bases/knative/config/autoscan.yaml
- platform/bases/knative/config/config.yaml
- platform/bases/knative/config/queues.yaml
- platform/bases/kustomization.yaml
- platform/overlays/gke/knative/config/queues.yaml
- services/auto-scan/cloudbuild.yaml
- services/db-migration/cloudbuild.yaml
- services/result-queue/cloudbuild.yaml
- services/scan-queue/cloudbuild.yaml
- services/scanners/dns/cloudbuild.yaml
- services/scanners/https/cloudbuild.yaml
- services/scanners/results/cloudbuild.yaml
- services/scanners/ssl/cloudbuild.yaml
Hopefully makes flux happy with scanner image names!
> Fix tags for flux

- frontend/package-lock.json
- frontend/package.json
This commit resolves warning we were getting about certain dependencies
existing in both dev and production.
> Remove duplicated deps

- frontend/package-lock.json
- frontend/package.json
> Update to supertest 6

- frontend/src/DomainCard.js
- frontend/src/__tests__/FloatingMenu.test.js
- frontend/src/__tests__/OrganizationCard.test.js
- frontend/src/setupTests.js
This commit has a handful of minor tweaks to solve some of the things
generating warnings in the tests.
> Fix warnings in tests

- frontend/src/FloatingMenu.js
> Fe fix mobile menu icons

- frontend/src/AdminDomains.js
This page is going to get a refactor soon, but for the moment its WONTFIX
> Silence lint warning for exhaustive deps

- api-js/src/types/base/index.js
Implementing user affiliation base type and corresponding fields in user and organization objects.
> User affiliation base type

- api-js/src/__tests__/sign-in.test.js
Fixed flaky sign in test, by pulling the auth token from the response, not sure there is any other way of doing this
> API Fixing Flaky Test

- api-js/cloudbuild.yaml
> increase js api build timeout to 20 mins

- api-js/src/__tests__/create-organization.test.js
- api-js/src/__tests__/load-organization-by-key.test.js
- api-js/src/__tests__/load-organization-by-slug.test.js
- api-js/src/__tests__/remove-domain.test.js
- api-js/src/__tests__/remove-organization.test.js
- api-js/src/__tests__/update-domain.test.js
- api-js/src/__tests__/update-user-role.test.js
- api-js/src/loaders/organizations/load-organization-by-key.js
- api-js/src/loaders/organizations/load-organization-by-slug.js
- api-js/src/loaders/organizations/load-organization-connections-by-domain-id.js
- api-js/src/loaders/organizations/load-organization-connections-by-user-id.js
- api-js/src/mutations/domain/remove-domain.js
- api-js/src/mutations/organizations/create-organization.js
- api-js/src/mutations/organizations/remove-organization.js
- api-js/src/queries/verified-domains/find-verified-domains.js
- api-js/src/types/base/index.js
Replace all instances of `blueCheck` to `verified`
> BlueCheck is no more lets welcome Verified

- api-js/src/__tests__/verify-organization.test.js
- api-js/src/locale/en/messages.js
- api-js/src/locale/en/messages.po
- api-js/src/locale/fr/messages.js
- api-js/src/locale/fr/messages.po
- api-js/src/mutations/organizations/index.js
- api-js/src/mutations/organizations/verify-organization.js
`verifyOrganization` mutation introduction
- allows only super admins to verify an org
- includes 100 coverage testing
> Verify Your Orgs Today!

- api-js/src/__tests__/load-dkim-guidance-tags-connections.test.js
- api-js/src/__tests__/load-dmarc-guidance-tags-connections.test.js
- api-js/src/__tests__/load-https-guidance-tags-connections.test.js
- api-js/src/__tests__/load-organization-connections-by-user-id.test.js
- api-js/src/__tests__/load-spf-guidance-tags-connections.test.js
- api-js/src/__tests__/load-ssl-guidance-tags-connections.test.js
- api-js/src/__tests__/load-user-affiliations-by-org-id.test.js
- api-js/src/__tests__/load-user-affiliations-by-user-id.test.js
- api-js/src/__tests__/spf-connection-query.test.js
- api-js/src/loaders/dmarc-report/load-dmarc-report.js
- api-js/src/loaders/guidance-tags/index.js
> Get API Codebase properly formatted, and tiny fix

- api-js/src/__tests__/dmarc-summary-by-period.test.js
- api-js/src/__tests__/period.test.js
- api-js/src/__tests__/yearly-dmarc-summaries.test.js
- api-js/src/types/base/dmarc-report/period.js
Switching field types to an Enum, and Scalar
> Dmarc Report Period Refactor

- api-js/src/__tests__/find-domain-by-domain.test.js
- api-js/src/__tests__/find-my-domains.test.js
- api-js/src/__tests__/find-verified-domain-by-domain.test.js
- api-js/src/__tests__/find-verified-domains.test.js
- api-js/src/enums/index.js
- api-js/src/enums/status.js
- api-js/src/types/base/domain-status.js
- api-js/src/types/base/index.js
- api-js/src/types/base/verified-objects.js
New status field to both the base domain type and the verified domain type
> Status field to domain object

- api-js/src/__tests__/dkim-result-connection-query.test.js
- api-js/src/__tests__/dmarc-connection-query.test.js
- api-js/src/__tests__/find-me.test.js
- api-js/src/__tests__/find-organization-by-slug.test.js
- api-js/src/__tests__/https-connection-query.test.js
- api-js/src/__tests__/load-user-affiliations-by-org-id.test.js
- api-js/src/__tests__/load-user-affiliations-by-user-id.test.js
- api-js/src/__tests__/spf-connection-query.test.js
- api-js/src/__tests__/ssl-connection-query.test.js
- api-js/src/loaders/user-affiliations/load-user-affiliations-by-org-id.js
- api-js/src/loaders/user-affiliations/load-user-affiliations-by-user-id.js
- api-js/src/locale/en/messages.js
- api-js/src/locale/en/messages.po
- api-js/src/locale/fr/messages.js
- api-js/src/locale/fr/messages.po
- api-js/src/types/base/index.js
Don't let the branch name confuse you, kinda spiralled away, however we now have 100 coverage on all base types and have surpassed 99% total coverage.
> Refactor tests to bring base types coverage to 100

- api-js/src/__tests__/notify-send-authenticate-email.test.js
- api-js/src/__tests__/notify-send-authenticate-text-msg.test.js
- api-js/src/__tests__/notify-send-org-invite-create-account.test.js
- api-js/src/__tests__/notify-send-org-invite-email.test.js
- api-js/src/__tests__/notify-send-password-reset-email.test.js
- api-js/src/__tests__/notify-send-tfa-text-msg.test.js
- api-js/src/__tests__/notify-send-verification-email.test.js
- api-js/src/locale/en/messages.po
- api-js/src/locale/fr/messages.po
- api-js/src/notify/index.js
- api-js/src/notify/notify-send-authenticate-email.js
- api-js/src/notify/notify-send-authenticate-text-msg.js
- api-js/src/notify/notify-send-org-invite-create-account.js
- api-js/src/notify/notify-send-org-invite-email.js
- api-js/src/notify/notify-send-password-reset-email.js
- api-js/src/notify/notify-send-tfa-text-msg.js
- api-js/src/notify/notify-send-verification-email.js
- api-js/src/server.js
This moves the notify client into the factory function rather than being passed in main function. This fixes the issues that were being brought up in the test coverage and brings us up to 99.2%
> Notfiy Function Refactors!

- api-js/src/mutations/user-affiliations/__tests__/invite-user-to-org.test.js
- api-js/src/mutations/user/__tests__/authenticate.test.js
- api-js/src/mutations/user/__tests__/sign-in.test.js
- api-js/src/mutations/user/__tests__/sign-up.test.js
Simple fix, just mocking the `tokenize` function with jest
> Fix Flaky Tests

- services/scanners/dns/dns_scanner.py
- services/scanners/results/result_processor.py
- services/scanners/results/tests/test_data.py
These changes update the parsing of scan results and subsequent tag generation.
DNS scanner has also been updated to ensure proper iteration through all 3rd party senders (both RUA and RUF).
> Amendments to guidance tag generation

- api-js/package-lock.json
- api-js/package.json
Quick PR to update the non-breaking changes dependencies, as the linguijs update will come later.
> Non-breaking Changes Dependency Updates

- frontend/src/graphql/queries.js
> Update web and email summary query to new api

- frontend/schema.faker.graphql
- frontend/src/SummaryGroup.js
- frontend/src/__tests__/SummaryGroup.test.js
- frontend/src/graphql/queries.js
> Fix landing page summaries & update faker

- frontend/src/AdminPage.js
- frontend/src/AdminPanel.js
- frontend/src/OrganizationDetails.js
- frontend/src/SummaryGroup.js
As described. Status attribute incorrectly set.
> Fix transparent toasts

- services/scanners/results/requirements.txt
- services/scanners/results/result_processor.py
- services/scanners/results/tests/test_data.py
- services/scanners/results/tests/test_result_processor.py
Updates the result processor tests to ensure they are run (fix async pytest issues). 
Resulting test failures have been fixed and all tests pass. Ran black
> Result processor test update

- services/core/core.py
- services/core/tests/test_core_service.py
Update core service tests to cover all summary update functions.
> Core service test update

- app/bases/knative/config/core.yaml
> Update core service container name

- guidance/tags_dkim.json
> added dkim tag for dupe keys

- services/scanners/results/result_processor.py
- services/scanners/results/tests/test_data.py
- services/scanners/results/tests/test_result_processor.py
Update result processor logic and tests to accommodate edge collections linking domains to scans. 
Addition of dkim10 (update-recommended) logic to assess public key use and recommend key rotation if necessary.
> Result processor logic update

- app/bases/knative/config/autoscan.yaml
- app/bases/knative/config/config.yaml
- app/bases/knative/config/queues.yaml
- services/auto-scan/autoscan.py
- services/auto-scan/requirements.txt
- services/auto-scan/tests/test_autoscan.py
- services/result-queue/result_queue.py
- services/scan-queue/scan_queue.py
- services/scanners/dns/dns_scanner.py
- services/scanners/https/https_scanner.py
- services/scanners/ssl/ssl_scanner.py
Alter the use of URLs throughout scanner code to make use of secrets for flexible URL support.
> URLs -> Secrets

- api-js/src/__tests__/create-context.test.js
- api-js/src/create-context.js
> Fixing auth token issue

- services/scan-queue/scan_queue.py
> Scan queue hotfix

- services/scanners/dns/requirements.txt
- services/scanners/https/requirements.txt
- services/scanners/results/requirements.txt
- services/scanners/ssl/requirements.txt
[2020-12-03 16:29:23 +0000] [70] [ERROR] Exception in worker process
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
worker.init_process()
File "/usr/local/lib/python3.8/dist-packages/uvicorn/workers.py", line 62, in init_process
super(UvicornWorker, self).init_process()
File "/usr/local/lib/python3.8/dist-packages/gunicorn/workers/base.py", line 140, in init_process
self.run()
File "/usr/local/lib/python3.8/dist-packages/uvicorn/workers.py", line 71, in run
loop.run_until_complete(server.serve(sockets=self.sockets))
File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
File "/usr/local/lib/python3.8/dist-packages/uvicorn/_impl/asyncio.py", line 54, in serve
config.load()
File …
> Addition of httptools requirement to scanners

- app/bases/knative/config/config.yaml
- services/scanners/dns/dns_scanner.py
- services/scanners/https/https_scanner.py
- services/scanners/results/result_processor.py
- services/scanners/results/tests/test_result_processor.py
- services/scanners/ssl/ssl_scanner.py
> Miscellaneous refactoring, tidying and dns scanner logic fix

- services/scanners/dns/dns_scanner.py
- services/scanners/https/https_scanner.py
- services/scanners/ssl/ssl_scanner.py
Improve code legibility and consistency across string formatting. Improve error resilience.
> Refactoring strings, catch error type in rua/ruf check (dns)

- api-js/src/auth/__tests__/check-domain-permission.test.js
- api-js/src/auth/check-domain-permission.js
- api-js/src/locale/en/messages.js
- api-js/src/locale/en/messages.po
- api-js/src/locale/fr/messages.js
- api-js/src/locale/fr/messages.po
This is a small refactor, adding in a check to see if the user has super admin permission, if so it bypasses the old check.
> Refactor To CheckDomainPermission Function

- services/scanners/results/result_processor.py
> Amendments to SPF and DKIM result processing

- services/scanners/results/result_processor.py
Ensures timestamp consistency within DNS scans.
> Generate timestamps immediately within insert functions.

- app/bases/tracker-api-deployment.yaml
> API Deployment Fix

- services/core/core.py
- services/core/tests/test_core_service.py
Miscellaneous fixes to core service
> Core service - Prod-ready

- api-js/src/types/__tests__/dkim-results.test.js
- api-js/src/types/__tests__/dmarc.test.js
- api-js/src/types/__tests__/https.test.js
- api-js/src/types/__tests__/spf.test.js
- api-js/src/types/__tests__/ssl.test.js
- api-js/src/types/base.js
Introducing a new `rawJson` field to the various scan result GraphQL objects.
> RawJson Field Introduction

- api-js/src/types/__tests__/dkim-results.test.js
Quick fix to solve a linting issue
> API Linting Issue Solved

- api-js/src/loaders/dmarc-report/__tests__/generate-detail-table-fields.test.js
- api-js/src/loaders/dmarc-report/__tests__/generate-gql-query.test.js
- api-js/src/loaders/dmarc-report/generate-detail-table-fields.js
- api-js/src/loaders/dmarc-report/generate-gql-query.js
Quick update to the query generation to limit the possible fields that can be queried.
> Aggregate Query Generation Updates

- app/bases/knative/config/config.yaml
- services/scanners/results/requirements.txt
- services/scanners/results/result_processor.py
- services/scanners/results/tests/test_data.py
- services/scanners/results/tests/test_result_processor.py
- services/scanners/results/utils.py
- services/scanners/ssl/requirements.txt
- services/scanners/ssl/ssl_scanner.py
- Simplifying SSL scan results before sending to result-processor for further dissection (improves the division of labour between scanner and processor)
- Get elliptic curves in use via SSLYZE
- Pull guidance file from Github repo and compare results against guidance to assess compliance
- Add fields to SSL result collection documents to improve verbosity of results
> Ssl scan update

- frontend/src/client.js
> Fix client link address

- frontend/src/UserCard.js
- frontend/src/UserPage.js
- frontend/src/__tests__/UserList.test.js
- frontend/src/__tests__/UserPage.test.js
- frontend/src/graphql/queries.js
- Changed the query on Userpage
- Usercards made unclickable as they now link to current user's page (to be fixed soon)
> FE UserPage hotfix

- api-js/README.md
This commit adds missing env vars to the README file to get the instructions in
sync with the actual code.
> Update getting started instructions

- api-js/src/mutations/user-affiliations/__tests__/invite-user-to-org.test.js
- api-js/src/mutations/user-affiliations/invite-user-to-org.js
This is a quick update to fix the routing issue in the email sent to the invited user.
> Invite User To Org Update

- api-js/package-lock.json
- api-js/package.json
- api-js/src/validators/__tests__/slugify.test.js
- api-js/src/validators/slugify.js
You're regularly scheduled API dependency update!
> API Dependency Updates

- frontend/src/graphql/mutations.js
> Update signIn Mutation

- app/bases/knative/config/autoscan.yaml
> Perform scans at 1am every second day

- frontend/src/App.js
> Remove organization link for unauthed users

- api-js/src/types/__tests__/organization-summary.test.js
- api-js/src/types/organization-summary.js
Fixing a possible division by zero in the org summary calculations
> Fixing Division by Zero

- frontend/src/SummaryGroup.js
Capitalized DMARC and removed "Policy" from the donut so there was no text-wrapping
> Cleaned up text to prevent wrapping

- frontend/src/graphql/mutations.js
Fixes "error" on sign up (removed affiliations field from mutation)
> Remove affiliations field from signUp mutation

- frontend/src/PasswordConfirmation.js
- frontend/src/PasswordField.js
> Make password viewing button unable to be tabbed to

- frontend/src/DmarcReportPage.js
Reordered table columns to make them easier to read/work with
> Reorded table columns to make things more clear

- api-js/src/loaders/dmarc-report/generate-detail-table-fields.js
> envelopeFrom Field Fix

- frontend/src/UserPage.js
Removed the button until the functionality exists.
> Remove API keys button from user page

- frontend/schema.faker.graphql
- frontend/src/App.js
- frontend/src/DomainCard.js
- frontend/src/OrganizationDetails.js
- frontend/src/__tests__/OrganizationDetails.test.js
- frontend/src/graphql/queries.js
- adds in error handling to org details page
- only scanned domains show results on DomainCards
- added pagination parameter to ORG_DEATILS_PAGE query domains and affiliations
> Fe fix indv org page

- services/super-admin/src/__tests__/super-admin-service.test.js
- services/super-admin/src/database/create-super-admin-account.js
- Small update to fix the account fields for the super admin account
> Super Admin Account DB Field Update

- frontend/src/SignInPage.js
Fix error handling for sign in mutation to allow incorrect password prompt to appear.
> Fix incorrect password prompt not appearing

- frontend/src/DmarcByDomainPage.js
> Fe round dmarc summary percentages

- frontend/src/ScanDomain.js
- frontend/src/__tests__/ScanDomain.test.js
- frontend/src/graphql/mutations.js
updated mutation and form to remove unused enum that caused failure
> Fix scan requests

- frontend/src/AdminPage.js
Increase number of organizations visible in admin page dropdown
> Fe increase orgs admin dropdown

- services/scanners/results/result_processor.py
- services/scanners/results/tests/test_data.py
- services/scanners/results/tests/test_result_processor.py
- services/scanners/results/utils.py
- services/scanners/ssl/requirements.txt
Also -- pins sslyze version to ensure future functionality remains unaltered
> Dmarc phase implementation

- frontend/package-lock.json
As advertised... just incrementing the patch level where possible.
> Bump patch levels of frontend deps

- frontend/src/locales/en.po
- frontend/src/locales/fr.po
This commit is the result of running
```
npm run extract -- --clean
```
> Clean up translations

- api-js/src/user/mutations/sign-in.js
> Fix non-tfa sign in token issue

- frontend/src/App.js
- frontend/src/PrivateRoute.js
- frontend/src/SignInPage.js
- frontend/src/TwoFactorAuthenticatePage.js
e.g. A signed out user attempting to navigate to /admin will be redirected to auth, they will be redirected to /admin after auth is complete.
> Add redirection to previous page after sign in

- frontend/src/CustomTooltipContent.js
- frontend/src/DmarcReportSummaryGraph.js
Fixes DMARC graph tool tip (component broke when hovering over bar).
Also adds percentage to tool tip.
> FE DMARC graph tool tip fix and add percent

- frontend/src/DmarcReportSummaryGraph.js
> Disable sliding animation for DMARC report graph tooltip

- frontend/src/ScanDomain.js
> add user context to REQUEST_SCAN mutation

- clients/python/Pipfile
- clients/python/Pipfile.lock
- clients/python/README.md
- clients/python/tracker_client.py
Implement the beginning of Tracker's Python client.
> Client implement get all domains

- frontend/src/DmarcGuidancePage.js
- frontend/src/DomainCard.js
- frontend/src/GuidanceTagDetails.js
- frontend/src/GuidanceTagList.js
- frontend/src/ScanCategoryDetails.js
- frontend/src/__tests__/DmarcGuidancePage.test.js
- frontend/src/__tests__/GuidanceTagDetails.test.js
- frontend/src/__tests__/GuidanceTagList.test.js
- frontend/src/__tests__/ScanCard.test.js
- frontend/src/__tests__/ScanCategoryDetails.test.js
- frontend/src/fixtures/dmarcGuidancePageData.js
- frontend/src/graphql/queries.js
update Scan details dage to js-api
> Fe update scan page API

- frontend/src/UserList.js
As described
https://github.com/canada-ca/tracker/projects/3#card-53537502
> Remove "Super Admin" as option when inviting

- clients/python/Pipfile
- clients/python/Pipfile.lock
- clients/python/tracker_client.py
Implement ability to get the list of domains belonging to an organization by specifying either an acronym or full name.
> Client get domains by org

- frontend/src/CreateUserPage.js
- frontend/src/SignInPage.js
- frontend/src/TwoFactorAuthenticatePage.js
- frontend/src/graphql/mutations.js
Switches the site language to a user's preferred language upon sign in and account creation.
> Fe switch language on signin

- scripts/codemods/README.md
- scripts/codemods/package-lock.json
- scripts/codemods/package.json
- scripts/codemods/replace-console-with-log.js
- scripts/codemods/test.js
This script has not be run yet, it's just being added as a small example: renaming console.log to something else. This is a
working example now, but will be expanded on later.
> Add script for replacing console.log

- services/dmarc-report/src/loaders/load-summary-by-date.js
Missed this, but need it for pagination
> Pull Id for cursor

- frontend/src/EditableUserDisplayName.js
- frontend/src/EditableUserEmail.js
- frontend/src/EditableUserLanguage.js
- frontend/src/EditableUserPhoneNumber.js
- frontend/src/EditableUserTFAMethod.js
Fixes user profile information not being successfully updated.
> Fix user profile mutations

- api-js/src/dmarc-summaries/loaders/__tests__/load-dkim-failure-connections-by-sum-id.test.js
- api-js/src/dmarc-summaries/loaders/__tests__/load-dmarc-failure-connections-by-sum-id.test.js
- api-js/src/dmarc-summaries/loaders/__tests__/load-full-pass-connections-by-sum-id.test.js
- api-js/src/dmarc-summaries/loaders/__tests__/load-spf-failure-connections-by-sum-id.test.js
- api-js/src/dmarc-summaries/loaders/index.js
- api-js/src/dmarc-summaries/loaders/load-dkim-failure-connections-by-sum-id.js
- api-js/src/dmarc-summaries/loaders/load-dmarc-failure-connections-by-sum-id.js
- api-js/src/dmarc-summaries/loaders/load-full-pass-connections-by-sum-id.js
- api-js/src/dmarc-summaries/loaders/load-spf-failure-connections-by-sum-id.js
- api-js/src/locale/en/messages.js
- api-js/src/locale/en/messages.po
- api-js/src/locale/fr/messages.js
- api-js/src/locale/fr/messages.po
- `dkimFailureLoaderConnectionsBySumId`
- Completed with 100% coverage
- `dmarcFailureLoaderConnectionsBySumId`
- Completed with 100% coverage
- `fullPassLoaderConnectionsBySumId`
- Completed with 100% coverage
- `spfFailureLoaderConnectionsBySumId`
- Completed with 100% coverage
> Dmarc Summary Detail Table Loaders

- api-js/src/enums/period.js
> fix last thirty day enum value issue

- api-js/src/dmarc-summaries/objects/__tests__/dmarc-summary.test.js
- api-js/src/dmarc-summaries/objects/dmarc-summary.js
- api-js/src/domain/objects/__tests__/domain.test.js
- api-js/src/domain/objects/domain.js
Fixes to undefined or invalid values when returning data
> Undefined or Invalid Values Fixes

- api-js/src/domain/objects/__tests__/domain.test.js
- api-js/src/domain/objects/domain.js
> Replace _id with _key

- services/dmarc-report/src/database/update-thirty-days.js
thirty_days is not equal to thirtyDays
> FIx Thirty Days Issue

- app/bases/kustomization.yaml
This reverts commit acb0a3a573d85aaaafff44fc37c7ccaad2baf7e1.
> Revert "Auto-release gcr.io/track-compliance/api-js:master-7d49433"

- app/aks/README.md
- app/aks/arangodb.yaml
- app/aks/envoy-filter.yaml
- app/aks/istio-ingressgateway-service.yaml
- app/aks/jaeger.yaml
- app/aks/kiali.yaml
- app/aks/knative/config/queues.yaml
- app/aks/kustomization.yaml
- app/aks/publicgateway.yaml
- app/aks/selfsigned-issuer.yaml
- app/aks/tracker-api-deployment.yaml
- app/aks/tracker-frontend-deployment.yaml
- platform/aks/README.md
- platform/aks/domain-config.yaml
- platform/aks/knative-istio-networking.yaml
- platform/aks/knative-serving-core.yaml
- platform/aks/kustomization.yaml
This is the first draft of AKS support. More to follow.
> Add basic overlays for AKS

- frontend/schema.faker.graphql
- frontend/src/DmarcByDomainPage.js
- frontend/src/fixtures/dkimFailureData.js
- frontend/src/fixtures/dmarcFailureData.js
- frontend/src/fixtures/dmarcReportGraphData.js
- frontend/src/fixtures/dmarcReportSummaryTable.js
- frontend/src/fixtures/fullPassData.js
- frontend/src/fixtures/spfFailureData.js
- frontend/src/graphql/queries.js
Updates the DMARC queries after a change to the api. Also includes a required change to the cache and DmarcByDomainPage.js due to these changes.
> Fe update dmarc queries

- api-js/src/dmarc-summaries/objects/__tests__/detail-tables.test.js
- api-js/src/dmarc-summaries/objects/detail-tables.js
- frontend/src/DmarcByDomainPage.js
> Fix domains not showing on DMARC summary table

- services/dmarc-report/src/database/initialize-summaries.js
simple fix, just needed to move conditional statement down after pulling the summary.
> Fix Thirty Day Being Empty On Initialization

- frontend/src/DomainCard.js
> Fix alignment on DomainCard.js

- README.md
Update the repo's README to reflect removal of Python API and addition of clients folder. 
Fixed some awkward phrasing/grammar issues as well.
> Update project root README

- README.md
This PR makes that one  ` | ` not red.
> Update README to remove the one red pipe character

- app/aks/kustomization.yaml
Just to make the experimentation easier.
> Use dev creds in aks

- api-js/src/domain/objects/__tests__/domain.test.js
- api-js/src/domain/objects/domain.js
Add `dmarcPhase` field to the `domain` gql object.
> Adding DMARC Phase to Domain GQL

- platform/flux/patch.yaml
> Give flux more CPU

- platform/flux/bases/flux-deployment.yaml
- platform/flux/patch.yaml
This is the end of the line for Flux 1. Experimentation with Flux 2 has begun.
> Update to the last release of Flux 1

- frontend/src/DmarcGuidancePage.js
- frontend/src/ScanCard.js
- frontend/src/fixtures/dmarcGuidancePageData.js
- frontend/src/graphql/queries.js
- frontend/src/locales/en.po
- frontend/src/locales/fr.po
Fix query after dmarcPhase was moved
> Move dmarcPhase in GET_GUIDANCE_TAGS_OF_DOMAIN query

- app/aks/kustomization.yaml
- app/test/kustomization.yaml
Appropriate creds can be added separately.
> Remove creds from test and aks config

- clients/python/tests/conftest.py
- clients/python/tracker_client/formatting.py
- clients/python/tracker_client/queries.py
This PR updates the client for the deprecation of the guidanceTags field.
> Client fix guidance

- api-js/cloudbuild.yaml
- frontend/cloudbuild.yaml
This commit adds a unix timestamp to allow us to sort the images as per the new
flux docs:
https://toolkit.fluxcd.io/guides/sortable-image-tags/
> Use sortable image tags

- api-js/cloudbuild.yaml
- frontend/cloudbuild.yaml
This commit writes an image name to the cloudbuild workspace so it can be used
in the build and push steps.
> Fix timestamp silliness

- api-js/Dockerfile
- api-js/package.json
> replace migration.js with database-options.js

- frontend/schema.faker.graphql
Just your regularly "scheduled" faker update, including changes for:
- Field additions to `SSL`
- Basic Field Type Updates (`String -> Date`, etc.)
- Ordering for various connections (`DKIM`, `DMARC`, `Domain`, etc.)
> Updating Faker

- app/gke/certificate.yaml
- app/gke/publicgateway.yaml
- platform/components/istio/envoy-security-headers-filter.yaml
This commit adds comments to our current k8s config showing where it implements
the various requirements of the ITPIN for HTTPS: https://bit.ly/3qfVqhd
> Connect code to policy

- api-js/src/server.js
> Enable Apollo Tracing

- clients/python/cloudbuild.yaml
- clients/python/tests/test_core.py
Adds `cloudbuild.yaml` to automate linting and testing for client files.
> Client add CI

- api-js/src/affiliation/mutations/__tests__/invite-user-to-org.test.js
- api-js/src/affiliation/mutations/invite-user-to-org.js
Small fix to ensure that the users permission is not`undefined` for a given org.
> Invite User to Org Permission Check Fix

- api-js/src/locale/en/messages.po
- api-js/src/locale/fr/messages.po
- api-js/src/user/mutations/__tests__/update-user-profile.test.js
- api-js/src/user/mutations/update-user-profile.js
Add in a check to ensure username is not already in use.
> Small Fix For updateUserProfile Mutation

- api-js/src/email-scan/objects/__tests__/dkim.test.js
- api-js/src/email-scan/objects/__tests__/dmarc.test.js
- api-js/src/email-scan/objects/__tests__/spf.test.js
- api-js/src/email-scan/objects/dkim.js
- api-js/src/email-scan/objects/dmarc.js
- api-js/src/email-scan/objects/email-scan.js
- api-js/src/email-scan/objects/spf.js
- api-js/src/verified-domains/objects/__tests__/verified-domain.test.js
- api-js/src/verified-domains/objects/verified-domain.js
- api-js/src/web-scan/objects/__tests__/https.test.js
- api-js/src/web-scan/objects/__tests__/ssl.test.js
- api-js/src/web-scan/objects/https.js
- api-js/src/web-scan/objects/ssl.js
- api-js/src/web-scan/objects/web-scan.js
- frontend/schema.faker.graphql
- Fix naming of `starDate` to `startDate` (sorry Jim)
- Fix incorrect GraphQL type on the argument `timestamp` from `GraphQLString` to `GraphQLDate`
- Faker has been updated to match changes
> Small Cleanup for the API

- frontend/src/graphql/mutations.js
> Fix UpdateUserProfile Mutation String

- .github/dependabot.yml
Lower open-pull-request-limit to 5.
> Reduce open-pull-request-limit

- api-js/src/locale/en/messages.js
- api-js/src/locale/en/messages.po
- api-js/src/locale/fr/messages.js
- api-js/src/locale/fr/messages.po
- api-js/src/user/mutations/__tests__/update-user-password.test.js
- api-js/src/user/mutations/__tests__/update-user-profile.test.js
- api-js/src/user/mutations/__tests__/verify-phone-number.test.js
- api-js/src/user/mutations/update-user-password.js
- api-js/src/user/mutations/update-user-profile.js
- api-js/src/user/mutations/verify-phone-number.js
Just a little clean up replacing checks with a function for consistency across the API.
> Use Authorization Function in User Mutations

- api-js/src/user/mutations/__tests__/verify-phone-number.test.js
- api-js/src/user/mutations/verify-phone-number.js
- api-js/src/user/objects/__tests__/verify-phone-number-result.test.js
- api-js/src/user/objects/verify-phone-number-result.js
- frontend/schema.faker.graphql
> Add User Field in VerifyPhoneNumberResult

- services/dmarc-report/Dockerfile
- services/super-admin/Dockerfile
Missed the name change in the docker file when updating these services.
> JS Services Dockerfile fixes

- api-js/src/dmarc-summaries/loaders/__tests__/load-dmarc-sum-connections-by-user-id.test.js
- api-js/src/domain/loaders/__tests__/load-domain-conn-org-id.test.js
- api-js/src/domain/loaders/__tests__/load-domain-connections-by-user-id.test.js
- api-js/src/email-scan/loaders/__tests__/load-dkim-connections-by-domain-id.test.js
- api-js/src/email-scan/loaders/__tests__/load-dkim-results-connections-by-dkim-id.test.js
- api-js/src/email-scan/loaders/__tests__/load-dmarc-connections-by-domain-id.test.js
- api-js/src/email-scan/loaders/__tests__/load-spf-connections-by-domain-id.test.js
- api-js/src/guidance-tag/loaders/__tests__/load-dkim-guidance-tags-connections.test.js
- api-js/src/guidance-tag/loaders/__tests__/load-dmarc-guidance-tags-connections.test.js
- api-js/src/guidance-tag/loaders/__tests__/load-https-guidance-tags-connections.test.js
- api-js/src/guidance-tag/loaders/__tests__/load-spf-guidance-tags-connections.test.js
- api-js/src/guidance-tag/loaders/__tests__/load-ssl-guidance-tags-connections.test.js
- api-js/src/organization/loaders/__tests__/load-organization-connections-by-domain-id.test.js
- api-js/src/organization/loaders/__tests__/load-organization-connections-by-user-id.test.js
- api-js/src/verified-domains/loaders/__tests__/load-verified-domain-conn-by-org-id.test.js
- api-js/src/verified-domains/loaders/__tests__/load-verified-domain-connections.test.js
- api-js/src/verified-organizations/loaders/__tests__/load-verified-org-conn-by-domain-id.test.js
- api-js/src/verified-organizations/loaders/__tests__/load-verified-org-conn.test.js
- api-js/src/web-scan/loaders/__tests__/load-https-connections-by-domain-id.test.js
- api-js/src/web-scan/loaders/__tests__/load-ssl-connections-by-domain-id.test.js
Removing some redundant tests that were causing some flakiness, so hopefully with these removed we can get rid of it.
> Remove Redundant Tests

- frontend/src/Footer.js
- frontend/src/LandingPage.js
The abstraction the Layout component creates is not a useful one. This is the
first step in removing it, allowing us to shave some memory use and bytes
transferred.
> Remove Layout from Footer and LandingPage

- services/dmarc-report/package-lock.json
- services/dmarc-report/package.json
> Update DMARC Report Dependencies

- frontend/src/DmarcByDomainPage.js
- frontend/src/DomainsPage.js
- frontend/src/OrganizationAffiliations.js
- frontend/src/OrganizationDomains.js
- frontend/src/Organizations.js
- frontend/src/__tests__/DomainsPage.test.js
- frontend/src/__tests__/OrganizationAffiliations.test.js
- frontend/src/__tests__/OrganizationDetails.test.js
- frontend/src/__tests__/OrganizationDomains.test.js
- frontend/src/__tests__/Organizations.test.js
- frontend/src/__tests__/ScanDomain.test.js
- frontend/src/graphql/queries.js
This PR removes all queries used for reverse pagination as they are no longer being used anywhere.
> Fe remove reverse pagination

- frontend/src/App.js
- frontend/src/locales/en.js
- frontend/src/locales/en.po
- frontend/src/locales/fr.js
- frontend/src/locales/fr.po
This PR just throws in a new link to `App.js` that provides a link to the issues section of the repo in case the user finds an issue.
> Introduce Report an Issue Link

- frontend/src/AdminDomains.js
- frontend/src/DomainsPage.js
- frontend/src/Organizations.js
- frontend/src/ScanDomain.js
- frontend/src/UserList.js
- frontend/src/locales/en.js
- frontend/src/locales/en.po
- frontend/src/locales/fr.js
- frontend/src/locales/fr.po
This PR disables the search bars, which will be re-enabled once searching is implemented in the API. As well this PR changes the text on the admin page to `Add a domain` and `Invite a user`.
> Disable Search Bars

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- CONTRIBUTING.md
- SECURITY.md
This PR introduces a couple of markdown files for the repo including:
- Contributing Guide
- Security Policy
- Issue Templates
- Bug Reports
- Feature Requests
> Create New Markdown Files

- app/README.md
- app/bases/knative/config/dmarc-report.yaml
- app/bases/kustomization.yaml
- app/creds/dev/kustomization.yaml
- app/creds/prod/kustomization.yaml
- deploy/bases/dmarc-report-registry.yaml
- deploy/bases/kustomization.yaml
- deploy/gke/dmarc-report-image-policy.yaml
- deploy/gke/kustomization.yaml
This PR adds a service to automate importation of DMARC aggregate data.
> Automate DMARC aggregate imports

- services/dmarc-report/cloudbuild.yaml
This commit adds tags that flux knows how to sort, making the tags match the
policy for automated deployments.
> Add sortable image tags for dmarc-report image

- frontend/src/locales/fr.po
> Add more french translations

- services/dmarc-report/Dockerfile
> Fix dmarc-report service docker image

- services/scanners/results/result_processor.py
This PR fixes a NameError that occurred rarely in result_processor.py because of a reference to a no longer existing `tags` variable.
> Fix rare NameError in result_processor.py

- api-js/package-lock.json
- api-js/package.json
Your regularly scheduled package update.
> API Update Packages

- services/dmarc-report/package-lock.json
- services/dmarc-report/package.json
> DMARC Report Service Package Updates

- services/super-admin/package-lock.json
- services/super-admin/package.json
> Super Admin Service Dependency Updates

- app/bases/knative/config/config.yaml
- deploy/bases/dns-scanner-registry.yaml
- deploy/bases/https-scanner-registry.yaml
- deploy/bases/kustomization.yaml
- deploy/bases/result-processor-registry.yaml
- deploy/bases/ssl-scanner-registry.yaml
- deploy/gke/dns-scanner-image-policy.yaml
- deploy/gke/https-scanner-image-policy.yaml
- deploy/gke/kustomization.yaml
- deploy/gke/result-processor-image-policy.yaml
- deploy/gke/ssl-scanner-image-policy.yaml
- services/scanners/dns/cloudbuild.yaml
- services/scanners/https/cloudbuild.yaml
- services/scanners/results/cloudbuild.yaml
- services/scanners/ssl/cloudbuild.yaml
This PR adds the files necessary for flux to automate deployment of new container images for scanners (including results processing).
> Set up flux for scanner image updates

- api-js/src/server.js
> Disable apollo-tracing

- frontend/package-lock.json
- frontend/package.json
- frontend/webpack.config.js
This commit fixes the ERR_UNKNOWN_URL_SCHEME errors we were seeing during local
development and closes #2044
> Add Source-map loader

- api-js/src/enums/dmarc-summary-order-field.js
- frontend/schema.faker.graphql
> Align dmarc summary order fields

- services/super-admin/package-lock.json
- services/super-admin/package.json
> Super Admin Service Deps Update

- app/gke/README.md
- app/test/README.md
> Update readmes with current gcp settings

- .github/workflows/codeql-analysis.yml
This commit sets codeql to run once a week on Tuesdays. Starting small to see what we get!
> Enable codeql scanning

- api-js/src/domain/queries/__tests__/find-my-domains.test.js
- api-js/src/domain/queries/find-my-domains.js
- api-js/src/organization/queries/__tests__/find-my-organizations.test.js
- api-js/src/organization/queries/find-my-organizations.js
This PR fixes some issues in queries where the connection loader was put in a try catch, which was ruining the underlying try catch blocks.
> Fix Try Catch Errors

- api-js/database-options.js
> Add new Aggregate Guidance Tag Collection

- frontend/src/PhoneNumberField.js
> Fe always show phone number help

- frontend/src/EditableUserTFAMethod.js
- frontend/src/__tests__/EditableUserTFAMethod.test.js
- frontend/src/locales/en.po
- frontend/src/locales/fr.po
Clarifies terminology on the Your Account page
> Clarify terminology for TFA

- services/super-admin/README.md
Add example of test.env file with values.
> Update super-admin service readme

- services/super-admin/cloudbuild.yaml
This commit changes cloudbuild to create a sortable tag name for super-admin
images... the first step towards automating it's deployments.
> Give super admin service a sortable image tag

- services/super-admin/cloudbuild.yaml
> Fix super-admin image build directory

- frontend/schema.faker.graphql
- frontend/src/GuidanceTagDetails.js
- frontend/src/GuidanceTagList.js
- frontend/src/ScanCard.js
- frontend/src/ScanCategoryDetails.js
- frontend/src/TrackerButton.js
- frontend/src/client.js
- frontend/src/graphql/queries.js
- frontend/src/locales/en.po
- frontend/src/locales/fr.po
Scan categories and guidance tags are now collapsible
> Scan categories and guidance tags are now collapsable

- Makefile
- README.md
- app/README.md
This commit adds a makefile to reduce the amount of fiddling required to stand
up tracker. Readme files have been updated to reflect this.
> Simplify setup with a Makefile

- services/super-admin/package-lock.json
- services/super-admin/package.json
> Super Admin Dependency Updates

- clients/python/Pipfile.lock
> Update Python client dependencies

- services/auto-scan/README.md
- services/auto-scan/autoscan.py
- services/auto-scan/tests/test_autoscan.py
- services/result-queue/README.md
- services/result-queue/result_queue.py
- services/scan-queue/README.md
- services/scan-queue/scan_queue.py
This PR adds docstrings to the Python source for Autoscan, the scan queue and result queue, and READMEs to all of their root directories.
> Document autoscan and queues

- services/scanners/https/https_scanner.py
Fixes logic resulting in invalid scan results.
> Fix erroneous logic

- api-js/src/dmarc-summaries/objects/__tests__/dkim-failure-table.test.js
- api-js/src/dmarc-summaries/objects/__tests__/dmarc-failure-table.test.js
- api-js/src/dmarc-summaries/objects/__tests__/full-pass-table.test.js
- api-js/src/dmarc-summaries/objects/__tests__/spf-failure-table.test.js
- api-js/src/dmarc-summaries/objects/dkim-failure-table.js
- api-js/src/dmarc-summaries/objects/dmarc-failure-table.js
- api-js/src/dmarc-summaries/objects/full-pass-table.js
- api-js/src/dmarc-summaries/objects/spf-failure-table.js
- frontend/schema.faker.graphql
This reverts commit 6e43160371b4033cadf9841cf9d5cbb2276e7cfd.
> Revert "Updating Detail Table Fields to use DomainScalar (#2190)"

- services/super-admin/index.js
- services/super-admin/src/super-admin-service.js
Remove default value, and just pass it when being called.
> Fix Testing Coverage

- app/test/README.md
> Update instructions for making a test cluster

- api-js/database-options.js
chartSummaryCriteria, not chartsummarycriteria.
> Correctly camelCase collection name

- Makefile
Now you can do
```
make backup
make restore from=somedir
```
> Add backup/restore commands to makefile

- api-js/src/domain/mutations/__tests__/create-domain.test.js
- api-js/src/organization/mutations/__tests__/verify-organization.test.js
- api-js/src/user/mutations/__tests__/reset-password.test.js
- api-js/src/user/mutations/__tests__/sign-in.test.js
- api-js/src/user/mutations/__tests__/sign-up.test.js
- api-js/src/user/mutations/__tests__/update-user-password.test.js
- api-js/src/user/mutations/sign-up.js
When users are signing up, they will now be sent a link to their email to verify their account.
> Send Verification Email during Sign Up

- frontend/src/UserList.js
- frontend/src/fixtures/orgUserListData.js
- frontend/src/graphql/mutations.js
- frontend/src/graphql/queries.js
- frontend/src/locales/en.po
- frontend/src/locales/fr.po
> Fe add remove user button

- frontend/src/AdminDomains.js
- frontend/src/App.js
- frontend/src/AuthenticateField.js
- frontend/src/CreateUserPage.js
- frontend/src/DmarcByDomainPage.js
- frontend/src/DmarcReportPage.js
- frontend/src/DmarcReportTable.js
- frontend/src/DomainCard.js
- frontend/src/DomainsPage.js
- frontend/src/FloatingMenu.js
- frontend/src/Footer.js
- frontend/src/ForgotPasswordPage.js
- frontend/src/OrganizationCard.js
- frontend/src/OrganizationDetails.js
- frontend/src/OrganizationSummary.js
- frontend/src/Organizations.js
- frontend/src/PageNotFound.js
- frontend/src/ResetPasswordPage.js
- frontend/src/ScanDomain.js
- frontend/src/SignInPage.js
- frontend/src/TrackerButton.js
- frontend/src/TwoFactorAuthenticatePage.js
- frontend/src/UserList.js
- frontend/src/UserPage.js
- frontend/src/locales/en.po
- frontend/src/locales/fr.po
- All loading messages now use the component
- fixed consistency problems across the app (toasts, text alignment, padding, collapse buttons, etc.)
- added padding where needed (closes #2179)
- Removes footer on mobile
- Added 'Report an Issue" to mobile menu
- added link buttons to organization cards for better mobile usability
- added link buttons to domain cards for better mobile usability
> General Styling Improvements

- frontend/src/AdminDomains.js
- frontend/src/AdminPage.js
- frontend/src/AdminPanel.js
- frontend/src/Domain.js
- frontend/src/UserList.js
- frontend/src/__tests__/AdminPanel.test.js
- frontend/src/__tests__/UserList.test.js
- frontend/src/fixtures/orgUserListData.js
- frontend/src/graphql/queries.js
- frontend/src/locales/en.po
- frontend/src/locales/fr.po
- Domains and users separated into tabs
- user role modification moved behind "edit" button
> Revamped Admin Page

- frontend/src/client.js
> Update client uri

- api-js/src/locale/en/messages.po
- api-js/src/locale/fr/messages.po
- api-js/src/organization/objects/organization-summary.js
This removes the translations for the various summaries in the organization GQL object.
> Remove Organization Summary Category Translations

- frontend/src/AdminDomains.js
> Fix successful create domain toast

- frontend/src/AdminDomains.js
> Refetch queries when removal/modification of domain

- frontend/mocking/faked_schema.js
- frontend/src/Organizations.js
- frontend/src/__tests__/Organizations.test.js
- frontend/src/graphql/queries.js
> Remove SA org from Organizations page

- frontend/src/UserList.js
> Update admin user list when adding or removing users

- api-js/src/user/mutations/__tests__/sign-up.test.js
- api-js/src/user/mutations/sign-up.js
Adds alias to parameter so it is now defined.
> Fix Undefined User Error on Sign Up

- api-js/src/affiliation/mutations/invite-user-to-org.js
- api-js/src/affiliation/mutations/update-user-role.js
- api-js/src/user/queries/find-user-by-username.js
Adds `toLowerCase()` to cleansed args.
Closes #2264
> Lower All Usernames

- frontend/src/AdminDomains.js
> Add form to add-domain area

- frontend/src/AdminPage.js
- frontend/src/graphql/queries.js
> Order admin page organizations by acronyms

- platform/README.md
> Update platform readme.

- api-js/src/auth/__tests__/check-domain-ownership.test.js
- api-js/src/auth/check-domain-ownership.js
- api-js/src/domain/objects/__tests__/domain.test.js
- api-js/src/domain/objects/domain.js
- api-js/src/locale/en/messages.js
- api-js/src/locale/en/messages.po
- api-js/src/locale/fr/messages.po
This PR adds in a new field on the domain object titled `hasDMARCReport`, it is a boolean value to help determine whether or not to either display a `DMARC Report` btn or link to the dmarc report from the guidance page. I also had to update the `checkDomainOwnership` function to properly support those users who are super admins.
> Add hasDMARCReport Field to the Domain Obj

- services/super-admin/package-lock.json
- services/super-admin/package.json
> Super Admin Service Dependency Update

- services/dmarc-report/package-lock.json
- services/dmarc-report/package.json
- services/dmarc-report/src/database/__tests__/upsert-ownership.test.js
- services/dmarc-report/src/database/upsert-ownership.js
> DMARC Report Service Dependency Update

- frontend/src/AdminDomains.js
- frontend/src/DomainsPage.js
- frontend/src/Organizations.js
- frontend/src/__tests__/AdminDomains.test.js
- frontend/src/client.js
- frontend/src/graphql/queries.js
- frontend/src/useDebounce.js
Adds debounce to the following search areas to reduce number of calls to api:
- Admin Page - domains section (also adds search in the first place)
- Organizations list page
- Domains list page
> Fe add debounce to searches

- scripts/loadtesting/.prettierrc
- scripts/loadtesting/README.md
- scripts/loadtesting/frontend.js
- scripts/loadtesting/package-lock.json
- scripts/loadtesting/package.json
This commit adds a simple script for testing the frontend with [k6](https://k6.io/).
> Add k6 loadtesting script

- api-js/database-options.js
- api-js/src/affiliation/loaders/__tests__/load-affiliation-connections-by-org-id.test.js
- api-js/src/affiliation/loaders/__tests__/load-affiliation-connections-by-user-id.test.js
- api-js/src/affiliation/loaders/load-affiliation-connections-by-org-id.js
- api-js/src/affiliation/loaders/load-affiliation-connections-by-user-id.js
- api-js/src/organization/loaders/load-organization-connections-by-user-id.js
- api-js/src/organization/objects/organization.js
- api-js/src/user/objects/__tests__/user-shared.test.js
- api-js/src/user/objects/user-personal.js
- api-js/src/user/objects/user-shared.js
This PR adds a search argument to affiliation connections in the `Organization` type, and `UserPersonal` type.
Closes #2294
> Add Search to Affiliation Connections

- api-js/src/affiliation/loaders/load-affiliation-connections-by-org-id.js
- api-js/src/affiliation/loaders/load-affiliation-connections-by-user-id.js
This PR updates the condition when checking to see if the search functionality needs to be used.
> Update Affiliation Search Condition 

- api-js/src/verified-organizations/loaders/__tests__/load-verified-org-conn-by-domain-id.test.js
The goal here is more isolation, and fewer db interactions.
> Refactor load-verified-org-conn-by-domain-id test

- api-js/src/domain/loaders/load-domain-connections-by-organizations-id.js
- api-js/src/domain/loaders/load-domain-connections-by-user-id.js
This adds in another condition to `if` statement for enabling searching for the domain connection queries.
> Update Domain Searching if Conditions

- frontend/src/UserList.js
- frontend/src/__tests__/UserList.test.js
- frontend/src/graphql/queries.js
> Fe add search for users

- frontend/src/UserList.js
- frontend/src/__tests__/UserList.test.js
- frontend/src/graphql/queries.js
Reverts canada-ca/tracker#2336
> Revert "Fe add search for users"

- frontend/cloudbuild.yaml
> Increase cloudbuild timeout to 1200s

- frontend/src/UserList.js
- frontend/src/__tests__/UserList.test.js
- frontend/src/graphql/queries.js
This reverts commit 3282885c05486b9d352ecde98a5337efeefcabef.
> Revert "Revert "Fe add search for users (#2336)" (#2348)"

- deploy/bases/super-admin-registry.yaml
- deploy/gke/super-admin-image-policy.yaml
> Automate super admin image deployments.

- README.md
Update description to capture current folder structure, and include more policy links.
> Update project readme.

- frontend/src/CreateUserPage.js
- frontend/src/SignInPage.js
- frontend/src/TrackerButton.js
adds a new TrackerButton variant,
It uses the same format as the create account and back button during sign in and sign up
> TrackerButton new variant, primary outline

- api-js/src/locale/en/messages.js
- api-js/src/locale/en/messages.po
- api-js/src/locale/fr/messages.js
- api-js/src/locale/fr/messages.po
- api-js/src/user/queries/__tests__/is-user-super-admin.test.js
- api-js/src/user/queries/index.js
- api-js/src/user/queries/is-user-super-admin.js
- frontend/mocking/faked_schema.js
- frontend/src/AdminPage.js
- frontend/src/UserList.js
- frontend/src/graphql/queries.js
Super Admins now see all available orgs and have correct privileges on Admin page
> Fe fix admin afilliations

- services/core/cloudbuild.yaml
As advertised. This is the first step to automating deployments.
> Use sortable tag name for the core service

- app/bases/knative/config/core.yaml
- app/jobs/core-job.yaml
- deploy/bases/core-registry.yaml
- deploy/gke/core-image-policy.yaml
All the flux plumbing to automate updates of the core image.
> Automate core image updates

- frontend/src/AuthenticateField.js
This disables the autocomplete for the 2fa codes.
> Add autoComplete="off" to 2fa field.

- frontend/src/LocaleSwitcher.js
adds a transparent border so that the size doesn't change on hover
> FIx language buttons jumping on hover

- frontend/src/SignInPage.js
- frontend/src/TrackerButton.js
is a prerequisite for a couple changes
> Ux tracker button primary outline variant
